{
  "hash": "b66498250cd1ddf4bb06a7fbfa18b72e",
  "result": {
    "engine": "knitr",
    "markdown": "# Making decisions {#sec-conditionals}\n\n\n\nNobody reading a surveillance report sees \"1,426\" and thinks \"1,426\". They think \"bad day\". Most of what routine epidemiological reporting does is turn numbers into labels, and R hands you two entirely different tools for the job. One of them decides what your *script* does next. The other decides what goes in a *column*. Beginners reach for the first when they need the second roughly every time, and the result is either a red error or, worse, an answer that is correct for one row and quietly wrong for the other 344.\n\nThis chapter sorts out which is which, and then builds the column that turns 345 numbers into something you can put in a report: a severity label for every day of 2020.\n\n## Where we are\n\nEverything here starts from the daily counts you built in the previous chapter. The file ships cumulative totals, so a day's new cases is today's total minus yesterday's, and `lag(confirmed, default = 0)` supplies the \"yesterday\" for the very first row. That default matters: `confirmed` is 0 on 22 January, so day one had a real zero of new cases, not a missing one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read_covid() %>%\n  arrange(date) %>%\n  mutate(daily_cases = confirmed - lag(confirmed, default = 0))\n\ncovid %>%\n  select(date, confirmed, daily_cases) %>%\n  slice(85:90)\n#> # A tibble: 6 × 3\n#>   date       confirmed daily_cases\n#>   <date>         <dbl>       <dbl>\n#> 1 2020-04-15      3699         447\n#> 2 2020-04-16      4427         728\n#> 3 2020-04-17      5050         623\n#> 4 2020-04-18      5992         942\n#> 5 2020-04-19      6588         596\n#> 6 2020-04-20      8014        1426\n```\n:::\n\n\n## `if` asks exactly one question\n\nR's `if` is a control-flow statement. It looks at a single TRUE or FALSE and picks which block of code to run. It is the right tool when you are deciding something about your analysis as a whole.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworst <- max(covid$daily_cases)\nworst\n#> [1] 1426\n\nif (worst > 1000) {\n  \"Singapore recorded a four-figure day.\"\n} else {\n  \"No day reached a thousand.\"\n}\n#> [1] \"Singapore recorded a four-figure day.\"\n```\n:::\n\n\n`worst` is one number. `worst > 1000` is one TRUE. `if` is happy.\n\nNow the mistake. Suppose you want a label on every row, and you write the thing that reads like English:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (covid$daily_cases > 300) \"High\" else \"Not high\"\n#> Error in `if (covid$daily_cases > 300) ...`:\n#> ! the condition has length > 1\n```\n:::\n\n\n`covid$daily_cases > 300` is not one TRUE. It is 345 of them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(covid$daily_cases > 300)\n#> [1] 345\n```\n:::\n\n\n`if` has no way to act on 345 answers at once, so it refuses. The message to search for is **the condition has length > 1**.\n\nThis error is newer than you might expect. Up to R 4.1, that same code ran: R warned you, silently took the first element, and carried on. A script could label the entire dataset \"Not high\" because 22 January happened to have zero cases, and the only sign of trouble was a warning most people scroll past. R 4.2 promoted it to an error. If you find an old script or a Stack Overflow answer that relies on the old behaviour, that is why it no longer works, and the change was an improvement.\n\nWhen you do want a whole-dataset question, collapse the vector to one value first. `any()` and `all()` are built for this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (any(covid$daily_cases > 1000)) {\n  \"At least one day topped a thousand.\"\n}\n#> [1] \"At least one day topped a thousand.\"\n```\n:::\n\n\n## `if_else()` builds a column\n\nFor a label on every row you want a *vectorised* choice: one input vector in, one output vector out, same length. dplyr's `if_else()` does that.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(big_day = if_else(daily_cases > 300, \"High\", \"Not high\")) %>%\n  count(big_day)\n#> # A tibble: 2 × 2\n#>   big_day      n\n#>   <chr>    <int>\n#> 1 High        77\n#> 2 Not high   268\n```\n:::\n\n\nRead the arguments as a sentence: for each row, test `daily_cases > 300`; where it is TRUE use `\"High\"`, where it is FALSE use `\"Not high\"`.\n\n`if_else()` is fussy about types, and the fussiness is deliberate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(big_day = if_else(daily_cases > 300, \"High\", 0))\n#> Error in `mutate()` at magrittr/R/pipe.R:136:3:\n#> ℹ In argument: `big_day = if_else(daily_cases > 300, \"High\", 0)`.\n#> Caused by error in `if_else()`:\n#> ! Can't combine `true` <character> and `false` <double>.\n```\n:::\n\n\n**Can't combine `true` <character> and `false` <double>** means you asked for a column that would be text on some rows and a number on others. R will not guess which one you meant. Base R's `ifelse()` will guess, and its guesses are how people lose data. Watch what happens to a date column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbig <- covid %>%\n  filter(daily_cases > 300) %>%\n  slice(1:3)\n\nifelse(big$daily_cases > 300, big$date, as.Date(NA))\n#> [1] 18365 18366 18367\n```\n:::\n\n\nThose five-digit numbers are days since 1 January 1970, which is how R stores a `Date` underneath. `ifelse()` stripped the class and handed back the raw integers. Somebody has spent an evening trying to work out why their outbreak started in 1970.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif_else(big$daily_cases > 300, big$date, as.Date(NA))\n#> [1] \"2020-04-13\" \"2020-04-14\" \"2020-04-15\"\n```\n:::\n\n\nSame question, dates intact. Use `if_else()`.\n\n## `case_when()` when there are more than two answers\n\nTwo labels is one test. Three labels needs two tests, and nesting `if_else()` inside `if_else()` inside `if_else()` produces code nobody can read six months later. `case_when()` replaces the nesting with a list of conditions, each paired with the value to use when it matches.\n\nThe cutoffs the course uses: under 100 new cases is Low, 100 up to and including 300 is Medium, over 300 is High.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- covid %>%\n  mutate(\n    severity = case_when(\n      daily_cases <  100 ~ \"Low\",\n      daily_cases <= 300 ~ \"Medium\",\n      daily_cases >  300 ~ \"High\"\n    )\n  )\n\ncovid %>% count(severity)\n#> # A tibble: 3 × 2\n#>   severity     n\n#>   <chr>    <int>\n#> 1 High        77\n#> 2 Low        215\n#> 3 Medium      53\n```\n:::\n\n\nThe `~` separates the test from the result. R uses that squiggle wherever the two sides of a relationship have to sit in one expression, which is why it also turns up in modelling formulas and in ggplot facet specifications; inside `case_when()` it means \"gives\".\n\n`case_when()` works top to bottom and **first match wins**. Once a row matches a line, later lines never see it. That is what lets the second condition be `daily_cases <= 300` and not `daily_cases >= 100 & daily_cases <= 300`: any row still being tested on line two already failed line one, so it already has at least 100 cases.\n\nWhich also means the order is load-bearing. Swap the first two lines and the arithmetic is identical but the answer is not:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(\n    wrong = case_when(\n      daily_cases <= 300 ~ \"Medium\",\n      daily_cases <  100 ~ \"Low\",\n      daily_cases >  300 ~ \"High\"\n    )\n  ) %>%\n  count(wrong)\n#> # A tibble: 2 × 2\n#>   wrong      n\n#>   <chr>  <int>\n#> 1 High      77\n#> 2 Medium   268\n```\n:::\n\n\nEvery Low day matched \"Medium\" on the way past and never reached its own line. No error, no warning, 215 days mislabelled. When a `case_when()` gives you a category with a suspiciously round zero or a suspiciously large count, read the order before you read anything else.\n\nThe other failure mode is a row that matches nothing at all. Drop the last line and the 77 High days have nowhere to go:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(\n    incomplete = case_when(\n      daily_cases <  100 ~ \"Low\",\n      daily_cases <= 300 ~ \"Medium\"\n    )\n  ) %>%\n  count(incomplete)\n#> # A tibble: 3 × 2\n#>   incomplete     n\n#>   <chr>      <int>\n#> 1 Low          215\n#> 2 Medium        53\n#> 3 <NA>          77\n```\n:::\n\n\n`case_when()` returns `NA` for unmatched rows rather than complaining, so this only shows up if you look. `.default` catches everything that falls through and is worth using whenever your conditions are meant to be exhaustive:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(\n    severity_alt = case_when(\n      daily_cases <  100 ~ \"Low\",\n      daily_cases <= 300 ~ \"Medium\",\n      .default = \"High\"\n    )\n  ) %>%\n  count(severity_alt)\n#> # A tibble: 3 × 2\n#>   severity_alt     n\n#>   <chr>        <int>\n#> 1 High            77\n#> 2 Low            215\n#> 3 Medium          53\n```\n:::\n\n\n## The boundaries are real days\n\n\"100 to 300\" is ambiguous in English and unambiguous in code, which is exactly where specifications go wrong. Is a day with exactly 100 cases Low or Medium? Is 300 Medium or High? Somebody has to decide, and in a real outbreak that somebody is you, at half past five, on the phone.\n\nThis dataset contains days sitting on both ends of the rule.\n\n::: {.callout-important}\n## Predict before you run\n\nTwo days in August: 18 August had exactly 100 new cases, and 6 August had 301. Under the cutoffs written above, write down the label each of them gets before you look. If you are not sure, that is the point of the exercise.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(date %in% as.Date(c(\"2020-08-06\", \"2020-08-18\"))) %>%\n  select(date, confirmed, daily_cases, severity)\n#> # A tibble: 2 × 4\n#>   date       confirmed daily_cases severity\n#>   <date>         <dbl>       <dbl> <chr>   \n#> 1 2020-08-06     54555         301 High    \n#> 2 2020-08-18     55938         100 Medium\n```\n:::\n\n\n18 August is Medium because `daily_cases < 100` is FALSE at exactly 100, so it fell through to the `<= 300` line. 6 August is High because 301 is one case past `<= 300`. Change `<` to `<=` on the first line and 18 August becomes Low. One character, one day, and if that day is the one in the headline you will hear about it.\n\nWrite your thresholds down in prose next to the code, with the inequalities spelled out. \"Fewer than 100\" and \"up to 100\" are different rules and they will disagree on real days.\n\n## Missing values fall straight through\n\nNeither `if_else()` nor `case_when()` treats `NA` as FALSE. `NA > 0` is `NA`, which is neither branch, so the result is `NA`. Deaths in this file are missing for the first 59 days, so they show it plainly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(\n    daily_deaths = deaths - lag(deaths, default = 0),\n    death_day = if_else(daily_deaths > 0, \"yes\", \"no\")\n  ) %>%\n  count(death_day)\n#> # A tibble: 3 × 2\n#>   death_day     n\n#>   <chr>     <int>\n#> 1 no          260\n#> 2 yes          25\n#> 3 <NA>         60\n```\n:::\n\n\nSixty rows came back `NA`: the 59 days before any death total was published, plus the first day that had one, which has no valid predecessor to difference against. `if_else()` gives you a `missing =` argument to label them explicitly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(\n    daily_deaths = deaths - lag(deaths, default = 0),\n    death_day = if_else(daily_deaths > 0, \"yes\", \"no\", missing = \"not reported yet\")\n  ) %>%\n  count(death_day)\n#> # A tibble: 3 × 2\n#>   death_day            n\n#>   <chr>            <int>\n#> 1 no                 260\n#> 2 not reported yet    60\n#> 3 yes                 25\n```\n:::\n\n\nIn `case_when()` you do the same thing with an `is.na()` line placed first, so that missing rows are claimed before any comparison gets a chance to return `NA`. \"No deaths reported\" and \"deaths not reported\" are different findings and a table that merges them is a table that misleads.\n\n## `table()` sorts alphabetically, and that is wrong here\n\n`count()` is the dplyr way. Base R's `table()` is shorter and you will meet it in other people's code, so look at what it does with the labels:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(covid$severity)\n#> \n#>   High    Low Medium \n#>     77    215     53\n```\n:::\n\n\nHigh, Low, Medium. Alphabetical order, and alphabetical order for an ordered variable is meaningless. It puts the worst category first and the middle category last, and every bar chart, every legend and every summary table you build from that column will inherit the nonsense.\n\nR sorts alphabetically because `severity` is currently plain text:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(covid$severity)\n#> [1] \"character\"\n```\n:::\n\n\nText has no order except the dictionary's. Telling R that these three strings are levels of a categorical variable, in a specific order, is what `factor()` is for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- covid %>%\n  mutate(severity = factor(severity, levels = c(\"Low\", \"Medium\", \"High\")))\n\ntable(covid$severity)\n#> \n#>    Low Medium   High \n#>    215     53     77\n```\n:::\n\n\n215 Low, 53 Medium, 77 High. They sum to 345, which is every day of the dataset, so nothing fell through the conditions.\n\nA factor stores small integers plus a lookup table of labels, which is why the ordering sticks:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(covid$severity)\n#> [1] \"Low\"    \"Medium\" \"High\"\nas.integer(head(covid$severity, 5))\n#> [1] 1 1 1 1 1\nhead(covid$severity, 5)\n#> [1] Low Low Low Low Low\n#> Levels: Low Medium High\n```\n:::\n\n\nRows 1 to 5 are stored as `1`, displayed as `Low`, and sorted first because `Low` is level one. ggplot reads exactly the same information, so the same fix that repairs `table()` repairs your axes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_chr <- ggplot(covid, aes(x = as.character(severity))) +\n  geom_bar() +\n  labs(title = \"Stored as text\", x = NULL, y = \"Days\")\n\np_fct <- ggplot(covid, aes(x = severity)) +\n  geom_bar() +\n  labs(title = \"Stored as a factor\", x = NULL, y = \"Days\")\n\np_chr + p_fct\n```\n\n::: {.cell-output-display}\n![The same 345 days, counted twice. Only the ordering differs.](conditionals_files/figure-html/fig-severity-order-1.svg){#fig-severity-order}\n:::\n:::\n\n\nYou will be doing this for the rest of your career. Age bands, Likert scales, disease stages, income quintiles, WHO regions ordered by anything other than the alphabet: every one of them arrives as text and every one of them needs `factor(levels = ...)` before it plots correctly. It is not a beginner's workaround. It is the fix.\n\nOne trap while you are learning it. `factor()` silently converts any value not listed in `levels` to `NA`, including one that differs only in case:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(factor(as.character(covid$severity), levels = c(\"low\", \"Medium\", \"High\")))\n#> [1] <NA> <NA> <NA> <NA> <NA> <NA>\n#> Levels: low Medium High\ntable(factor(as.character(covid$severity), levels = c(\"low\", \"Medium\", \"High\")), useNA = \"ifany\")\n#> \n#>    low Medium   High   <NA> \n#>      0     53     77    215\n```\n:::\n\n\nA lower-case `l` sent 215 days to `NA` without a word of complaint. After you create a factor, run `table(..., useNA = \"ifany\")` or `count()` once and check the total still matches your row count. Two seconds, and it catches this every time.\n\n## The dataset, assembled\n\nPutting the pieces together, here is the whole thing in one block: the file as it ships, sorted by date, with daily counts differenced out of the cumulative columns, a severity factor in sensible order, and a `month` column produced by rounding each date down to the first of its month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read_covid() %>%\n  arrange(date) %>%\n  mutate(\n    daily_cases  = confirmed - lag(confirmed, default = 0),\n    daily_deaths = deaths - lag(deaths, default = 0),\n    severity = case_when(\n      daily_cases <  100 ~ \"Low\",\n      daily_cases <= 300 ~ \"Medium\",\n      daily_cases >  300 ~ \"High\"\n    ),\n    severity = factor(severity, levels = c(\"Low\", \"Medium\", \"High\")),\n    month = floor_date(date, \"month\")\n  )\n\ncovid %>%\n  select(date, daily_cases, daily_deaths, severity, month) %>%\n  slice(85:88)\n#> # A tibble: 4 × 5\n#>   date       daily_cases daily_deaths severity month     \n#>   <date>           <dbl>        <dbl> <fct>    <date>    \n#> 1 2020-04-15         447            0 High     2020-04-01\n#> 2 2020-04-16         728            0 High     2020-04-01\n#> 3 2020-04-17         623            1 High     2020-04-01\n#> 4 2020-04-18         942            0 High     2020-04-01\n```\n:::\n\n\nThat block is exactly what `covid_daily()` runs. The definition sits in `_common.R` in the project root, where you can open it and read it, so `covid <- covid_daily()` rebuilds this table in one line whenever you want it back in a fresh session. Nothing is hidden in there that you have not now built by hand.\n\n## Exercises\n\n::: {#exr-severity}\n## Audit your severity column\n\nDo not trust `severity` because you wrote it. Check it.\n\n1. Confirm the three counts add up to 345 and that no day came back `NA`.\n2. For each label, report the smallest and the largest `daily_cases` it contains.\n3. Look at the numbers from step 2 either side of each cutoff, and say how far you could move the 100 threshold, in either direction, before a single day changed its label.\n\nStep 3 is the one worth thinking about. Write down what it tells you about how much the labelling really depends on the exact number 100.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\n`group_by(severity)` followed by a `summarise()` containing `n()`, `min()` and `max()` answers steps 1 and 2 in one call: `group_by()` splits the rows into one pile per label, and `summarise()` computes one row of answers for each pile. If you would rather stay with verbs you have already used, a `filter()` per label and a `range()` on each gets you the same three pairs of numbers with more typing. For the `NA` check, `count()` shows a missing category if one exists.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-severity)\n\n::: {#exr-move-cutoffs}\n## Move the cutoffs and watch the headline move\n\nThe 100 and 300 thresholds were chosen by whoever wrote the original worksheet, not by nature. Rebuild `severity` with cutoffs at 50 and 500 instead, keeping the same boundary conventions (under 50 is Low, 50 up to and including 500 is Medium, over 500 is High).\n\nReport the three counts under the new rule, and compare them with 215 / 53 / 77. Then write two sentences you would be willing to put in a report under each set of cutoffs, describing how severe 2020 was. Both sentences must be true of the same 345 days.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\nCopy the `case_when()` block, change the two numbers, and give the new column a different name so you can `count()` both and put the results side by side. Do not forget the `factor()` line, or your new column will sort alphabetically again.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-move-cutoffs)\n",
    "supporting": [
      "conditionals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}