{
  "hash": "244262a88d44fb632020f3adcf152418",
  "result": {
    "engine": "knitr",
    "markdown": "# Transforming data {#sec-transform}\n\n\n\nThe file you read in the last chapter has 345 rows and 13 columns, and the number you most want is in none of them. `confirmed` is a running total. It tells you how many cases Singapore had confirmed by the end of each day, cumulatively, since the first one. Nowhere in the file is there a column saying how many cases were confirmed *on* a given day, which is the quantity every epidemic curve, every reproduction number and every situation report is built from.\n\nGetting it takes one line of dplyr. Getting it *right* takes understanding what that line assumes, which is most of this chapter.\n\nStart where the last chapter finished.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read_covid()\ncovid\n#> # A tibble: 345 × 13\n#>    administrative_area_level_1 confirmed deaths date       stringency_index\n#>    <chr>                           <dbl>  <dbl> <date>                <dbl>\n#>  1 Singapore                           0     NA 2020-01-22             19.4\n#>  2 Singapore                           1     NA 2020-01-23             25  \n#>  3 Singapore                           3     NA 2020-01-24             25  \n#>  4 Singapore                           3     NA 2020-01-25             25  \n#>  5 Singapore                           4     NA 2020-01-26             25  \n#>  6 Singapore                           5     NA 2020-01-27             25  \n#>  7 Singapore                           7     NA 2020-01-28             25  \n#>  8 Singapore                           7     NA 2020-01-29             25  \n#>  9 Singapore                          10     NA 2020-01-30             25  \n#> 10 Singapore                          13     NA 2020-01-31             25  \n#> # ℹ 335 more rows\n#> # ℹ 8 more variables: government_response_index <dbl>,\n#> #   containment_health_index <dbl>,\n#> #   retail_and_recreation_percent_change_from_baseline <dbl>,\n#> #   grocery_and_pharmacy_percent_change_from_baseline <dbl>,\n#> #   parks_percent_change_from_baseline <dbl>,\n#> #   transit_stations_percent_change_from_baseline <dbl>, …\n```\n:::\n\n\n## One verb, one job\n\ndplyr is built on a small number of functions with deliberately boring names. Each one takes a data frame as its first argument, does one thing to it, and returns a data frame. They are called verbs because they are things you do to a table.\n\nYou need five of them for almost everything.\n\n### `filter()` keeps rows\n\nSingapore's circuit breaker ran from 7 April to 1 June 2020. To look at only those days:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(covid, date >= \"2020-04-07\", date <= \"2020-06-01\")\n#> # A tibble: 56 × 13\n#>    administrative_area_level_1 confirmed deaths date       stringency_index\n#>    <chr>                           <dbl>  <dbl> <date>                <dbl>\n#>  1 Singapore                        1481      6 2020-04-07             62.0\n#>  2 Singapore                        1623      6 2020-04-08             76.8\n#>  3 Singapore                        1910      6 2020-04-09             76.8\n#>  4 Singapore                        2108      7 2020-04-10             82.4\n#>  5 Singapore                        2299      8 2020-04-11             76.8\n#>  6 Singapore                        2532      8 2020-04-12             76.8\n#>  7 Singapore                        2918      9 2020-04-13             76.8\n#>  8 Singapore                        3252     10 2020-04-14             76.8\n#>  9 Singapore                        3699     10 2020-04-15             76.8\n#> 10 Singapore                        4427     10 2020-04-16             76.8\n#> # ℹ 46 more rows\n#> # ℹ 8 more variables: government_response_index <dbl>,\n#> #   containment_health_index <dbl>,\n#> #   retail_and_recreation_percent_change_from_baseline <dbl>,\n#> #   grocery_and_pharmacy_percent_change_from_baseline <dbl>,\n#> #   parks_percent_change_from_baseline <dbl>,\n#> #   transit_stations_percent_change_from_baseline <dbl>, …\n```\n:::\n\n\nFifty-six rows, which is 7 April to 1 June counted inclusively. Two things are happening in that call that deserve a moment.\n\nThe first is that several conditions separated by commas are combined with **and**. Every condition has to hold for a row to survive. If you want **or**, you have to say so with `|`, because a comma will never mean that.\n\nThe second is that `date` is a proper `Date` column and you compared it to a piece of text. R quietly converted the text to a date for you, which works because `\"2020-04-07\"` is in ISO order: year, month, day. Write the date the way most of the world writes it and R does not complain, it gets a different answer:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.Date(\"07/04/2020\")\n#> [1] \"0007-04-20\"\n```\n:::\n\n\nThe seventh of April, 2020, has become the twentieth of April in the year 7. R read `07` as the year, `04` as the month and `2020` as the day, then rolled the impossible day number forward. No error, no warning, and a `filter()` built on that comparison would return all 345 rows while looking entirely reasonable. Use ISO dates. This is the reason the standard exists.\n\nThere is one more thing about `filter()` that catches everyone exactly once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(covid, date = \"2020-04-07\")\n#> Error in `filter()`:\n#> ! We detected a named input.\n#> ℹ This usually means that you've used `=` instead of `==`.\n#> ℹ Did you mean `date == \"2020-04-07\"`?\n```\n:::\n\n\nOne equals sign is assignment, two is comparison. dplyr recognises the mistake and tells you which one you meant, which is kinder than most of R. Base R would have silently treated it as an argument name.\n\n### `arrange()` reorders rows\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(covid, desc(stringency_index))\n#> # A tibble: 345 × 13\n#>    administrative_area_level_1 confirmed deaths date       stringency_index\n#>    <chr>                           <dbl>  <dbl> <date>                <dbl>\n#>  1 Singapore                        2108      7 2020-04-10             82.4\n#>  2 Singapore                       12693     12 2020-04-25             82.4\n#>  3 Singapore                       17101     16 2020-05-01             82.4\n#>  4 Singapore                        1623      6 2020-04-08             76.8\n#>  5 Singapore                        1910      6 2020-04-09             76.8\n#>  6 Singapore                        2299      8 2020-04-11             76.8\n#>  7 Singapore                        2532      8 2020-04-12             76.8\n#>  8 Singapore                        2918      9 2020-04-13             76.8\n#>  9 Singapore                        3252     10 2020-04-14             76.8\n#> 10 Singapore                        3699     10 2020-04-15             76.8\n#> # ℹ 335 more rows\n#> # ℹ 8 more variables: government_response_index <dbl>,\n#> #   containment_health_index <dbl>,\n#> #   retail_and_recreation_percent_change_from_baseline <dbl>,\n#> #   grocery_and_pharmacy_percent_change_from_baseline <dbl>,\n#> #   parks_percent_change_from_baseline <dbl>,\n#> #   transit_stations_percent_change_from_baseline <dbl>, …\n```\n:::\n\n\nThe Oxford stringency index peaked at 82.41, and three separate days sit at that peak. Sorting does not deduplicate; it puts equal things next to each other and leaves them in the order it found them.\n\n`desc()` looks like clutter until you try the obvious alternative:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(covid, -date)\n#> Error in `arrange()`:\n#> ℹ In argument: `..1 = -date`.\n#> Caused by error in `-.Date`:\n#> ! unary - is not defined for \"Date\" objects\n```\n:::\n\n\n`unary - is not defined for \"Date\" objects`. Negating a number to reverse the sort works for numbers, and dates are stored as numbers underneath, but R refuses to let you do arithmetic that would produce a nonsense date. `desc()` works on anything that can be sorted, including text and factors, so use it and stop thinking about it.\n\n### `select()` keeps columns\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(covid, date, confirmed, deaths, stringency_index)\n#> # A tibble: 345 × 4\n#>    date       confirmed deaths stringency_index\n#>    <date>         <dbl>  <dbl>            <dbl>\n#>  1 2020-01-22         0     NA             19.4\n#>  2 2020-01-23         1     NA             25  \n#>  3 2020-01-24         3     NA             25  \n#>  4 2020-01-25         3     NA             25  \n#>  5 2020-01-26         4     NA             25  \n#>  6 2020-01-27         5     NA             25  \n#>  7 2020-01-28         7     NA             25  \n#>  8 2020-01-29         7     NA             25  \n#>  9 2020-01-30        10     NA             25  \n#> 10 2020-01-31        13     NA             25  \n#> # ℹ 335 more rows\n```\n:::\n\n\nThe order you name them is the order you get, so `select()` doubles as a way to move a column to the front. There are helpers for the cases where naming every column is not sensible:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(covid, date, ends_with(\"_percent_change_from_baseline\"))\n#> # A tibble: 345 × 7\n#>    date       retail_and_recreation_percent_change_from…¹ grocery_and_pharmacy…²\n#>    <date>                                           <dbl>                  <dbl>\n#>  1 2020-01-22                                          NA                     NA\n#>  2 2020-01-23                                          NA                     NA\n#>  3 2020-01-24                                          NA                     NA\n#>  4 2020-01-25                                          NA                     NA\n#>  5 2020-01-26                                          NA                     NA\n#>  6 2020-01-27                                          NA                     NA\n#>  7 2020-01-28                                          NA                     NA\n#>  8 2020-01-29                                          NA                     NA\n#>  9 2020-01-30                                          NA                     NA\n#> 10 2020-01-31                                          NA                     NA\n#> # ℹ 335 more rows\n#> # ℹ abbreviated names: ¹​retail_and_recreation_percent_change_from_baseline,\n#> #   ²​grocery_and_pharmacy_percent_change_from_baseline\n#> # ℹ 4 more variables: parks_percent_change_from_baseline <dbl>,\n#> #   transit_stations_percent_change_from_baseline <dbl>,\n#> #   workplaces_percent_change_from_baseline <dbl>,\n#> #   residential_percent_change_from_baseline <dbl>\n```\n:::\n\n\n`starts_with()`, `ends_with()` and `contains()` all work inside `select()` and nowhere else, which is confusing the first time. They are part of a small language called tidyselect that only makes sense in the context of choosing columns. A leading minus drops instead of keeps:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(covid, -administrative_area_level_1)\n#> # A tibble: 345 × 12\n#>    confirmed deaths date       stringency_index government_response_index\n#>        <dbl>  <dbl> <date>                <dbl>                     <dbl>\n#>  1         0     NA 2020-01-22             19.4                      19.3\n#>  2         1     NA 2020-01-23             25                        24.5\n#>  3         3     NA 2020-01-24             25                        24.5\n#>  4         3     NA 2020-01-25             25                        24.5\n#>  5         4     NA 2020-01-26             25                        24.5\n#>  6         5     NA 2020-01-27             25                        24.5\n#>  7         7     NA 2020-01-28             25                        24.5\n#>  8         7     NA 2020-01-29             25                        24.5\n#>  9        10     NA 2020-01-30             25                        24.5\n#> 10        13     NA 2020-01-31             25                        24.5\n#> # ℹ 335 more rows\n#> # ℹ 7 more variables: containment_health_index <dbl>,\n#> #   retail_and_recreation_percent_change_from_baseline <dbl>,\n#> #   grocery_and_pharmacy_percent_change_from_baseline <dbl>,\n#> #   parks_percent_change_from_baseline <dbl>,\n#> #   transit_stations_percent_change_from_baseline <dbl>,\n#> #   workplaces_percent_change_from_baseline <dbl>, …\n```\n:::\n\n\nThat column is the string `\"Singapore\"` in all 345 rows. It is there because the data hub serves many countries from one schema, and it carries no information at all once you have filtered down to one of them.\n\n### `rename()` changes column names\n\n`retail_and_recreation_percent_change_from_baseline` is fifty characters long, and you will type it more times in an afternoon's work than you would like. Google named it, not you, and the name is descriptive rather than convenient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmob <- rename(\n  covid,\n  retail      = retail_and_recreation_percent_change_from_baseline,\n  grocery     = grocery_and_pharmacy_percent_change_from_baseline,\n  parks       = parks_percent_change_from_baseline,\n  transit     = transit_stations_percent_change_from_baseline,\n  workplaces  = workplaces_percent_change_from_baseline,\n  residential = residential_percent_change_from_baseline\n)\n\nselect(mob, date, retail, workplaces, residential)\n#> # A tibble: 345 × 4\n#>    date       retail workplaces residential\n#>    <date>      <dbl>      <dbl>       <dbl>\n#>  1 2020-01-22     NA         NA          NA\n#>  2 2020-01-23     NA         NA          NA\n#>  3 2020-01-24     NA         NA          NA\n#>  4 2020-01-25     NA         NA          NA\n#>  5 2020-01-26     NA         NA          NA\n#>  6 2020-01-27     NA         NA          NA\n#>  7 2020-01-28     NA         NA          NA\n#>  8 2020-01-29     NA         NA          NA\n#>  9 2020-01-30     NA         NA          NA\n#> 10 2020-01-31     NA         NA          NA\n#> # ℹ 335 more rows\n```\n:::\n\n\nNew name on the left, old name on the right, which is the opposite of the order most people guess. The way to remember it is that `rename()` behaves like `mutate()` and every other function that makes columns: the thing being created is always on the left of the `=`.\n\nThe code in this book keeps the long names, because that is what the file ships with and because a chapter that renames things in secret is a chapter you cannot copy code out of. In your own analysis, rename early and rename once.\n\n### `mutate()` makes new columns\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(\n  mutate(covid, cfr = deaths / confirmed * 100),\n  date, confirmed, deaths, cfr\n)\n#> # A tibble: 345 × 4\n#>    date       confirmed deaths   cfr\n#>    <date>         <dbl>  <dbl> <dbl>\n#>  1 2020-01-22         0     NA    NA\n#>  2 2020-01-23         1     NA    NA\n#>  3 2020-01-24         3     NA    NA\n#>  4 2020-01-25         3     NA    NA\n#>  5 2020-01-26         4     NA    NA\n#>  6 2020-01-27         5     NA    NA\n#>  7 2020-01-28         7     NA    NA\n#>  8 2020-01-29         7     NA    NA\n#>  9 2020-01-30        10     NA    NA\n#> 10 2020-01-31        13     NA    NA\n#> # ℹ 335 more rows\n```\n:::\n\n\n`mutate()` works on whole columns at a time. There is no loop over rows; `deaths / confirmed` divides two vectors of 345 numbers element by element and hands back a third. This is the single biggest habit shift coming from a spreadsheet, and once it clicks, most of R gets easier.\n\nThe case fatality ratio at the end of 2020 was 29 in 58,599, or about 0.05%. That is a very low number by any international comparison of that year, and the reason is demographic before it is clinical: the great majority of Singapore's 2020 cases came from the migrant-worker dormitory outbreak that dominated April to August, in a population of working-age adults. The ratio does not mean much until you say that.\n\n## Stringing verbs together\n\nLook at what that last call became. To make a column and then choose four columns, the code reads inside out: `mutate()` is buried in the middle, `select()` wraps around it, and the data frame you started from is somewhere in the interior. Add a `filter()` and an `arrange()` and it becomes unreadable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(\n  arrange(\n    select(\n      filter(covid, date >= \"2020-04-07\", date <= \"2020-06-01\"),\n      date, confirmed, stringency_index\n    ),\n    desc(stringency_index)\n  ),\n  4\n)\n#> # A tibble: 4 × 3\n#>   date       confirmed stringency_index\n#>   <date>         <dbl>            <dbl>\n#> 1 2020-04-10      2108             82.4\n#> 2 2020-04-25     12693             82.4\n#> 3 2020-05-01     17101             82.4\n#> 4 2020-04-08      1623             76.8\n```\n:::\n\n\nYou have to read that from the innermost bracket outwards, which is backwards from the order the operations happen and backwards from how you thought about the problem. The pipe fixes it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(date >= \"2020-04-07\", date <= \"2020-06-01\") %>%\n  select(date, confirmed, stringency_index) %>%\n  arrange(desc(stringency_index)) %>%\n  head(4)\n#> # A tibble: 4 × 3\n#>   date       confirmed stringency_index\n#>   <date>         <dbl>            <dbl>\n#> 1 2020-04-10      2108             82.4\n#> 2 2020-04-25     12693             82.4\n#> 3 2020-05-01     17101             82.4\n#> 4 2020-04-08      1623             76.8\n```\n:::\n\n\n`x %>% f(y)` means `f(x, y)`. The thing on the left is passed in as the first argument of the function on the right. Because every dplyr verb takes a data frame first and returns a data frame, they chain without any glue.\n\nRead `%>%` as \"and then\". Take covid, and then keep the circuit-breaker days, and then keep three columns, and then sort by stringency, and then show me four rows. That is the order the sentence happens in and the order the code is written in.\n\nSome habits worth forming now. Put the `%>%` at the end of the line, never at the start of the next one, because R needs to see that the line is unfinished. Indent the continuation lines. Build the chain one verb at a time, running it after each addition, rather than writing eight lines and then trying to work out which one broke. RStudio has a keyboard shortcut for the pipe: Ctrl+Shift+M on Windows and Linux, Cmd+Shift+M on a Mac.\n\n::: {.callout-note}\n## The other pipe\n\nR gained a pipe of its own in version 4.1, written `|>`. It does the same basic thing and needs no packages. It differs in the details: `%>%` lets you write `.` to put the incoming value somewhere other than the first argument, while `|>` has a narrower placeholder with different rules, and the two behave differently with anonymous functions. This book uses `%>%` throughout, so if you see `|>` in code you find elsewhere, it is the same idea and not a typo.\n:::\n\n## Cumulative counts are not incidence\n\nHere is the epidemiology that the rest of the chapter exists to support.\n\n`confirmed` only ever goes up. It went up when Singapore was recording three cases a day in February, it went up when Singapore recorded 1,426 in a single day in April, and it went up in December when the epidemic was essentially over. A cumulative curve cannot fall, so it can never show you a peak or a turn. What it shows is the total damage so far, which is a real quantity and almost never the one you want.\n\nIncidence is the number of new cases per unit time. It is what an epidemic *is*: a rate, going up and coming down. It is what you fit a model to and what you compute a reproduction number from, and it is the only one of the two that can tell you whether last week was better than the week before.\n\nBoth curves below are made from the same 345 numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_inc <- covid %>%\n  arrange(date) %>%\n  mutate(daily_cases = confirmed - lag(confirmed, default = 0))\n\np_cum <- ggplot(covid_inc, aes(date, confirmed)) +\n  geom_line() +\n  scale_y_continuous(labels = label_comma()) +\n  labs(title = \"Cumulative confirmed cases\", x = NULL, y = NULL)\n\np_inc <- ggplot(covid_inc, aes(date, daily_cases)) +\n  geom_col(width = 1) +\n  scale_y_continuous(labels = label_comma()) +\n  labs(title = \"New cases each day\", x = NULL, y = NULL)\n\np_cum / p_inc\n```\n\n::: {.cell-output-display}\n![The same epidemic, twice. Above, the cumulative confirmed count. Below, new cases per day, derived from it.](transform_files/figure-html/fig-cumulative-vs-incident-1.svg){#fig-cumulative-vs-incident fig-alt='Two stacked time series for 2020. The upper panel is a smooth S-shaped curve rising from zero to about 58,600 and then flattening. The lower panel is a jagged bar chart peaking above 1,400 in late April, falling through the middle of the year, with a second smaller rise from late July into August and one tall isolated spike.'}\n:::\n:::\n\n\nThe top panel is the shape every dashboard showed in 2020, and for judging anything it is close to useless. It rises steeply through the middle of the year and flattens at the right-hand edge, and that is all it can ever do. The peak is invisible in it. So is the fact that half the year's cases had been confirmed by 20 May.\n\nThe bottom panel shows an epidemic. It climbs through April to a single highest day of 1,426 on 20 April, stays high through May, then falls unevenly until the week of 5 July, before a second rise carries it back up through late July into early August and it dies away from mid-August onwards. The tall isolated spike is 5 August, which recorded 908 cases against an August median of 91 and a next-highest August day of 313. Singapore's Ministry of Health attributed that day to clearance testing in the dormitories detecting past infections. Whatever you make of the explanation, a cumulative curve would never have prompted the question.\n\nThere is a rhetorical consequence worth being alert to. A cumulative curve flatters every intervention, because after any intervention it keeps rising and can always be described as \"flattening\". An incidence curve makes the claim falsifiable: either the number came down or it did not.\n\n## `lag()`, and the precondition nobody states\n\nThe line that did the work was this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_cases = confirmed - lag(confirmed, default = 0)\n```\n:::\n\n\n`lag()` shifts a vector one position to the right, so that each element lines up with the one before it. On a short example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0, 1, 3, 3, 4)\nlag(x)\n#> [1] NA  0  1  3  3\nx - lag(x)\n#> [1] NA  1  2  0  1\n```\n:::\n\n\nElement two of `lag(x)` is element one of `x`. Subtracting gives the difference between consecutive elements: the increments. The first element has nothing before it, so `lag()` puts `NA` there, and the subtraction propagates it.\n\nNow the part that matters. **`lag()` is positional, not date-aware.** It has no idea that your data has a `date` column. It takes the row physically above, whatever that row happens to be. If your rows are in some other order, `lag()` will not warn you, will not error, and will happily compute differences between days that are months apart.\n\nSuppose you had sorted by stringency index earlier in your session, for a perfectly good reason, and then computed daily cases without re-sorting.\n\n::: {.callout-important}\n## Predict before you run\n\nOf the 345 daily case counts produced from wrongly ordered rows, how many will come out negative? Commit to a number before you scroll.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscrambled <- covid %>%\n  arrange(desc(stringency_index)) %>%\n  mutate(daily_cases = confirmed - lag(confirmed, default = 0))\n\nsum(scrambled$daily_cases < 0)\n#> [1] 8\nmedian(scrambled$daily_cases)\n#> [1] 42\n```\n:::\n\n\nEight. Eight rows out of 345 are negative, and the median of the wrong answer is 42 against a true value of 40. Sort the table by anything other than date and roughly 97% of the resulting daily counts still look like plausible daily counts. Some of them are even right, by accident, wherever two adjacent rows happened to be adjacent days.\n\nThis is what makes the mistake dangerous. A bug that produces obvious garbage gets caught in the first thirty seconds. A bug that produces 337 plausible numbers and 8 impossible ones gets caught when a reviewer asks about a negative value in a figure, three months later.\n\nSo: put `arrange(date)` in the chain, immediately before the `mutate()`, every time. It costs one line. It does nothing at all when the data was already sorted, which this file is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- covid %>%\n  arrange(date) %>%\n  mutate(daily_cases = confirmed - lag(confirmed, default = 0))\n\ncovid %>% select(date, confirmed, daily_cases)\n#> # A tibble: 345 × 3\n#>    date       confirmed daily_cases\n#>    <date>         <dbl>       <dbl>\n#>  1 2020-01-22         0           0\n#>  2 2020-01-23         1           1\n#>  3 2020-01-24         3           2\n#>  4 2020-01-25         3           0\n#>  5 2020-01-26         4           1\n#>  6 2020-01-27         5           1\n#>  7 2020-01-28         7           2\n#>  8 2020-01-29         7           0\n#>  9 2020-01-30        10           3\n#> 10 2020-01-31        13           3\n#> # ℹ 335 more rows\n```\n:::\n\n\n## What belongs in the first row\n\n`lag()` on its own leaves `NA` at the top, because there is no previous row to subtract. The `default = 0` argument fills that gap with a zero instead. Whether that is right is a question about your data, not a question about R, and it is the kind of decision that gets made by accident far more often than it gets made on purpose.\n\nHere it is right, and you can see why in the first row of the table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>% select(date, confirmed, daily_cases) %>% head(3)\n#> # A tibble: 3 × 3\n#>   date       confirmed daily_cases\n#>   <date>         <dbl>       <dbl>\n#> 1 2020-01-22         0           0\n#> 2 2020-01-23         1           1\n#> 3 2020-01-24         3           2\n```\n:::\n\n\n`confirmed` is 0 on 22 January 2020. Zero cases had been confirmed by the end of that day, so zero cases were confirmed *during* it. That is a real observation, not a gap. Recording it as `NA` would throw away a genuine zero and quietly shorten the series by one day in every count, sum and plot downstream.\n\nThe picture changes completely if the series does not start at zero. Suppose your extract began on 1 March, when the cumulative total was already 106. Then `default = 0` would compute 106 new cases on 1 March, which is not what happened; those 106 accumulated over the preceding weeks. On that series the honest answer is `NA`, because you have no information about how many cases occurred on the first day of a window you did not observe the start of.\n\nTwo conventions, two different datasets, and no default to memorise. Look at the first value. If it is zero, `default = 0` records a true zero. If it is not, plain `lag()` and an `NA` tells the truth about what you do not know. This file starts at zero, which is the only reason `default = 0` belongs in the code above, and it is the sort of reason worth writing in a comment beside it.\n\n## Two checks worth running every time\n\nDerived columns are where quiet errors live, because nothing about them looks different from data that came out of a file. Two cheap checks catch most of what can go wrong with a difference of a cumulative series.\n\nThe first is that a difference of a non-decreasing count cannot be negative. If a negative appears, either the rows are out of order or the source revised its figures downward.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>% filter(daily_cases < 0)\n#> # A tibble: 0 × 14\n#> # ℹ 14 variables: administrative_area_level_1 <chr>, confirmed <dbl>,\n#> #   deaths <dbl>, date <date>, stringency_index <dbl>,\n#> #   government_response_index <dbl>, containment_health_index <dbl>,\n#> #   retail_and_recreation_percent_change_from_baseline <dbl>,\n#> #   grocery_and_pharmacy_percent_change_from_baseline <dbl>,\n#> #   parks_percent_change_from_baseline <dbl>,\n#> #   transit_stations_percent_change_from_baseline <dbl>, …\n```\n:::\n\n\nZero rows. What comes back is an empty tibble rather than nothing at all, and the empty tibble still knows its column names and types, which is how you can tell the check ran instead of failing silently.\n\nThe second is that the daily numbers must add back up to the cumulative total. The increments telescope: every intermediate value cancels, leaving the last one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(covid$daily_cases) == max(covid$confirmed)\n#> [1] TRUE\nsum(covid$daily_cases)\n#> [1] 58599\n```\n:::\n\n\n58,599 either way. Run the same check on the scrambled version and it fails, because the \"last\" row in stringency order is 22 January, where the cumulative total is 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(scrambled$daily_cases) == max(scrambled$confirmed)\n#> [1] FALSE\n```\n:::\n\n\nA test that fails when the code is wrong and passes when it is right is worth the two lines it takes to write. Keep both of these near the top of any script that differences a cumulative series.\n\nOne warning about applying the same recipe to `deaths`. That column is missing for the first 59 days of 2020, and the second check will not reconcile on it: you get 27 deaths back out of a cumulative total that ends at 29. The reason is the `lag()` you have just met. Singapore's first two deaths are both recorded on 21 March, which is also the first day the column carries a number at all, so the difference on that row is `2 - NA`, which is `NA`, and a sum told to skip missing values skips those two deaths along with them. Differencing recovers changes; it cannot recover the level a series started at. That is a property of the file rather than a mistake you made, and what to do about it is a decision about what a blank in that column means rather than a change to the code.\n\n## Exercises\n\n::: {#exr-verbs}\n## Build a circuit-breaker table\n\nUsing only `filter()`, `select()`, `rename()`, `arrange()` and the pipe, produce a table covering the circuit breaker (7 April to 1 June 2020 inclusive) that contains the date, the cumulative confirmed count, the stringency index, and the retail and workplace mobility columns under short names of your choosing. Sort it so that the deepest workplace mobility drops appear first.\n\nThen answer two things from the result. How many rows does it have, and does that match the number of calendar days in the period? And what do the top three rows have in common as dates, once you look them up?\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\n`rename()` and `select()` can both give a column a new name, so you can do it in one step or two. For the second question, count the days from 7 April to 1 June by hand and remember that both endpoints are included.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-verbs)\n\n::: {#exr-daily-cases}\n## Difference the deaths series\n\nApply the same pattern you used for cases to the `deaths` column: sort by date, then make a `daily_deaths` column by subtracting the lagged cumulative count.\n\nThen run both of the checks from this chapter on it. Are there any negative values? Does the total of the daily numbers equal the final cumulative figure? Report exactly what you get from each check, including anything R does with missing values along the way.\n\nFinally, find the largest single-day increase in deaths and the date it happened. Leave the shortfall unrepaired. What the exercise wants is the row it went astray on, named exactly.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\n`sum()` on a vector containing `NA` returns `NA`, so you will need to decide what to tell it to do about that, and the decision is part of the answer. Look at the rows around the first date on which `deaths` is not missing.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-daily-cases)\n",
    "supporting": [
      "transform_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}