{
  "hash": "3381b75195686003927d575c57952925",
  "result": {
    "engine": "knitr",
    "markdown": "# Worked solutions {#sec-solutions}\n\n\n\n\n\n\n\nEvery exercise in the book has an answer here, and every answer on this page was executed to produce the output you see. If a number in a solution disagrees with a number you got, one of us has a bug, and finding out which is more useful than either of us being right.\n\nRead the exercise first and have a go. A solution you have already attempted teaches you something; a solution you read cold teaches you that R exists.\n\nTwo objects are set up once at the top of this page and used throughout. `covid` is `covid_daily()`, the state the book reaches at the end of @sec-conditionals, with `daily_cases`, `daily_deaths`, `severity` and `month` already built. `covid_raw` is `read_covid()`, the file exactly as it ships, which a few of the early solutions need because the exercises are about what the raw file looks like. Chapters up to and including @sec-conditionals build those columns in front of you, so if you are working through the book in order and your object is called something else, that is fine.\n\n## Build a week by hand {#sec-sol-vectors}\n\n> From the chapter on objects, vectors and functions: store the first seven cumulative counts, difference them, break the vector with a string, and see what one `NA` does to a mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweek_one <- c(0, 1, 3, 3, 4, 5, 7)\n\nlength(week_one)\n#> [1] 7\ntypeof(week_one)\n#> [1] \"double\"\n```\n:::\n\n\nSeven elements, and the type is `double` rather than `integer` even though every value is a whole number. `c(0, 1, 3)` writes doubles unless you ask for integers with `0L, 1L, 3L`. This catches people out when they compare `typeof()` output against what they expected, and it almost never matters in practice.\n\nPart two. Two vectors of the same length subtract element by element, so you need days two to seven in one and days one to six in the other:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweek_one[2:7] - week_one[1:6]\n#> [1] 1 2 0 1 1 2\n```\n:::\n\n\nOne, two, zero, one, one, two. Day four had no new cases at all. This is the same arithmetic that `lag()` does across all 345 rows in @sec-transform, written out small enough to see.\n\nWhat this does *not* give you is a number for day one. There is no day zero to subtract, so six differences come out of seven values. In the full dataset the book handles that with `lag(confirmed, default = 0)`, which is defensible here because `confirmed[1]` really is 0.\n\nPart three. Add a label to the front:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabelled <- c(\"week one\", week_one)\n\ntypeof(labelled)\n#> [1] \"character\"\nlabelled\n#> [1] \"week one\" \"0\"        \"1\"        \"3\"        \"3\"        \"4\"        \"5\"       \n#> [8] \"7\"\n```\n:::\n\n\nEvery number became text. A vector holds one type, and when `c()` is handed a mixture it picks the type that can represent all of it. Character wins over double because any number can be written as a string, whereas `\"week one\"` cannot be written as a number. That is coercion, and it is silent by design.\n\nThe arithmetic now fails:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabelled * 2\n#> Error in `labelled * 2`:\n#> ! non-numeric argument to binary operator\n```\n:::\n\n\n`non-numeric argument to binary operator` is the error you will meet most often in your first month of R, and nine times out of ten the cause is exactly this: a stray label, a footnote marker, or a `\"N/A\"` typed by hand into a spreadsheet column, coercing an entire column of numbers to text on import.\n\nPart four:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweek_na <- week_one\nweek_na[4] <- NA\n\nmean(week_na)\n#> [1] NA\nmean(week_na, na.rm = TRUE)\n#> [1] 3.333333\n```\n:::\n\n\n`NA` in, `NA` out. R will not guess what the missing value was, so any arithmetic that touches it is undefined and R says so. `na.rm = TRUE` drops it and averages the remaining six, giving 3.33.\n\n**What people get wrong.** They reach for `na.rm = TRUE` as a reflex, because it makes the `NA` go away and the code stops complaining. It also silently changes the denominator: the second mean is over six days, not seven, and nothing in the output says so. @sec-missing is about the cases where that matters, and Singapore's mobility columns are one of them.\n\n## Take a tibble apart {#sec-sol-tibble-anatomy}\n\n> From the chapter on rectangles: show with code that a tibble is a list, get the type of every column, build a small tibble of policy dates, and find a behaviour that a plain data frame does differently.\n\nPart one. Three functions do the whole job:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.list(covid_raw)\n#> [1] TRUE\nlength(covid_raw)\n#> [1] 13\nunique(lengths(covid_raw))\n#> [1] 345\n```\n:::\n\n\n`length()` counts the elements of the underlying list, which is 13 columns. `lengths()`, with the s, measures each element, and `unique()` collapsing to a single value of 345 is the proof that every column has the same length. 345 is the number of rows, 13 the number of columns. Row *i* of every column refers to the same day, and that guarantee is what makes `filter()` safe.\n\nPart two:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(covid_raw, class)\n#>                        administrative_area_level_1 \n#>                                        \"character\" \n#>                                          confirmed \n#>                                          \"numeric\" \n#>                                             deaths \n#>                                          \"numeric\" \n#>                                               date \n#>                                             \"Date\" \n#>                                   stringency_index \n#>                                          \"numeric\" \n#>                          government_response_index \n#>                                          \"numeric\" \n#>                           containment_health_index \n#>                                          \"numeric\" \n#> retail_and_recreation_percent_change_from_baseline \n#>                                          \"numeric\" \n#>  grocery_and_pharmacy_percent_change_from_baseline \n#>                                          \"numeric\" \n#>                 parks_percent_change_from_baseline \n#>                                          \"numeric\" \n#>      transit_stations_percent_change_from_baseline \n#>                                          \"numeric\" \n#>            workplaces_percent_change_from_baseline \n#>                                          \"numeric\" \n#>           residential_percent_change_from_baseline \n#>                                          \"numeric\"\n```\n:::\n\n\n`sapply()` applies `class()` to each column and collects the answers into a named character vector. If you want the storage type rather than the class, `sapply(covid_raw, typeof)` gives `double` where this gives `numeric`, and `double` where this gives `Date`, because a `Date` is a double with an attribute attached.\n\nPart three:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy <- tibble(\n  date  = as.Date(c(\"2020-04-07\", \"2020-06-02\", \"2020-06-19\")),\n  phase = c(\"Circuit breaker begins\", \"Phase 1 reopening\", \"Phase 2 reopening\")\n)\n\npolicy\n#> # A tibble: 3 × 2\n#>   date       phase                 \n#>   <date>     <chr>                 \n#> 1 2020-04-07 Circuit breaker begins\n#> 2 2020-06-02 Phase 1 reopening     \n#> 3 2020-06-19 Phase 2 reopening\n```\n:::\n\n\nWhy a tibble rather than two vectors: sorting or filtering a tibble moves whole rows, so a date can never lose its label. With two loose vectors, `sort(phase)` reorders one and leaves the other alone, and nothing errors. The second reason is that the correspondence is now written down. Anyone reading `policy` can see that 2 June is Phase 1; with two vectors that fact lives only in the head of whoever typed them.\n\nPart four. Convert to an old-style data frame and the difference shows up straight away:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid_df <- as.data.frame(covid_raw)\n\nhead(covid_df$conf, 5)\n#> [1] 0 1 3 3 4\n```\n:::\n\n\nPartial matching. `covid_df$conf` is not a column, and the data frame helpfully decided you meant `confirmed`. The tibble refuses:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(covid_raw$conf, 5)\n#> Warning: Unknown or uninitialised column: `conf`.\n#> NULL\n```\n:::\n\n\n`NULL`, plus a warning naming the column you asked for. That is the behaviour you want, because partial matching turns a typo into a plausible answer. If a data frame has both `confirmed` and `confirmed_smoothed`, `$conf` is ambiguous and returns `NULL` anyway, so the convenience is unreliable as well as dangerous.\n\nThe other classic difference is single-bracket subsetting:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(covid_df[, \"confirmed\"])\n#> [1] \"numeric\"\nclass(covid_raw[, \"confirmed\"])\n#> [1] \"tbl_df\"     \"tbl\"        \"data.frame\"\n```\n:::\n\n\nThe data frame drops to a bare vector when you ask for one column. The tibble stays a tibble. Code written as `df[, cols]` and then piped into something expecting a rectangle works or breaks depending on how many columns `cols` happened to contain that day, which is the kind of bug that only shows up on the run where a filter left you with one column.\n\n## Land the file yourself {#sec-sol-first-look}\n\n> From the chapter on reading the epidemic in: read the CSV yourself with `read_csv()`, state the types explicitly, count the missing values, then read it with `read.csv()` and find what breaks.\n\nPart one. In a fresh session you would need `library(tidyverse)` and `library(here)` first; this page already has them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- read_csv(here(\"data\", \"sg_covid_data.csv\"))\n#> Rows: 345 Columns: 13\n#> ── Column specification ────────────────────────────────────────────────────────\n#> Delimiter: \",\"\n#> chr   (1): administrative_area_level_1\n#> dbl  (11): confirmed, deaths, stringency_index, government_response_index, c...\n#> date  (1): date\n#> \n#> ℹ Use `spec()` to retrieve the full column specification for this data.\n#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n\nThe specification message is the answer. `date (1): date` means readr recognised the ISO-8601 strings and parsed the column to `Date`. `dbl (11)` covers `confirmed`, `deaths`, the three policy indices and the six mobility columns. `chr (1): administrative_area_level_1` is the country name, which is `\"Singapore\"` on all 345 rows and would have been the first thing to check if it were not.\n\nReading that message is a habit worth forming now. It is the only moment R tells you what it decided about your file, and by the time a column of counts has silently become character, you are three chunks downstream wondering why `mean()` failed.\n\nPart two. `cols()` names the columns you care about and `.default` mops up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntyped <- read_csv(\n  here(\"data\", \"sg_covid_data.csv\"),\n  col_types = cols(\n    date                        = col_date(),\n    confirmed                   = col_double(),\n    administrative_area_level_1 = col_character(),\n    .default                    = col_double()\n  )\n)\n\ndim(typed)\n#> [1] 345  13\n```\n:::\n\n\nNo message this time. readr only reports a specification it guessed, and you did not ask it to guess. Writing the spec out is what you do when a file is going into a pipeline that runs weekly, because it turns \"the column changed type when they added a row\" from a silent surprise into a loud parsing failure.\n\nPart three:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(raw)\n#> Rows: 345\n#> Columns: 13\n#> $ administrative_area_level_1                        <chr> \"Singapore\", \"Singa…\n#> $ confirmed                                          <dbl> 0, 1, 3, 3, 4, 5, 7…\n#> $ deaths                                             <dbl> NA, NA, NA, NA, NA,…\n#> $ date                                               <date> 2020-01-22, 2020-0…\n#> $ stringency_index                                   <dbl> 19.44, 25.00, 25.00…\n#> $ government_response_index                          <dbl> 19.27, 24.48, 24.48…\n#> $ containment_health_index                           <dbl> 22.02, 27.98, 27.98…\n#> $ retail_and_recreation_percent_change_from_baseline <dbl> NA, NA, NA, NA, NA,…\n#> $ grocery_and_pharmacy_percent_change_from_baseline  <dbl> NA, NA, NA, NA, NA,…\n#> $ parks_percent_change_from_baseline                 <dbl> NA, NA, NA, NA, NA,…\n#> $ transit_stations_percent_change_from_baseline      <dbl> NA, NA, NA, NA, NA,…\n#> $ workplaces_percent_change_from_baseline            <dbl> NA, NA, NA, NA, NA,…\n#> $ residential_percent_change_from_baseline           <dbl> NA, NA, NA, NA, NA,…\n```\n:::\n\n\nSeven columns start with `NA`: `deaths` and the six mobility columns. Count them properly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw %>%\n  summarise(across(everything(), ~ sum(is.na(.x)))) %>%\n  pivot_longer(everything(), names_to = \"column\", values_to = \"n_missing\") %>%\n  filter(n_missing > 0)\n#> # A tibble: 7 × 2\n#>   column                                             n_missing\n#>   <chr>                                                  <int>\n#> 1 deaths                                                    59\n#> 2 retail_and_recreation_percent_change_from_baseline        24\n#> 3 grocery_and_pharmacy_percent_change_from_baseline         24\n#> 4 parks_percent_change_from_baseline                        24\n#> 5 transit_stations_percent_change_from_baseline             24\n#> 6 workplaces_percent_change_from_baseline                   24\n#> 7 residential_percent_change_from_baseline                  24\n```\n:::\n\n\nThey do not all have the same number. The six mobility columns have 24 apiece and `deaths` has 59, and the two gaps have nothing to do with each other. The mobility gap runs from 22 January to 14 February because Google's baseline period, the median by weekday over 3 January to 6 February 2020, had not finished. The `deaths` gap runs to 20 March because Singapore had not recorded a COVID-19 death yet, and the source file encodes \"none yet\" as missing rather than as zero. Two different reasons, two different repairs, and @sec-missing takes them apart.\n\nIf `across()` and `pivot_longer()` are new, `colSums(is.na(raw))` gets you the same numbers in one line of base R.\n\nPart four:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_df <- read.csv(here(\"data\", \"sg_covid_data.csv\"))\n\nclass(base_df$date)\n#> [1] \"character\"\nhead(base_df$date, 3)\n#> [1] \"2020-01-22\" \"2020-01-23\" \"2020-01-24\"\n```\n:::\n\n\nCharacter. `read.csv()` has no date parser, so the dates arrive as strings that look right and behave like text. Anything date-shaped then fails:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_df$date[2] - base_df$date[1]\n#> Error in `base_df$date[2] - base_df$date[1]`:\n#> ! non-numeric argument to binary operator\n```\n:::\n\n\nWhereas the readr version answers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw$date[2] - raw$date[1]\n#> Time difference of 1 days\n```\n:::\n\n\n**What people get wrong.** Sorting. `sort()` on character dates in ISO-8601 format gives the right answer by accident, because `\"2020-04-07\"` sorts after `\"2020-04-06\"` alphabetically as well as chronologically. Hand it dates written `07/04/2020` and the sort is silently wrong. If your dates are text, `arrange(date)` will look like it worked.\n\n## Build a circuit-breaker table {#sec-sol-verbs}\n\n> From the chapter on transforming data: use `filter()`, `select()`, `rename()` and `arrange()` to pull the circuit-breaker period into a small table sorted by the deepest workplace mobility drops.\n\n`select()` renames as it selects, so this is one call rather than two:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncb <- covid %>%\n  filter(date >= as.Date(\"2020-04-07\"), date <= as.Date(\"2020-06-01\")) %>%\n  select(\n    date,\n    confirmed,\n    stringency = stringency_index,\n    retail     = retail_and_recreation_percent_change_from_baseline,\n    workplaces = workplaces_percent_change_from_baseline\n  ) %>%\n  arrange(workplaces)\n\ncb\n#> # A tibble: 56 × 5\n#>    date       confirmed stringency retail workplaces\n#>    <date>         <dbl>      <dbl>  <dbl>      <dbl>\n#>  1 2020-04-10      2108       82.4    -63        -83\n#>  2 2020-05-01     17101       82.4    -68        -83\n#>  3 2020-05-07     20939       76.8    -66        -83\n#>  4 2020-05-25     31960       73.2    -62        -82\n#>  5 2020-04-23     11178       76.8    -68        -69\n#>  6 2020-04-29     15641       76.8    -67        -69\n#>  7 2020-04-30     16169       76.8    -67        -69\n#>  8 2020-04-22     10141       76.8    -66        -68\n#>  9 2020-04-27     14423       76.8    -67        -68\n#> 10 2020-04-28     14951       76.8    -66        -68\n#> # ℹ 46 more rows\n```\n:::\n\n\nTwo `filter()` conditions separated by a comma are combined with AND, which is what you want for a date range. Writing `filter(date >= start & date <= end)` is identical; the comma is the house style because it reads as a list of requirements.\n\n`arrange(workplaces)` sorts ascending, and mobility drops are negative, so ascending puts the deepest drops first. If you wanted the same thing for a series where bigger means worse, you would need `arrange(desc(...))`. Getting this backwards is worth checking every time, because a sorted table always looks convincing.\n\nHow many rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(cb)\n#> [1] 56\n\nas.integer(as.Date(\"2020-06-01\") - as.Date(\"2020-04-07\")) + 1\n#> [1] 56\n```\n:::\n\n\nFifty-six both ways. Twenty-four days of April, thirty-one of May, and the first of June. The `+ 1` is there because subtracting two dates counts the gaps between them, not the days, and forgetting it is how a period ends up one day short in a report. The agreement between the two numbers is the check: if `nrow()` had come back 55, you would have a missing day in the file rather than an off-by-one in your head.\n\nThe top three rows are 10 April, 1 May and 7 May, all at 83% below baseline. They are Good Friday, Labour Day and Vesak Day. The three deepest workplace-mobility days inside Singapore's strictest eight weeks of 2020 are public holidays, and the same holds across the whole year: the eight deepest workplace days in 2020 are all public holidays.\n\n**What people get wrong.** Reading a mobility trough as a policy effect. Before you write a sentence about any dip in these series, check the date against a calendar. @sec-functions comes back to this with the full list of eight.\n\n## Difference the deaths series {#sec-sol-daily-cases}\n\n> Also from the chapter on transforming data: apply the cases recipe to `deaths`, run both checks on the result, and find the largest single-day rise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths_daily <- covid_raw %>%\n  arrange(date) %>%\n  mutate(daily_deaths = deaths - lag(deaths, default = 0))\n\ndeaths_daily %>%\n  select(date, deaths, daily_deaths) %>%\n  slice(58:63)\n#> # A tibble: 6 × 3\n#>   date       deaths daily_deaths\n#>   <date>      <dbl>        <dbl>\n#> 1 2020-03-19     NA           NA\n#> 2 2020-03-20     NA           NA\n#> 3 2020-03-21      2           NA\n#> 4 2020-03-22      2            0\n#> 5 2020-03-23      2            0\n#> 6 2020-03-24      2            0\n```\n:::\n\n\nThe first check, for negative values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(deaths_daily$daily_deaths < 0)\n#> [1] NA\n```\n:::\n\n\n`NA`, not `FALSE`. This is the part of the exercise worth slowing down for. `NA < 0` is `NA`, because R has no idea whether the missing value was negative. `any()` then has a vector containing `NA`s and `FALSE`s and no `TRUE` at all, and the honest answer to \"is at least one of these true?\" when some of them are unknown is \"I cannot tell\". So it returns `NA`.\n\nTell it to ignore the unknowns and you get the answer you wanted:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(deaths_daily$daily_deaths < 0, na.rm = TRUE)\n#> [1] FALSE\n```\n:::\n\n\nNo negative daily deaths. The cumulative series never goes backwards.\n\nThe second check, that the daily figures add back to the cumulative total:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(deaths_daily$daily_deaths)\n#> [1] NA\n\nsum(deaths_daily$daily_deaths, na.rm = TRUE)\n#> [1] 27\n\nmax(deaths_daily$deaths, na.rm = TRUE)\n#> [1] 29\n```\n:::\n\n\nThe plain `sum()` is `NA` for the same reason. With `na.rm = TRUE` you get 27, and the cumulative column ends at 29. The check fails, and it is supposed to.\n\nHere is where the two went. `deaths` is missing for the first 59 rows and the first recorded value, on 21 March 2020, is already 2. So the difference on 21 March is `2 - NA`, which is `NA`, and those two deaths never enter the sum:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths_daily %>%\n  filter(!is.na(deaths)) %>%\n  slice_head(n = 3) %>%\n  select(date, deaths, daily_deaths)\n#> # A tibble: 3 × 3\n#>   date       deaths daily_deaths\n#>   <date>      <dbl>        <dbl>\n#> 1 2020-03-21      2           NA\n#> 2 2020-03-22      2            0\n#> 3 2020-03-23      2            0\n```\n:::\n\n\nDifferencing recovers changes. It cannot recover a level. A series that starts part-way up loses everything below the step, and no amount of `na.rm = TRUE` puts it back. @sec-missing shows the repair, which is a decision about what the leading `NA`s mean rather than a piece of code.\n\nThe largest single-day rise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeaths_daily %>%\n  slice_max(daily_deaths, n = 1) %>%\n  select(date, deaths, daily_deaths)\n#> # A tibble: 2 × 3\n#>   date       deaths daily_deaths\n#>   <date>      <dbl>        <dbl>\n#> 1 2020-04-27     14            2\n#> 2 2020-05-06     20            2\n```\n:::\n\n\nTwo days tie at two deaths, so `slice_max(n = 1)` returns both. `with_ties = FALSE` would give you one arbitrarily, which is fine when you want a single row and wrong when the tie is the finding. In a year with 29 deaths, the fact that no day recorded more than two is worth a sentence on its own.\n\n## Interrogate the mobility gap {#sec-sol-mobility-na}\n\n> From the chapter on missing values: check whether the six mobility columns are missing on the same days, take a monthly mean that has almost no data behind it, and count days two ways.\n\nPart one. `which(is.na(x))` gives row numbers rather than a count, and row numbers can be compared:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmobility <- covid %>% select(ends_with(\"percent_change_from_baseline\"))\n\nna_rows <- lapply(mobility, function(x) which(is.na(x)))\n\nlengths(na_rows)\n#> retail_and_recreation_percent_change_from_baseline \n#>                                                 24 \n#>  grocery_and_pharmacy_percent_change_from_baseline \n#>                                                 24 \n#>                 parks_percent_change_from_baseline \n#>                                                 24 \n#>      transit_stations_percent_change_from_baseline \n#>                                                 24 \n#>            workplaces_percent_change_from_baseline \n#>                                                 24 \n#>           residential_percent_change_from_baseline \n#>                                                 24\n\nall(sapply(na_rows, identical, na_rows[[1]]))\n#> [1] TRUE\n```\n:::\n\n\nThe same 24 rows in all six columns, not merely 24 in each. `identical()` is doing real work there: it compares length, type and every element, so two different sets of 24 rows would come back `FALSE`.\n\nWhich days:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(covid$date[na_rows[[1]]])\n#> [1] \"2020-01-22\" \"2020-02-14\"\n```\n:::\n\n\n22 January to 14 February 2020, one unbroken block at the start of the file. All six series are absent for the same reason: Google's baseline is the median for each day of the week over 3 January to 6 February 2020, and until that window closed there was nothing to compute a percentage change against. One cause, one shape of gap, which is why the six columns move together.\n\nPart two:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeb <- covid %>% filter(month == as.Date(\"2020-02-01\"))\n\nnrow(feb)\n#> [1] 29\n\nmean(feb$parks_percent_change_from_baseline, na.rm = TRUE)\n#> [1] -7.533333\n\nsum(!is.na(feb$parks_percent_change_from_baseline))\n#> [1] 15\n```\n:::\n\n\nThe number is −7.53. It is the mean of 15 days out of 29, and all 15 fall in the second half of the month:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(feb$date[!is.na(feb$parks_percent_change_from_baseline)])\n#> [1] \"2020-02-15\" \"2020-02-29\"\n```\n:::\n\n\nCalling that \"February's average parks mobility\" would tell a reader that Singaporeans spent 7.5% less time in parks across February 2020, when what the number describes is 15 February to 29 February. The first half of the month is not averaged low. It is not averaged at all, and half of February is missing from a number labelled February.\n\nJanuary is the harsher version. Retail mobility is 100% missing that month, and `mean()` with `na.rm = TRUE` returns `NaN` rather than a number, because you have asked it to average nothing. `NaN` at least stops you. A mean over 15 of 29 days does not.\n\nPart three. The prediction: the gap should be 24, because the missing rows are the same 24 rows for every mobility column, and the two tools treat them differently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(covid[covid$parks_percent_change_from_baseline < -40, ])\n#> [1] 101\n\ncovid %>%\n  filter(parks_percent_change_from_baseline < -40) %>%\n  nrow()\n#> [1] 77\n```\n:::\n\n\n101 against 77, a gap of exactly 24. `covid$parks... < -40` is a logical vector containing `TRUE`, `FALSE` and 24 `NA`s. The single-bracket subscript keeps every row that is not `FALSE`, so each `NA` becomes a row of nothing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbracket <- covid[covid$parks_percent_change_from_baseline < -40, ]\n\nsum(is.na(bracket$date))\n#> [1] 24\n```\n:::\n\n\nTwenty-four rows in that result have no date and no case count. `filter()` drops `NA` rows because a row that might match is not a row that does, and for the question \"on how many days did parks mobility fall below −40\" the honest answer is 77, with a footnote saying 24 days cannot be assessed.\n\n**What people get wrong.** Reporting the 101. It is a bigger number, it comes out of code that ran without complaint, and nothing on screen says a quarter of those rows are phantoms. The same arithmetic applies to every mobility column in this file, and the gap is always 24.\n\n## Audit your severity column {#sec-sol-severity}\n\n> From the chapter on making decisions: check the three severity counts, find the range of `daily_cases` inside each label, and work out how far the 100 cutoff could move before anything changed.\n\nSteps one and two in one call. `group_by()` and `summarise()` are the subject of @sec-groups, so treat this as a preview:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  group_by(severity) %>%\n  summarise(\n    days    = n(),\n    lowest  = min(daily_cases),\n    highest = max(daily_cases)\n  )\n#> # A tibble: 3 × 4\n#>   severity  days lowest highest\n#>   <fct>    <int>  <dbl>   <dbl>\n#> 1 Low        215      0      94\n#> 2 Medium      53    100     295\n#> 3 High        77    301    1426\n```\n:::\n\n\n215, 53 and 77 add to 345, which is every row in the file. `count()` is the other route and it has one advantage here: it shows an `NA` category if one exists.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>% count(severity)\n#> # A tibble: 3 × 2\n#>   severity     n\n#>   <fct>    <int>\n#> 1 Low        215\n#> 2 Medium      53\n#> 3 High        77\n```\n:::\n\n\nThree rows, no fourth row labelled `NA`. If a day had come back missing, this is where it would show, and the cause would be a gap in `case_when()`'s conditions rather than a gap in the data. `case_when()` returns `NA` when nothing matches, silently, so this check is the one that catches a cutoff you forgot to cover.\n\nStep three is the one worth thinking about. The largest Low day is 94 and the smallest Medium day is 100. Nothing in 2020 landed in between:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(daily_cases >= 90, daily_cases <= 110) %>%\n  count(daily_cases, severity)\n#> # A tibble: 6 × 3\n#>   daily_cases severity     n\n#>         <dbl> <fct>    <int>\n#> 1          91 Low          1\n#> 2          93 Low          1\n#> 3          94 Low          1\n#> 4         100 Medium       1\n#> 5         102 Medium       1\n#> 6         106 Medium       1\n```\n:::\n\n\nSo the cutoff could sit anywhere from 95 to 100 and every one of the 345 days would keep the label it has. Move it to 101 and 18 August, which recorded exactly 100 cases, becomes Low. Move it to 94 and the same day is unaffected but the 94-case day changes. Prove it rather than trusting the argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelabel <- function(lower) {\n  s <- case_when(\n    covid$daily_cases <  lower ~ \"Low\",\n    covid$daily_cases <= 300   ~ \"Medium\",\n    covid$daily_cases >  300   ~ \"High\"\n  )\n  factor(s, levels = c(\"Low\", \"Medium\", \"High\"))\n}\n\nas_written <- relabel(100)\n\nsapply(90:105, function(t) identical(relabel(t), as_written))\n#>  [1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE\n#> [13] FALSE FALSE FALSE FALSE\n```\n:::\n\n\n`TRUE` from 95 through 100 and `FALSE` either side. The upper cutoff behaves the same way: the largest Medium day is 295 and the smallest High day is 301, so 295 through 300 are interchangeable.\n\nWhat that tells you is that the exact number 100 is not carrying the classification. Any cutoff from 95 to 100 produces the identical table, and the same is true of 295 to 300 at the top, so nobody can argue that your headline depends on a round number picked by a worksheet author. What they *can* argue is what happens at 50, or at 500, and that is the next exercise.\n\n## Move the cutoffs and watch the headline move {#sec-sol-move-cutoffs}\n\n> Also from the chapter on making decisions: rebuild `severity` with cutoffs at 50 and 500, compare the counts with 215 / 53 / 77, and write a defensible sentence under each rule.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecut <- covid %>%\n  mutate(\n    severity_wide = case_when(\n      daily_cases <  50  ~ \"Low\",\n      daily_cases <= 500 ~ \"Medium\",\n      daily_cases >  500 ~ \"High\"\n    ),\n    severity_wide = factor(severity_wide, levels = c(\"Low\", \"Medium\", \"High\"))\n  )\n\nrecut %>% count(severity_wide)\n#> # A tibble: 3 × 2\n#>   severity_wide     n\n#>   <fct>         <int>\n#> 1 Low             189\n#> 2 Medium          114\n#> 3 High             42\n```\n:::\n\n\n189 Low, 114 Medium, 42 High, against 215 / 53 / 77 under the original rule. Put them side by side to see where the days went:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecut %>% count(severity, severity_wide)\n#> # A tibble: 5 × 3\n#>   severity severity_wide     n\n#>   <fct>    <fct>         <int>\n#> 1 Low      Low             189\n#> 2 Low      Medium           26\n#> 3 Medium   Medium           53\n#> 4 High     Medium           35\n#> 5 High     High             42\n```\n:::\n\n\nTwenty-six days that were Low are now Medium, and 35 days that were High are now Medium. Nothing crossed two boundaries. The wider Medium band swallowed the edges of both neighbours, and the count of High days fell by nearly half.\n\nThe `factor()` line matters. Leave it out and `count()` sorts High, Low, Medium alphabetically, which looks like a bug in your analysis and is not.\n\nTwo sentences, both true of the same 345 days:\n\n> Under the original thresholds, 77 of Singapore's 345 reported days in 2020, 22%, exceeded 300 new cases, and 62% stayed below 100.\n\n> Under thresholds of 50 and 500, only 42 days in 2020, 12%, exceeded 500 new cases, and a further 114 sat in a broad middle band.\n\nNeither is false. The first invites the reader to conclude that a fifth of Singapore's 2020 was a bad day. The second invites them to conclude that high-burden days were rare. A reader who sees only one of the two takes away a different impression of the same year.\n\nA threshold is an argument, and the place for an argument is your methods section, next to a reason. \"300 was chosen because it is roughly the daily capacity of the contact-tracing system\" is a cutoff you can defend. \"300 was on the worksheet\" is not, and until somebody asks you, nobody will know which one you had.\n\n## High-severity days by month {#sec-sol-monthly-high}\n\n> From the chapter on grouping and summarising: one row per month, counting High, Medium and Low days plus the days of data in the month.\n\nThree `sum()` calls inside one `summarise()` put the columns in the order you choose, which `count()` plus `pivot_wider()` does not:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_severity <- covid %>%\n  group_by(month) %>%\n  summarise(\n    days   = n(),\n    low    = sum(severity == \"Low\"),\n    medium = sum(severity == \"Medium\"),\n    high   = sum(severity == \"High\"),\n    cases  = sum(daily_cases)\n  )\n\nmonthly_severity\n#> # A tibble: 12 × 6\n#>    month       days   low medium  high cases\n#>    <date>     <int> <int>  <int> <int> <dbl>\n#>  1 2020-01-01    10    10      0     0    13\n#>  2 2020-02-01    29    29      0     0    89\n#>  3 2020-03-01    31    31      0     0   824\n#>  4 2020-04-01    30     5      7    18 15243\n#>  5 2020-05-01    31     0      0    31 18715\n#>  6 2020-06-01    30     0     18    12  9023\n#>  7 2020-07-01    31     0     19    12  8298\n#>  8 2020-08-01    31    18      9     4  4607\n#>  9 2020-09-01    30    30      0     0   953\n#> 10 2020-10-01    31    31      0     0   250\n#> 11 2020-11-01    30    30      0     0   203\n#> 12 2020-12-01    31    31      0     0   381\n```\n:::\n\n\n`sum(severity == \"High\")` works because `==` gives a logical vector and `sum()` treats `TRUE` as 1. It is the standard idiom for \"count the rows where this holds\" and it composes inside `summarise()` in a way that `nrow(filter(...))` does not.\n\nCheck the row that will trip you up before anything else. January has 10 days, not 31, because the file starts on 22 January. Every other month is complete. That is why `days` is in the table: without it, January's 13 cases read as a whole quiet month rather than as the last ten days of one.\n\nThe two questions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_severity %>% slice_max(high, n = 2)\n#> # A tibble: 2 × 6\n#>   month       days   low medium  high cases\n#>   <date>     <int> <int>  <int> <int> <dbl>\n#> 1 2020-05-01    31     0      0    31 18715\n#> 2 2020-04-01    30     5      7    18 15243\n\nmonthly_severity %>% slice_max(cases, n = 2)\n#> # A tibble: 2 × 6\n#>   month       days   low medium  high cases\n#>   <date>     <int> <int>  <int> <int> <dbl>\n#> 1 2020-05-01    31     0      0    31 18715\n#> 2 2020-04-01    30     5      7    18 15243\n```\n:::\n\n\nMay wins both. Every one of its 31 days was above 300 cases, and it carried 18,715 of the year's 58,599.\n\nThey can come apart, and August is the near-miss that shows how. August has 4 High days and 4,607 cases, more than September through December combined, while March has 0 High days and 824. A count of days above a threshold is insensitive to how far above the threshold those days sat, so a month of steady 320s and a month carrying one 908 can produce very different High counts for similar totals. Report both, or report the one whose question you are answering.\n\n## A monthly alert table you can defend {#sec-sol-monthly-alert}\n\n> Also from the chapter on grouping and summarising: three statuses instead of two, then the same table under a rate-based rule, and which of the two you would defend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalerts <- covid %>%\n  group_by(month) %>%\n  summarise(\n    days       = n(),\n    high_days  = sum(severity == \"High\"),\n    mean_daily = round(mean(daily_cases), 1)\n  ) %>%\n  mutate(\n    status_days = case_when(\n      high_days >  5 ~ \"Alert\",\n      high_days >= 1 ~ \"Watch\",\n      TRUE           ~ \"All clear\"\n    )\n  )\n\nalerts\n#> # A tibble: 12 × 5\n#>    month       days high_days mean_daily status_days\n#>    <date>     <int>     <int>      <dbl> <chr>      \n#>  1 2020-01-01    10         0        1.3 All clear  \n#>  2 2020-02-01    29         0        3.1 All clear  \n#>  3 2020-03-01    31         0       26.6 All clear  \n#>  4 2020-04-01    30        18      508.  Alert      \n#>  5 2020-05-01    31        31      604.  Alert      \n#>  6 2020-06-01    30        12      301.  Alert      \n#>  7 2020-07-01    31        12      268.  Alert      \n#>  8 2020-08-01    31         4      149.  Watch      \n#>  9 2020-09-01    30         0       31.8 All clear  \n#> 10 2020-10-01    31         0        8.1 All clear  \n#> 11 2020-11-01    30         0        6.8 All clear  \n#> 12 2020-12-01    31         0       12.3 All clear\n```\n:::\n\n\nThe ordering carries the logic. `case_when()` takes the first condition that matches, so `high_days > 5` has to come before `high_days >= 1`; a month with 18 High days satisfies both, and if the `>= 1` line came first, April would be labelled \"Watch\". The final `TRUE ~ \"All clear\"` is the catch-all, and without it the months with zero High days would come back `NA` rather than falling through to a sensible default.\n\nNow the rate-based rule. I have picked 100 mean daily cases, and stating the number out loud is half the exercise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalerts <- alerts %>%\n  mutate(status_rate = if_else(mean_daily > 100, \"Alert\", \"All clear\"))\n\nalerts %>%\n  filter(status_days != status_rate) %>%\n  select(month, days, high_days, mean_daily, status_days, status_rate)\n#> # A tibble: 1 × 6\n#>   month       days high_days mean_daily status_days status_rate\n#>   <date>     <int>     <int>      <dbl> <chr>       <chr>      \n#> 1 2020-08-01    31         4       149. Watch       Alert\n```\n:::\n\n\nOne month changes: August, \"Watch\" under the day-count rule and \"Alert\" under the rate rule. August had 4 High days and a mean of 148.6, and the mean is being pulled up by 5 August, which recorded 908 cases against a monthly median of 91. Recompute August's mean without that single day and it falls to 123.3, still above 100 but by much less.\n\nWhich rule I would rather defend: the day-count rule, and not because it is kinder to August. A count of days above a threshold cannot be moved by one extreme value, and 5 August is an extreme value with a known cause. MOH attributed the day's numbers to clearance testing in the dormitories picking up past infections, 903 of the 908 were dormitory residents, and 581 were linked to a single cluster at Acacia Lodge. A rule that escalates a whole month on the strength of one day of retrospective testing is a rule that will escalate again the next time a backlog clears.\n\nThe honest version of the answer is that I would report both columns and let the meeting see the disagreement, because the disagreement is the finding. A single status column hides the fact that August was one thing by one measure and another thing by another.\n\n## Cross-check a month that is not September {#sec-sol-september}\n\n> Also from the chapter on grouping and summarising: compute a month's mean daily cases two ways, then try the same trick on January and fix what breaks.\n\nOctober, the differenced way:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noctober <- covid %>% filter(month == as.Date(\"2020-10-01\"))\n\nnrow(october)\n#> [1] 31\nmean(october$daily_cases)\n#> [1] 8.064516\n```\n:::\n\n\nNow the telescoping route, which never touches `daily_cases` at all. Every day's increment cancels against the next one, so the total for October is the cumulative count on 31 October minus the cumulative count on 30 September:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nend_october   <- covid %>% filter(date == as.Date(\"2020-10-31\")) %>% pull(confirmed)\nend_september <- covid %>% filter(date == as.Date(\"2020-09-30\")) %>% pull(confirmed)\n\n(end_october - end_september) / nrow(october)\n#> [1] 8.064516\n```\n:::\n\n\n8.06 both ways. Two routes that share no intermediate column, which is what makes the agreement evidence rather than a tautology. Comparing `mean()` against a loop that performs the same division proves only that R can divide.\n\nWrap it up so January can break it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_mean_telescoped <- function(df, which_month) {\n  m    <- as.Date(which_month)\n  this <- df %>% filter(month == m)\n  prev <- df %>% filter(month == m - months(1))\n\n  end_this <- this %>% slice_max(date, n = 1) %>% pull(confirmed)\n  end_prev <- prev %>% slice_max(date, n = 1) %>% pull(confirmed)\n\n  (end_this - end_prev) / nrow(this)\n}\n\nmonth_mean_telescoped(covid, \"2020-10-01\")\n#> [1] 8.064516\n```\n:::\n\n\nJanuary:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_mean_telescoped(covid, \"2020-01-01\")\n#> numeric(0)\n```\n:::\n\n\n`numeric(0)`. Not an error, not `NA`, an empty vector. There is no December 2019 in this file, so `prev` has zero rows, `pull(confirmed)` returns a length-zero vector, and arithmetic between a length-1 vector and a length-0 vector gives length 0. R does exactly what it was asked and the answer has nothing in it.\n\nThat is worse than an error, because `numeric(0)` will travel. Put it in a `mutate()` and you get a length mismatch three steps later. Print it in a report and you get a blank cell nobody notices.\n\nThe fix uses a fact about this specific file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid$confirmed[1]\n#> [1] 0\ncovid$date[1]\n#> [1] \"2020-01-22\"\n```\n:::\n\n\n`confirmed` is 0 on the first day of the record. There is nothing before the file to subtract, because the cumulative count starts at zero:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_mean_telescoped <- function(df, which_month) {\n  m    <- as.Date(which_month)\n  this <- df %>% filter(month == m)\n  prev <- df %>% filter(month == m - months(1))\n\n  end_this <- this %>% slice_max(date, n = 1) %>% pull(confirmed)\n  end_prev <- prev %>% slice_max(date, n = 1) %>% pull(confirmed)\n\n  if (length(end_prev) == 0) end_prev <- 0\n\n  (end_this - end_prev) / nrow(this)\n}\n\nmonth_mean_telescoped(covid, \"2020-01-01\")\n#> [1] 1.3\n\njanuary <- covid %>% filter(month == as.Date(\"2020-01-01\"))\nmean(january$daily_cases)\n#> [1] 1.3\n```\n:::\n\n\n1.3 both ways.\n\nTwo assumptions are buried in that `if`. The first is that a cumulative series starting at 0 means no cases occurred before the record begins, which happens to be true here and is false for any dataset that starts mid-epidemic. The second is that January's denominator is 10, the days present in the file, not 31, the days in the month. Both are defensible for this file and both are things you must write down, because the function will happily return a number for a file where neither holds.\n\n## Draw a publication-ready epidemic curve {#sec-sol-epi-curve}\n\n> From the chapter on plots: a single figure of daily cases across 2020 that stands on its own, with the circuit breaker marked, saved as a 300 dpi PNG about 3.5 inches wide.\n\nBuild it as an object so it can be printed and saved without being drawn twice:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncb_start <- as.Date(\"2020-04-07\")\ncb_end   <- as.Date(\"2020-06-01\")\n\np_epi <- ggplot(covid, aes(x = date, y = daily_cases)) +\n  annotate(\n    \"rect\",\n    xmin = cb_start, xmax = cb_end, ymin = -Inf, ymax = Inf,\n    fill = nus_colours[[\"muted\"]], alpha = 0.25\n  ) +\n  geom_col(fill = nus_colours[[\"blue\"]], width = 1) +\n  scale_x_date(date_breaks = \"2 months\", date_labels = \"%b\") +\n  scale_y_continuous(labels = label_comma()) +\n  labs(\n    title    = \"Singapore's reported cases peaked on 20 April 2020\",\n    subtitle = \"Shaded band: circuit breaker, 7 April to 1 June\",\n    x = NULL,\n    y = \"New cases per day\",\n    caption  = \"Counts differenced from the cumulative confirmed series.\\nSource: COVID-19 Data Hub.\"\n  )\n\np_epi\n```\n\n::: {.cell-output-display}\n![The figure as drawn at the book's default width of 7 inches.](solutions_files/figure-html/sol-epi-1-1.svg)\n:::\n:::\n\n\nThree decisions in there are worth naming. `annotate(\"rect\", ...)` with `ymin = -Inf` and `ymax = Inf` shades the full height of the panel whatever the y range turns out to be, so the band does not need adjusting when the data changes. It comes before `geom_col()` so the bars sit on top of it rather than under it; layers are drawn in the order you add them. And `date_breaks = \"2 months\"` is a deliberate choice about collision: monthly ticks fit at 7 inches and do not fit at 3.5.\n\nNow save it at the size it will actually be printed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout <- tempfile(fileext = \".png\")\n\nggsave(out, plot = p_epi, width = 3.5, height = 2.6, dpi = 300)\n\nfile.exists(out)\n#> [1] TRUE\n```\n:::\n\n\nIn your own script that path would be `\"figures/epi-curve-2020.png\"` rather than a temporary file, and the directory has to exist first; `ggsave()` will not create it for you.\n\nThen the part the exercise actually asks about. Open that PNG. ggplot2 measures text in points rather than as a fraction of the canvas, so halving the width does not halve the type. `theme_nus()` has a base size of 12 and puts the title at 1.15 times that, which is a bold 13.8-point line that fits comfortably across 7 inches and runs off the edge of 3.5. The six month labels collide for the same reason. The fix is to give the small version its own text and its own axis, rather than drawing the big one and shrinking it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_small <- p_epi +\n  labs(\n    title    = \"Cases peaked on 20 April 2020\",\n    subtitle = \"Shaded: circuit breaker\",\n    caption  = \"Differenced from cumulative counts.\"\n  ) +\n  scale_x_date(date_breaks = \"3 months\", date_labels = \"%b\") +\n  theme(\n    plot.title    = element_text(size = 10),\n    plot.subtitle = element_text(size = 8),\n    plot.caption  = element_text(size = 6.5),\n    axis.title    = element_text(size = 8),\n    axis.text     = element_text(size = 7)\n  )\n#> Scale for x is already present.\n#> Adding another scale for x, which will replace the existing scale.\n\np_small\n```\n\n::: {.cell-output-display}\n![The same figure with type sized for a single journal column.](solutions_files/figure-html/sol-epi-3-1.svg)\n:::\n\n```{.r .cell-code}\n\nggsave(tempfile(fileext = \".png\"), plot = p_small,\n       width = 3.5, height = 2.6, dpi = 300)\n```\n:::\n\n\nShorter title, shorter caption, and four month ticks instead of six. The message about a scale being replaced is ggplot2 telling you that the second `scale_x_date()` overwrote the first, which is what was intended here and is something to look at hard when it is not.\n\n**What people get wrong.** Drawing the figure at 7 inches, saving it at 7 inches, and letting the journal or the slide deck shrink it afterwards. That shrink *does* scale the type, because it is scaling the finished image, and 13.8-point text at half size is 7-point text nobody can read. Size the figure for its final home.\n\n## Make the distribution legible, and say what it cost {#sec-sol-histogram}\n\n> Also from the chapter on plots: fix the histogram of `daily_cases`, state exactly which days your fix removed, then facet it by month in calendar order.\n\nThe raw version first, so there is something to compare against:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(covid, aes(x = daily_cases)) +\n  geom_histogram()\n#> `stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n::: {.cell-output-display}\n![The default. Over half the year lands in the leftmost bar.](solutions_files/figure-html/sol-hist-1-1.svg)\n:::\n:::\n\n\nThe message about `bins = 30` is ggplot2 telling you it guessed, and the guess is the wrong tool for a distribution this skewed. Thirty bins across a range of 0 to 1,426 is a bin width of 47.5, and 183 of the 345 days fall in the first one. The leftmost bar swallows the year and the rest of the panel is white space.\n\nHere is a version with a bin width you chose and a restricted view:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(covid, aes(x = daily_cases)) +\n  geom_histogram(binwidth = 20) +\n  xlim(0, 400) +\n  labs(\n    x = \"New cases per day\",\n    y = \"Days\",\n    title = \"Most of 2020 was quiet, and the tail is long\",\n    caption = \"55 days above 400 cases are not shown.\"\n  )\n#> Warning: Removed 55 rows containing non-finite outside the scale range\n#> (`stat_bin()`).\n#> Warning: Removed 2 rows containing missing values or values outside the scale range\n#> (`geom_bar()`).\n```\n\n::: {.cell-output-display}\n![Twenty-case bins, x axis cut at 400.](solutions_files/figure-html/sol-hist-2-1.svg)\n:::\n:::\n\n\nRead the warning, because it writes your caption for you. `Removed 55 rows containing non-finite outside the scale range` is the exact count: `xlim()` does not crop the picture, it drops the rows before the bins are computed, so those 55 days are not in this figure at all. They are the 55 days above 400 cases, which between them carry 36,379 of the year's 58,599 cases. A figure that omits 62% of the epidemic needs to say so, and the caption above does. The second warning, about 2 rows removed by `geom_bar()`, is the two bins that straddle the edge of the new limits.\n\n`coord_cartesian(xlim = c(0, 400))` is the alternative and behaves differently: it zooms the finished plot instead of filtering the data, so the bins are computed over all 345 days, nothing is removed, and you cannot see past 400. No warning appears, which is convenient and is also why I prefer `xlim()` here. The warning is a receipt.\n\nNow the faceted version. The factor is what puts the panels in calendar order:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  mutate(month_name = factor(format(date, \"%B\"), levels = month.name)) %>%\n  ggplot(aes(x = daily_cases)) +\n  geom_histogram(binwidth = 50) +\n  facet_wrap(~ month_name) +\n  labs(\n    x = \"New cases per day\",\n    y = \"Days\",\n    title = \"Twelve distributions, not one\"\n  )\n```\n\n::: {.cell-output-display}\n![The same distribution, cut by month, panels in calendar order.](solutions_files/figure-html/sol-hist-3-1.svg)\n:::\n:::\n\n\n`month.name` is a base R constant holding the twelve month names in order. Without the `factor()` call the panels come out April, August, December, February, and the plot looks broken for a reason that has nothing to do with plotting.\n\nWhich one goes in the report: the faceted one, if the question is about how the year changed. The single histogram answers \"what did a typical day in 2020 look like\", and the answer, that most days were under 100 cases, is true and close to useless, because 2020 in Singapore was not one epidemic curve at one intensity. The facets show January to March sitting flat against the axis, April to July spread right across it, August straddling both with its one 908-case day out on its own, and September to December back where the year started. That contrast is the finding, and a single histogram flattens it into a shape that describes no month in particular.\n\n## Put policy next to cases {#sec-sol-stringency}\n\n> Also from the chapter on plots: cases above, stringency below, one shared date axis, panels labelled A and B, then read the date of peak stringency off the figure and check it against the data.\n\nTwo ordinary plots, combined with `/`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_cases <- ggplot(covid, aes(x = date, y = daily_cases)) +\n  geom_line() +\n  scale_x_date(date_breaks = \"2 months\", date_labels = \"%b\") +\n  scale_y_continuous(labels = label_comma()) +\n  labs(x = NULL, y = \"New cases per day\")\n\np_stringency <- ggplot(covid, aes(x = date, y = stringency_index)) +\n  geom_line(colour = nus_colours[[\"crimson\"]]) +\n  scale_x_date(date_breaks = \"2 months\", date_labels = \"%b\") +\n  labs(x = NULL, y = \"Stringency index\")\n\n(p_cases / p_stringency) +\n  plot_annotation(\n    title    = \"Policy reached its ceiling ten days before cases turned\",\n    caption  = \"Sources: COVID-19 Data Hub; Oxford COVID-19 Government Response Tracker.\",\n    tag_levels = \"A\"\n  )\n```\n\n::: {.cell-output-display}\n![Policy stringency and reported cases, Singapore 2020.](solutions_files/figure-html/sol-stringency-1-1.svg)\n:::\n:::\n\n\nBoth panels use the same `scale_x_date()`, which is what makes them readable as one figure. Patchwork does not force a shared axis; it stacks two independent plots, and if one of them had a different date range the tick marks would not line up and the comparison would be silently wrong.\n\nReading it off the figure, panel B rises in a step in early April and flattens at its ceiling, and panel A is still climbing at that point. Checking against the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(stringency_index == max(stringency_index)) %>%\n  arrange(date) %>%\n  select(date, stringency_index, daily_cases)\n#> # A tibble: 3 × 3\n#>   date       stringency_index daily_cases\n#>   <date>                <dbl>       <dbl>\n#> 1 2020-04-10             82.4         198\n#> 2 2020-04-25             82.4         618\n#> 3 2020-05-01             82.4         932\n```\n:::\n\n\nThe maximum of 82.41 is reached on three separate days and the first is 10 April 2020. `slice_max()` would give you the same three rows, which is why the exercise warns you about it: with `n = 1` and default `with_ties = TRUE` you get all three, and `arrange(date)` then puts the earliest first. Taking `slice_max(..., n = 1, with_ties = FALSE)` and calling the result \"the date\" would be a guess dressed as an answer.\n\nCases had not peaked on 10 April. The peak was 1,426 on 20 April, ten days later, and on 10 April the count was 198:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>% slice_max(daily_cases, n = 1) %>% select(date, daily_cases)\n#> # A tibble: 1 × 2\n#>   date       daily_cases\n#>   <date>           <dbl>\n#> 1 2020-04-20        1426\n```\n:::\n\n\nTen days between the policy ceiling and the case peak is consistent with an incubation period plus a testing and reporting delay, and it is also consistent with a dormitory testing programme that was expanding through April independently of anything the index measures. This file cannot separate those, so the sentence to write is about the sequence, not the cause.\n\nOne thing not to do with panel B: read the small steps after July. There are 23 changes in the index after 1 July and several last a single day, which is indistinguishable from an encoding artifact in the source. A one-day tick is not a policy announcement.\n\n## Generalise the alert {#sec-sol-mobility-alert}\n\n> From the chapter on writing functions: let the caller choose which mobility series to check, keeping retail as the default, then count the days below −60 for workplaces and for parks.\n\nPassing a column name into a dplyr verb from inside a function needs `{{ }}` around the argument, which tells dplyr to look for the name in the data frame rather than in the calling environment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmobility_alert <- function(df,\n                           column    = retail_and_recreation_percent_change_from_baseline,\n                           threshold = -30) {\n  if (threshold > 0) {\n    stop(\"`threshold` should be negative. Mobility is measured as percentage change \",\n         \"from baseline, so a drop of 30% is -30, not 30.\", call. = FALSE)\n  }\n\n  df %>%\n    filter({{ column }} < threshold) %>%\n    pull(date)\n}\n```\n:::\n\n\nThe default is a bare column name, not a string, and it works because R does not evaluate a default argument until the function body needs it, by which point `filter()` has the data frame in scope. Existing calls are unaffected:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(mobility_alert(covid))\n#> [1] 88\n```\n:::\n\n\nEighty-eight, the same answer as before the rewrite. Adding an argument in the middle of a signature is the usual way to break other people's code, and putting the new argument after `df` with a default that reproduces the old behaviour is what keeps that from happening.\n\nThe two counts:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(mobility_alert(covid, workplaces_percent_change_from_baseline, threshold = -60))\n#> [1] 41\n\nlength(mobility_alert(covid, parks_percent_change_from_baseline, threshold = -60))\n#> [1] 37\n```\n:::\n\n\nForty-one days for workplaces and 37 for parks. Both counts exclude the 24 days with no mobility data, because `filter()` drops rows where the condition is `NA`, and that behaviour is now inherited by every call to this function.\n\nThe deepest workplace days:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  slice_min(workplaces_percent_change_from_baseline, n = 8) %>%\n  select(date, workplaces_percent_change_from_baseline) %>%\n  mutate(weekday = wday(date, label = TRUE))\n#> # A tibble: 8 × 3\n#>   date       workplaces_percent_change_from_baseline weekday\n#>   <date>                                       <dbl> <ord>  \n#> 1 2020-04-10                                     -83 Fri    \n#> 2 2020-05-01                                     -83 Fri    \n#> 3 2020-05-07                                     -83 Thu    \n#> 4 2020-05-25                                     -82 Mon    \n#> 5 2020-08-10                                     -73 Mon    \n#> 6 2020-07-10                                     -72 Fri    \n#> 7 2020-07-31                                     -72 Fri    \n#> 8 2020-12-25                                     -70 Fri\n```\n:::\n\n\nAll eight are public holidays: Good Friday on 10 April, Labour Day on 1 May, Vesak Day on 7 May, Hari Raya Puasa observed on 25 May, National Day observed on 10 August, polling day for the general election on 10 July, Hari Raya Haji on 31 July, and Christmas Day.\n\nThe interesting one is 10 July. The other seven are religious or seasonal holidays that recur every year and drag other things along with them, so a mobility trough on Good Friday tells you about Good Friday rather than about COVID-19. Polling day has none of that. It is a one-off public holiday, it sat inside Phase 2 with no change in restrictions around it, and workplace mobility fell 72% below baseline anyway. If you want a clean read on how far this series can move for a reason that has nothing to do with the epidemic, that is the day to look at.\n\n**What people get wrong.** Writing `filter(column < threshold)` without the braces. R then looks for an object called `column` in the calling environment, does not find one, and the error is `object 'column' not found`, which points at the wrong thing entirely. Or, worse, there *is* something called `column` in your global environment and the function quietly filters on that.\n\n## Add a judgement to the summary {#sec-sol-month-summary}\n\n> Also from the chapter on writing functions: give `month_summary()` a `verdict` column, run it on September and April, and decide whether five High days is a defensible cut-off.\n\n`summarise()` cannot reliably refer to a column it is creating in the same call, so the verdict goes in a `mutate()` afterwards. I have also made the cut-off an argument, for reasons below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary <- function(df, which_month, high_cut = 5) {\n  start <- floor_date(as.Date(which_month), \"month\")\n\n  if (!start %in% df$month) {\n    stop(\"No data for \", format(start, \"%B %Y\"), \". The data covers \",\n         format(min(df$month), \"%B %Y\"), \" to \",\n         format(max(df$month), \"%B %Y\"), \".\", call. = FALSE)\n  }\n\n  df %>%\n    filter(month == start) %>%\n    summarise(\n      month      = start,\n      days       = n(),\n      total      = sum(daily_cases),\n      mean_daily = round(mean(daily_cases), 1),\n      peak       = max(daily_cases),\n      peak_date  = date[which.max(daily_cases)],\n      high_days  = sum(severity == \"High\")\n    ) %>%\n    mutate(verdict = if_else(high_days > high_cut, \"Escalate\", \"All clear\"))\n}\n\nmonth_summary(covid, \"2020-09-01\")\n#> # A tibble: 1 × 8\n#>   month       days total mean_daily  peak peak_date  high_days verdict  \n#>   <date>     <int> <dbl>      <dbl> <dbl> <date>         <int> <chr>    \n#> 1 2020-09-01    30   953       31.8    86 2020-09-11         0 All clear\n\nmonth_summary(covid, \"2020-04-01\")\n#> # A tibble: 1 × 8\n#>   month       days total mean_daily  peak peak_date  high_days verdict \n#>   <date>     <int> <dbl>      <dbl> <dbl> <date>         <int> <chr>   \n#> 1 2020-04-01    30 15243       508.  1426 2020-04-20        18 Escalate\n```\n:::\n\n\nSeptember: 30 days, 953 cases, a mean of 31.8, a peak of 86, zero High days, \"All clear\". April: 15,243 cases, a peak of 1,426 on the 20th, 18 High days, \"Escalate\". Both verdicts match what the case counts say, which is the check the exercise asked for and is not a formality. Run this on twelve months and one of them will surprise you, and that is when you find out whether the rule or the data is wrong.\n\nIs five defensible? Not on the evidence in this file. Look at the whole year:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist_rbind(map(unique(covid$month), function(m) month_summary(covid, m))) %>%\n  select(month, days, total, mean_daily, high_days, verdict)\n#> # A tibble: 12 × 6\n#>    month       days total mean_daily high_days verdict  \n#>    <date>     <int> <dbl>      <dbl>     <int> <chr>    \n#>  1 2020-01-01    10    13        1.3         0 All clear\n#>  2 2020-02-01    29    89        3.1         0 All clear\n#>  3 2020-03-01    31   824       26.6         0 All clear\n#>  4 2020-04-01    30 15243      508.         18 Escalate \n#>  5 2020-05-01    31 18715      604.         31 Escalate \n#>  6 2020-06-01    30  9023      301.         12 Escalate \n#>  7 2020-07-01    31  8298      268.         12 Escalate \n#>  8 2020-08-01    31  4607      149.          4 All clear\n#>  9 2020-09-01    30   953       31.8         0 All clear\n#> 10 2020-10-01    31   250        8.1         0 All clear\n#> 11 2020-11-01    30   203        6.8         0 All clear\n#> 12 2020-12-01    31   381       12.3         0 All clear\n```\n:::\n\n\nAcross the twelve months, `high_days` only ever takes the values 0, 4, 12, 18 and 31. Nothing sits between 4 and 12. Five splits the year into four escalating months and eight clear ones, and so does any cut-off from 4 up to 11. Drop to 3 and August joins the escalating group; go up to 12 and June and July leave it. The rule is stable against small changes, which is reassuring, and the data gives you no reason to prefer five over any other number in that range, which is not.\n\nAugust is where it bites. Four High days, so \"All clear\", on a month that recorded 4,607 cases, more than September through December put together. The rule counts days over 300 and August's burden was distributed differently.\n\nThat is why `high_cut` is an argument rather than a hard-coded 5. Not because the caller will change it often, but because a number that appears in a function signature with a default is a number somebody chose, and a number buried in the body is a number nobody can find. Set it once, at the top, where a reviewer can argue with it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary(covid, \"2020-08-01\", high_cut = 3) %>%\n  select(month, high_days, mean_daily, verdict)\n#> # A tibble: 1 × 4\n#>   month      high_days mean_daily verdict \n#>   <date>         <int>      <dbl> <chr>   \n#> 1 2020-08-01         4       149. Escalate\n```\n:::\n\n\n## Cumulative deaths, both ways {#sec-sol-loop-vs-lag}\n\n> From the chapter on loops: difference the `deaths` column with an explicit `for` loop, then with `lag()`, check the two with `identical()`, and account for the gap against 29.\n\nThe loop is the same shape as the one the chapter wrote for `confirmed`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_deaths_loop <- numeric(nrow(covid))\n\nfor (i in seq_along(daily_deaths_loop)) {\n  if (i == 1) {\n    daily_deaths_loop[i] <- covid$deaths[i]\n  } else {\n    daily_deaths_loop[i] <- covid$deaths[i] - covid$deaths[i - 1]\n  }\n}\n\nhead(daily_deaths_loop, 8)\n#> [1] NA NA NA NA NA NA NA NA\n```\n:::\n\n\nEight `NA`s, because `deaths` is missing for the first 59 days. The vectorised version:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_deaths_lag <- covid %>%\n  mutate(dd = deaths - lag(deaths, default = 0)) %>%\n  pull(dd)\n\nidentical(daily_deaths_loop, daily_deaths_lag)\n#> [1] TRUE\n```\n:::\n\n\n`TRUE`. The two agree, including on where the `NA`s fall, which is the part worth checking: `identical()` treats `NA` as a value like any other, so a version that produced `NA` in a different place would come back `FALSE` even if every real number matched.\n\nThe reconciliation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(daily_deaths_loop, na.rm = TRUE)\n#> [1] 27\n\nmax(covid$deaths, na.rm = TRUE)\n#> [1] 29\n\nsum(is.na(daily_deaths_loop))\n#> [1] 60\n```\n:::\n\n\nTwenty-seven against a final cumulative figure of 29, with 60 missing values in the differenced series.\n\nSixty, not 59. That is the detail to account for. `deaths` is `NA` for rows 1 to 59, and row 60, which is 21 March 2020, is the first day with a recorded value. Its difference is `2 - NA`, which is `NA`, so the differenced series is missing for one row longer than the raw column is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  slice(58:62) %>%\n  select(date, deaths, daily_deaths)\n#> # A tibble: 5 × 3\n#>   date       deaths daily_deaths\n#>   <date>      <dbl>        <dbl>\n#> 1 2020-03-19     NA           NA\n#> 2 2020-03-20     NA           NA\n#> 3 2020-03-21      2           NA\n#> 4 2020-03-22      2            0\n#> 5 2020-03-23      2            0\n```\n:::\n\n\nThe first recorded value is 2, not 1. Two deaths had already occurred by the time the series starts, and differencing recovers changes rather than levels, so those two are unrecoverable from this column. 29 minus 2 is 27, and the arithmetic closes.\n\nNone of that is an error in your code. It is what the file says, and the useful response is to write it down rather than to patch it. @sec-missing shows the patch, which is a decision about whether the leading `NA`s mean \"zero deaths so far\" or \"not reported\", and those two readings give different answers.\n\n## An SIR model with an intervention {#sec-sol-sir-step}\n\n> Also from the chapter on loops: add a circuit breaker to the SIR model between days 40 and 95, plot the infectious compartment against the unmodified run, and say what happens when the intervention lifts.\n\nThe trick is that `beta` does not have to be one number. Make it a vector of length `days` and index it inside the loop:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsir_run <- function(beta, gamma = 0.1, N = 100000, days = 150, I0 = 10) {\n  if (length(beta) == 1) beta <- rep(beta, days)\n\n  S <- numeric(days)\n  I <- numeric(days)\n  R <- numeric(days)\n\n  S[1] <- N - I0\n  I[1] <- I0\n  R[1] <- 0\n\n  for (t in 2:days) {\n    new_infections <- beta[t - 1] * S[t - 1] * I[t - 1] / N\n    new_removals   <- gamma * I[t - 1]\n\n    S[t] <- S[t - 1] - new_infections\n    I[t] <- I[t - 1] + new_infections - new_removals\n    R[t] <- R[t - 1] + new_removals\n  }\n\n  tibble(day = 1:days, S = S, I = I, R = R)\n}\n\nbeta_cb <- rep(0.3, 150)\nbeta_cb[40:95] <- 0.15\n\nbaseline     <- sir_run(0.3)\nintervention <- sir_run(beta_cb)\n```\n:::\n\n\nWrapping the loop in a function is the change that makes this exercise tractable. Two runs means two of everything, and copying the loop and editing one line in the copy is precisely the failure mode @sec-functions is about. `beta[t - 1]` rather than `beta[t]` because the transmission that produces day `t`'s infections happened on day `t - 1`, which matches the rest of the loop's indexing.\n\nBoth runs in one tibble, so they can be plotted together:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nruns <- bind_rows(\n  baseline     %>% mutate(run = \"No intervention\"),\n  intervention %>% mutate(run = \"Beta halved, days 40-95\")\n)\n\nggplot(runs, aes(x = day, y = I, colour = run)) +\n  annotate(\"rect\", xmin = 40, xmax = 95, ymin = -Inf, ymax = Inf,\n           fill = nus_colours[[\"muted\"]], alpha = 0.2) +\n  geom_line(linewidth = 0.8) +\n  scale_y_continuous(labels = label_comma()) +\n  labs(\n    x = \"Day\", y = \"Infectious\", colour = NULL,\n    title = \"The intervention flattens the peak and leaves a second one behind\",\n    caption = \"Illustrative parameters. Not a model of Singapore.\"\n  )\n```\n\n::: {.cell-output-display}\n![A 56-day reduction in transmission from day 40, against the unmodified run. Illustrative parameters, not fitted to any data.](solutions_files/figure-html/sol-sir-2-1.svg)\n:::\n:::\n\n\nThe two questions, answered from the output rather than from what a model is supposed to do:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  run       = c(\"No intervention\", \"Beta halved, days 40-95\"),\n  peak_day  = c(baseline$day[which.max(baseline$I)],\n                intervention$day[which.max(intervention$I)]),\n  peak_I    = round(c(max(baseline$I), max(intervention$I))),\n  final_R   = round(c(tail(baseline$R, 1), tail(intervention$R, 1)))\n)\n#> # A tibble: 2 × 4\n#>   run                     peak_day peak_I final_R\n#>   <chr>                      <int>  <dbl>   <dbl>\n#> 1 No intervention               55  31211   94649\n#> 2 Beta halved, days 40-95       55  12072   76470\n```\n:::\n\n\nThe peak gets much smaller, from about 31,200 infectious to about 12,100, and with these parameters it does not get later at all. Both peak on day 55. That surprised me the first time and it has a clean explanation: the peak occurs when susceptibles fall to $\\gamma N / \\beta$, and halving $\\beta$ doubles that threshold, so the intervention run reaches its (higher) threshold at roughly the same time the baseline reaches its (lower) one. Change the dates or the depth of the intervention and the peaks separate. The generalisation \"interventions delay the peak\" is not something the arithmetic guarantees.\n\nAfter day 95 the intervention lifts and there is a second rise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintervention %>%\n  filter(day %in% c(95, 100, 108, 120, 150)) %>%\n  mutate(across(c(S, I, R), round))\n#> # A tibble: 5 × 4\n#>     day     S     I     R\n#>   <int> <dbl> <dbl> <dbl>\n#> 1    95 38867  4157 56976\n#> 2   100 36771  4208 59021\n#> 3   108 33127  4396 62477\n#> 4   120 28367  4018 67615\n#> 5   150 21722  1808 76470\n```\n:::\n\n\nInfections bottom out around day 95 and climb again to a local peak near day 108. The reason is in the `S` column. At day 95 the intervention run still has 38,867 susceptibles against the baseline's 5,713. With $\\beta$ back at 0.3 and $\\gamma$ at 0.1, each infectious person infects more than one other while $S/N$ stays above one third, so the epidemic restarts.\n\nWould I have predicted it? The direction, yes, once you look at where the susceptibles are. The size, no. The final attack rate falls from 95% to 76%, so the intervention prevented about 18,000 infections in a population of 100,000 despite the rebound, which is more than the shape of the curve suggests at a glance. Suppression without immunity postpones; it does not cancel. Whether the postponement is worth it depends on what you do with the time, and that is not a question this model contains.\n\n## Write the August 2020 situation report {#sec-sol-sitrep}\n\n> From the capstone chapter: the one-page report for August 2020, with a table, two figures, three sentences and a note on what the analysis cannot tell you.\n\nAugust's decision is 5 August, and everything below turns on how it gets handled. So the maximum, the median and the date of the maximum come out first, before anything else is computed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport_month <- as.Date(\"2020-08-01\")\n\naugust <- covid %>% filter(month == report_month)\n\nnrow(august)\n#> [1] 31\n\naugust %>%\n  summarise(\n    days         = n(),\n    cases        = sum(daily_cases),\n    mean_daily   = round(mean(daily_cases), 1),\n    median_daily = median(daily_cases),\n    peak         = max(daily_cases),\n    peak_date    = date[which.max(daily_cases)],\n    deaths       = sum(daily_deaths)\n  )\n#> # A tibble: 1 × 7\n#>    days cases mean_daily median_daily  peak peak_date  deaths\n#>   <int> <dbl>      <dbl>        <dbl> <dbl> <date>      <dbl>\n#> 1    31  4607       149.           91   908 2020-08-05      0\n```\n:::\n\n\nA mean of 148.6 and a median of 91. When those two are that far apart, the mean is describing one day rather than the month. Look at the top of the distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugust %>%\n  slice_max(daily_cases, n = 5) %>%\n  select(date, daily_cases)\n#> # A tibble: 5 × 2\n#>   date       daily_cases\n#>   <date>           <dbl>\n#> 1 2020-08-05         908\n#> 2 2020-08-02         313\n#> 3 2020-08-01         307\n#> 4 2020-08-06         301\n#> 5 2020-08-04         295\n```\n:::\n\n\n908 on 5 August, and the next highest day is 313. One day carries 19.7% of the month's cases. This is the decision the exercise refers to, and the wrong response is to delete the day. It happened, the cases were real, and MOH attributed the count to clearance testing in the dormitories picking up past infections: 903 of the 908 were dormitory residents and 581 were linked to a single cluster at Acacia Lodge. A case detected on 5 August was not necessarily an infection that occurred on 5 August, and that distinction belongs in the report, not in a filter.\n\nSo I report both figures and say why:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugust %>%\n  filter(date != as.Date(\"2020-08-05\")) %>%\n  summarise(\n    days         = n(),\n    cases        = sum(daily_cases),\n    mean_daily   = round(mean(daily_cases), 1),\n    median_daily = median(daily_cases),\n    peak         = max(daily_cases)\n  )\n#> # A tibble: 1 × 5\n#>    days cases mean_daily median_daily  peak\n#>   <int> <dbl>      <dbl>        <dbl> <dbl>\n#> 1    30  3699       123.           89   313\n```\n:::\n\n\nWithout 5 August the mean falls from 148.6 to 123.3 and the median barely moves, from 91 to 89. The median was already telling you what a typical August day looked like. That is the argument for putting a median in every monthly table.\n\nDeaths are 0 for August. The cumulative column reads 27 on 31 July and 27 on 31 August, so this is a real zero and not a gap, and August is late enough in the year that the leading `NA` problem in `deaths` does not touch it.\n\n### The table\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugust_weeks <- august %>%\n  mutate(week = floor_date(date, \"week\", week_start = 1)) %>%\n  group_by(week) %>%\n  summarise(\n    days         = n(),\n    cases        = sum(daily_cases),\n    median_daily = median(daily_cases),\n    peak         = max(daily_cases),\n    retail       = round(mean(retail_and_recreation_percent_change_from_baseline)),\n    stringency   = round(mean(stringency_index), 1)\n  )\n\naugust_weeks\n#> # A tibble: 6 × 7\n#>   week        days cases median_daily  peak retail stringency\n#>   <date>     <int> <dbl>        <dbl> <dbl>  <dbl>      <dbl>\n#> 1 2020-07-27     2   620          310   313    -20       50.9\n#> 2 2020-08-03     7  2279          242   908    -22       51.7\n#> 3 2020-08-10     7   643           83   188    -22       50.9\n#> 4 2020-08-17     7   606           91   117    -24       51.7\n#> 5 2020-08-24     7   418           54    94    -21       51.7\n#> 6 2020-08-31     1    41           41    41    -21       50.9\n```\n:::\n\n\nRead `days` first. August 2020 began on a Saturday, so the first row covers two days and the last covers one, and comparing `cases` across those rows would be comparing different amounts of time. `median_daily` is in the table instead of a mean for the reason above, and it does the job: 310 and 242 in the first two weeks, then 83, 91, 54 and 41. The month steps down sharply after 9 August and then drifts, which is not what the `cases` column shows, because week two's total is inflated by the 5 August spike.\n\n### The first figure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspike <- as.Date(\"2020-08-05\")\n\np_aug_cases <- ggplot(august, aes(x = date, y = daily_cases)) +\n  geom_col(fill = nus_colours[[\"blue\"]]) +\n  annotate(\"text\", x = spike + 1, y = 880, hjust = 0, size = 3,\n           colour = nus_colours[[\"crimson\"]],\n           label = \"5 Aug: 908 cases,\\n903 of them dormitory residents\") +\n  scale_x_date(date_breaks = \"1 week\", date_labels = \"%d %b\") +\n  scale_y_continuous(labels = label_comma()) +\n  labs(\n    title    = \"One day carries a fifth of August's cases\",\n    subtitle = \"Singapore, new COVID-19 cases reported each day, August 2020\",\n    x = NULL, y = \"New cases reported\",\n    caption  = \"Source: COVID-19 Data Hub. Reported cases, not infections.\"\n  )\n\np_aug_cases\n```\n\n::: {.cell-output-display}\n![Daily reported cases in Singapore, August 2020.](solutions_files/figure-html/sol-sitrep-5-1.svg)\n:::\n:::\n\n\nBars rather than a line, because 31 discrete daily counts are exactly the case where individual days matter and there is nothing measured in between. The annotation does the work that a footnote would otherwise have to do, and the title makes a claim rather than naming the axes.\n\n### The second figure\n\nThe case curve says what was reported. The second figure has to answer a different question, and in August the interesting one is whether anything else changed while cases fell:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugust_mobility <- august %>%\n  select(\n    date,\n    `Retail and recreation` = retail_and_recreation_percent_change_from_baseline,\n    Workplaces              = workplaces_percent_change_from_baseline\n  ) %>%\n  pivot_longer(-date, names_to = \"series\", values_to = \"change\")\n\nggplot(august_mobility, aes(x = date, y = change, colour = series)) +\n  geom_hline(yintercept = 0, colour = nus_colours[[\"muted\"]], linewidth = 0.3) +\n  geom_line() +\n  scale_x_date(date_breaks = \"1 week\", date_labels = \"%d %b\") +\n  labs(\n    title    = \"Cases fell through August; movement did not move\",\n    subtitle = \"Percent change from Google's 3 January to 6 February 2020 baseline\",\n    x = NULL, y = \"Change from baseline (%)\", colour = NULL,\n    caption  = \"The 10 August workplace trough is National Day observed, a public holiday.\"\n  )\n```\n\n::: {.cell-output-display}\n![Retail and workplace mobility in August 2020, as percent change from Google's pre-pandemic baseline.](solutions_files/figure-html/sol-sitrep-6-1.svg)\n:::\n:::\n\n\nRetail sits between 15% and 27% below baseline all month with no trend in it. Workplaces oscillate with the week, and the one deep trough, 73% below baseline on 10 August, is National Day observed rather than anything epidemiological. Stringency moves almost as little: 50.93 on 28 of the 31 days, with three scattered days at 56.48 that are exactly the one-day ticks @sec-visualise warns against reading as announcements.\n\nThe weekly median more than halved while neither of those series went anywhere. That constrains the explanations available and it does not identify a cause, which is a sentence worth writing down rather than talking yourself out of.\n\n### The three sentences\n\n> August recorded 4,607 cases across 31 complete days and no deaths, with the median daily count falling from 248 in July to 91, and 4 of its days above 300 against July's 12.\n\n> One day, 5 August, accounts for 908 of those cases, nearly a fifth of the month, and MOH attributed that day's figures to clearance testing in the dormitories detecting past infections, so August's mean of 148.6 falls to 123.3 when that day is set aside while the median barely moves.\n\n> Retail mobility held between 15% and 27% below baseline for the whole month and the stringency index sat at 50.93 on 28 of the 31 days, so August's decline in reported cases came without any measurable change in movement and with policy essentially unchanged.\n\nThree sentences, three jobs. The first sizes the month and states the denominator. The second addresses the thing a reader would otherwise get wrong. The third brings in the second data source and reports what it rules out.\n\n### What this analysis does not tell you\n\n**It cannot separate a fall in transmission from a fall in testing.** There is no test-count column in this file, so test positivity is not computable. August's declining curve is consistent with fewer infections and it is also consistent with the dormitory testing programme winding down after clearance was completed. Those are different worlds and this file does not distinguish them.\n\n**The 5 August spike is a dating problem as well as an outlier.** Cases reported that day include infections that occurred earlier, so the shape of August's curve is partly an artifact of when swabs were processed. Every weekly comparison in the table above inherits that.\n\n**The national total is still averaging two epidemics.** Through August the dormitory outbreak and community transmission had different sizes and different testing intensities, and this file carries one number for both. Every mean in this report is a weighted average with weights that are not in the data.\n\n**Flat mobility is weak evidence about the population that mattered.** This is my reading rather than something the file establishes. Google's mobility series come from location history on phones where that setting is switched on, and Google does not publish them broken down by nationality or work-permit status. Whether the movement of people in dormitories under quarantine appears in these curves at all is unanswerable from here, so I would not use the flat retail line to say anything about behaviour inside the dormitories, which is where 903 of the 908 cases on the month's biggest day were recorded.\n",
    "supporting": [
      "solutions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}