<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="A hands-on introduction to R and the tidyverse for public health students, built around a single real dataset: every day of Singapore’s 2020 COVID-19 epidemic. Written for SPH5421 at the NUS Saw Swee Hock School of Public Health.">
<title>12&nbsp; A monthly situation report – An Introduction to R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/next-steps.html" rel="next">
<link href="../chapters/iteration.html" rel="prev">
<link href="../assets/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cf46b01eabe5934f78e5ab797c839044.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/capstone.html">Putting it together</a></li><li class="breadcrumb-item"><a href="../chapters/capstone.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">A monthly situation report</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">An Introduction to R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://raw.githubusercontent.com/CERM-NUS/r-intro/main/data/sg_covid_data.csv" title="Download the data" class="quarto-navigation-tool px-1" aria-label="Download the data"><i class="bi bi-file-earmark-spreadsheet"></i></a>
    <a href="https://github.com/CERM-NUS/r-intro" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Before you write any code</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting set up</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">The R you cannot avoid</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Objects, vectors and functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/rectangles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Rectangles: data frames and tibbles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reading the epidemic in</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Working with the data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transforming data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Missing values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/conditionals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Making decisions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Grouping and summarising</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Showing it to someone</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/visualise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Plots</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Writing your own code</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Writing functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/iteration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Loops, and when you need them</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Putting it together</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/capstone.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">A monthly situation report</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/next-steps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Where to go next</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/good-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Good practice</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Worked solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">The data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/build.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">How this book is built</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/colophon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Colophon</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#the-brief" id="toc-the-brief" class="nav-link active" data-scroll-target="#the-brief"><span class="header-section-number">12.1</span> The brief</a></li>
  <li><a href="#what-a-good-report-contains" id="toc-what-a-good-report-contains" class="nav-link" data-scroll-target="#what-a-good-report-contains"><span class="header-section-number">12.2</span> What a good report contains</a></li>
  <li>
<a href="#april-2020-worked" id="toc-april-2020-worked" class="nav-link" data-scroll-target="#april-2020-worked"><span class="header-section-number">12.3</span> April 2020, worked</a>
  <ul class="collapse">
<li><a href="#a-script-that-stands-on-its-own" id="toc-a-script-that-stands-on-its-own" class="nav-link" data-scroll-target="#a-script-that-stands-on-its-own"><span class="header-section-number">12.3.1</span> A script that stands on its own</a></li>
  <li><a href="#the-headline-numbers" id="toc-the-headline-numbers" class="nav-link" data-scroll-target="#the-headline-numbers"><span class="header-section-number">12.3.2</span> The headline numbers</a></li>
  <li><a href="#the-table" id="toc-the-table" class="nav-link" data-scroll-target="#the-table"><span class="header-section-number">12.3.3</span> The table</a></li>
  <li><a href="#the-first-figure-the-epidemic-curve" id="toc-the-first-figure-the-epidemic-curve" class="nav-link" data-scroll-target="#the-first-figure-the-epidemic-curve"><span class="header-section-number">12.3.4</span> The first figure: the epidemic curve</a></li>
  <li><a href="#the-second-figure-mobility" id="toc-the-second-figure-mobility" class="nav-link" data-scroll-target="#the-second-figure-mobility"><span class="header-section-number">12.3.5</span> The second figure: mobility</a></li>
  <li><a href="#the-three-sentences" id="toc-the-three-sentences" class="nav-link" data-scroll-target="#the-three-sentences"><span class="header-section-number">12.3.6</span> The three sentences</a></li>
  </ul>
</li>
  <li><a href="#what-this-analysis-does-not-tell-you" id="toc-what-this-analysis-does-not-tell-you" class="nav-link" data-scroll-target="#what-this-analysis-does-not-tell-you"><span class="header-section-number">12.4</span> What this analysis does not tell you</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><span class="header-section-number">12.5</span> Your turn</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/CERM-NUS/r-intro/edit/main/chapters/capstone.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/CERM-NUS/r-intro/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/CERM-NUS/r-intro/blob/main/chapters/capstone.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/capstone.html">Putting it together</a></li><li class="breadcrumb-item"><a href="../chapters/capstone.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">A monthly situation report</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-capstone" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">A monthly situation report</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Up to now, each chapter has posed a question with the shape of its answer already visible: filter these rows, group by that column, plot the result. Requests in practice are less specified. They arrive from someone who wants to know what happened, by a deadline, in a form they can put in front of a committee.</p>
<p>The request in this chapter is of that kind: pick a month of Singapore’s 2020 and write the report. April is worked through first, to set out what the finished report looks like, and August is left to you.</p>
<section id="the-brief" class="level2" data-number="12.1"><h2 data-number="12.1" class="anchored" data-anchor-id="the-brief">
<span class="header-section-number">12.1</span> The brief</h2>
<p>The report covers one month and occupies one page. That page carries a table that gives the reader the month in numbers, two figures that show something the table cannot, and three sentences of interpretation. The limit of three is deliberate, because choosing which three findings matter takes more work than writing several paragraphs of hedged description.</p>
<p>Assume the reader is a public health officer who knows Singapore and does not know R. They will not read your code. They will look at the figures first, the table second, and your sentences only if the figures made them curious.</p>
</section><section id="what-a-good-report-contains" class="level2" data-number="12.2"><h2 data-number="12.2" class="anchored" data-anchor-id="what-a-good-report-contains">
<span class="header-section-number">12.2</span> What a good report contains</h2>
<p>A good report has six elements, and every one of them is something you already know how to produce.</p>
<ol type="1">
<li>
<strong>The month is stated, and so is the denominator.</strong> How many days does the month have, and how many of them carry data? Every month in this file is complete, but state that rather than leaving the reader to assume it.</li>
<li>
<strong>A count and a shape.</strong> A total tells you the size of the month. A median, a maximum and the date of the maximum tell you whether that total accumulated steadily or came from a small number of large days. Report both.</li>
<li>
<strong>A table at a unit the reader can take in.</strong> Days are too fine for a monthly table, and the month itself is too coarse; weeks are the workable grain.</li>
<li>
<strong>Two figures that answer different questions.</strong> Two views of the case curve is one figure drawn twice. Pair the epidemic curve with something else in the file: mobility, the stringency index, the severity mix.</li>
<li>
<strong>Every figure has a title that states a finding.</strong> “Daily cases, April 2020” only labels the figure, whereas “Cases rose for 13 days after the circuit breaker began” states a finding. A title that makes a claim has to be checked against the data before it can stand.</li>
<li>
<strong>At least one caveat that comes from looking at the data, not from a template.</strong> “Data may be incomplete” could be written without opening the file. “The 5 August count is four times the next highest August day and needs an explanation before it goes in a mean” could only come from the data.</li>
</ol></section><section id="april-2020-worked" class="level2" data-number="12.3"><h2 data-number="12.3" class="anchored" data-anchor-id="april-2020-worked">
<span class="header-section-number">12.3</span> April 2020, worked</h2>
<section id="a-script-that-stands-on-its-own" class="level3" data-number="12.3.1"><h3 data-number="12.3.1" class="anchored" data-anchor-id="a-script-that-stands-on-its-own">
<span class="header-section-number">12.3.1</span> A script that stands on its own</h3>
<p>The report script has to run from the top in a fresh R session, with nothing carried over from earlier work: the file is read, the columns are built, and only then are they used. Everything the script needs is inside the script. The chunk below is the pipeline from the conditionals chapter, written out once in full so that no part of the report depends on state you cannot see.</p>
<p><strong>Restart R and run the script from the top; whatever it still needs belongs in the script.</strong></p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">covid</span> <span class="op">&lt;-</span> <span class="fu">read_covid</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="va">date</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    daily_cases  <span class="op">=</span> <span class="va">confirmed</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lag.html">lag</a></span><span class="op">(</span><span class="va">confirmed</span>, default <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>    daily_deaths <span class="op">=</span> <span class="va">deaths</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lag.html">lag</a></span><span class="op">(</span><span class="va">deaths</span>, default <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>    severity <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span></span>
<span>      <span class="va">daily_cases</span> <span class="op">&lt;</span>  <span class="fl">100</span> <span class="op">~</span> <span class="st">"Low"</span>,</span>
<span>      <span class="va">daily_cases</span> <span class="op">&lt;=</span> <span class="fl">300</span> <span class="op">~</span> <span class="st">"Medium"</span>,</span>
<span>      <span class="va">daily_cases</span> <span class="op">&gt;</span>  <span class="fl">300</span> <span class="op">~</span> <span class="st">"High"</span></span>
<span>    <span class="op">)</span>,</span>
<span>    severity <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">severity</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    month <span class="op">=</span> <span class="fu">floor_date</span><span class="op">(</span><span class="va">date</span>, <span class="st">"month"</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you are writing this in a script of your own rather than inside the book’s project, swap <code>read_covid()</code> for <code>read_csv(here("data", "sg_covid_data.csv"))</code>. That helper exists so that the chapters do not repeat a file path in every chunk, and nothing else in the pipeline depends on it.</p>
<p>Then pick the month once, at the top, in a named object. When you move to August you change one line rather than hunting for <code>"2020-04"</code> scattered through twenty chunks.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">report_month</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="st">"2020-04-01"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">april</span> <span class="op">&lt;-</span> <span class="va">covid</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">month</span> <span class="op">==</span> <span class="va">report_month</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">april</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 30</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The result is thirty rows for a thirty-day month. The check is one line, and it catches a mis-specified filter before anything is computed from it.</p>
</section><section id="the-headline-numbers" class="level3" data-number="12.3.2"><h3 data-number="12.3.2" class="anchored" data-anchor-id="the-headline-numbers">
<span class="header-section-number">12.3.2</span> The headline numbers</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Predict before you run this
</div>
</div>
<div class="callout-body-container callout-body">
<p>April 2020 has one day far larger than the rest. Write down the date you think it fell on before you read the next output. The circuit breaker started on 7 April, which makes the first week the intuitive guess: restrictions came in and conditions improved from there.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">april</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    days         <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>    cases        <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span>,</span>
<span>    mean_daily   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span>,</span>
<span>    median_daily <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span>,</span>
<span>    peak         <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span>,</span>
<span>    peak_date    <span class="op">=</span> <span class="va">date</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.min.html">which.max</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span><span class="op">]</span>,</span>
<span>    deaths       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">daily_deaths</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 7</span></span>
<span><span class="co">#&gt;    days cases mean_daily median_daily  peak peak_date  deaths</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1    30 15243       508.         488.  1426 2020-04-20     12</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The peak is 20 April, thirteen days after the circuit breaker began. Reported cases continued to rise for two weeks after Singapore closed workplaces and required people to stay at home.</p>
<p>That is not a paradox, and the reason matters. Reported cases are the output of a testing programme, not a direct measurement of infection. Through April, testing in the migrant-worker dormitories was expanding fast, and the dormitory outbreak dominated the national count from April to August. A rising reported curve during that period is partly transmission and partly the swab rate catching up with infections that had already happened. The two cannot be separated from this file, and the report should say so.</p>
<p>Note two details of that output. <code>median_daily</code> prints as <code>488.</code> with a trailing full stop, which is the tibble telling you the value is not a whole number: it is 487.5, the average of the two middle days. The <code>deaths</code> total is 12 here, which is reliable for April because the <code>deaths</code> column has no missing values from 21 March onwards. Earlier in the year it does, with 59 leading <code>NA</code>s, and lag-differencing across them recovers only 27 of the year’s 29 deaths. If your chosen month is January, February or March, state that in the report.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">april</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">count</span><span class="op">(</span><span class="va">severity</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 2</span></span>
<span><span class="co">#&gt;   severity     n</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;    &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 Low          5</span></span>
<span><span class="co">#&gt; 2 Medium       7</span></span>
<span><span class="co">#&gt; 3 High        18</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Eighteen of April’s thirty days were over 300 cases. Across the whole year only 77 days were, so April holds nearly a quarter of the year’s highest-count days in a single month.</p>
</section><section id="the-table" class="level3" data-number="12.3.3"><h3 data-number="12.3.3" class="anchored" data-anchor-id="the-table">
<span class="header-section-number">12.3.3</span> The table</h3>
<p>Weeks are the right grain for a monthly table. <code>floor_date(date, "week", week_start = 1)</code> puts each date on its Monday. The <code>week_start</code> argument is set explicitly because lubridate’s default is Sunday, so without it every week in the table would run from Sunday to Saturday. Stating it makes the assumption visible at the cost of one argument.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">april_weeks</span> <span class="op">&lt;-</span> <span class="va">april</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>week <span class="op">=</span> <span class="fu">floor_date</span><span class="op">(</span><span class="va">date</span>, <span class="st">"week"</span>, week_start <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">week</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    days       <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>    cases      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span>,</span>
<span>    mean_daily <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    peak       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">daily_cases</span><span class="op">)</span>,</span>
<span>    retail     <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">retail_and_recreation_percent_change_from_baseline</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    stringency <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">stringency_index</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">april_weeks</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 7</span></span>
<span><span class="co">#&gt;   week        days cases mean_daily  peak retail stringency</span></span>
<span><span class="co">#&gt;   &lt;date&gt;     &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 2020-03-30     5   383         77   120    -23       41.7</span></span>
<span><span class="co">#&gt; 2 2020-04-06     7  1223        175   287    -53       71  </span></span>
<span><span class="co">#&gt; 3 2020-04-13     7  4056        579   942    -61       76.8</span></span>
<span><span class="co">#&gt; 4 2020-04-20     7  7036       1005  1426    -67       77.6</span></span>
<span><span class="co">#&gt; 5 2020-04-27     4  2545        636   799    -67       76.8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Look at the <code>days</code> column before you look at anything else. The first row covers five days, not seven, because April 2020 started on a Wednesday and the week beginning 30 March mostly belongs to March. The last row covers four. Any comparison of <code>cases</code> across those rows is comparing different amounts of time, which is why <code>mean_daily</code> is in the table and why <code>days</code> is in it too. Leave <code>days</code> out and a reader will read 383 against 1,223 as a threefold rise when part of the difference is two extra days.</p>
<p>The rest of the table tells a fairly clean story. Weekly totals climb from 383 to 7,036 and then fall back. Mean retail mobility drops from 23% below baseline in the first partial week to 67% below in each of the last two. Mean stringency goes from 41.7 to 71 in one step and sits in the seventies for the rest of the month.</p>
</section><section id="the-first-figure-the-epidemic-curve" class="level3" data-number="12.3.4"><h3 data-number="12.3.4" class="anchored" data-anchor-id="the-first-figure-the-epidemic-curve">
<span class="header-section-number">12.3.4</span> The first figure: the epidemic curve</h3>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cb_start</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="st">"2020-04-07"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">april</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">date</span>, <span class="va">daily_cases</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Bars: one column per day of reported cases</span></span>
<span>  <span class="fu">geom_col</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">nus_colours</span><span class="op">[[</span><span class="st">"blue"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Circuit-breaker marker and its text label</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">cb_start</span>, colour <span class="op">=</span> <span class="va">nus_colours</span><span class="op">[[</span><span class="st">"crimson"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>             linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">annotate</span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="va">cb_start</span> <span class="op">+</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="fl">1350</span>, hjust <span class="op">=</span> <span class="fl">0</span>, size <span class="op">=</span> <span class="fl">3.2</span>,</span>
<span>           colour <span class="op">=</span> <span class="va">nus_colours</span><span class="op">[[</span><span class="st">"crimson"</span><span class="op">]</span><span class="op">]</span>, label <span class="op">=</span> <span class="st">"Circuit breaker begins"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Axis formatting: weekly date breaks, comma-formatted counts</span></span>
<span>  <span class="fu">scale_x_date</span><span class="op">(</span>date_breaks <span class="op">=</span> <span class="st">"1 week"</span>, date_labels <span class="op">=</span> <span class="st">"%d %b"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">label_comma</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Text: title states the finding; caption carries the source and the caveat</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Cases rose for 13 days after the circuit breaker began"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Singapore, new COVID-19 cases reported each day, April 2020"</span>,</span>
<span>    x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="st">"New cases reported"</span>,</span>
<span>    caption <span class="op">=</span> <span class="st">"Source: COVID-19 Data Hub. Reported cases, not infections."</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-april-cases" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-april-cases-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="capstone_files/figure-html/fig-april-cases-1.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-april-cases-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Daily reported cases in Singapore, April 2020, with the start of the circuit breaker marked.
</figcaption></figure>
</div>
</div>
</div>
<p>The figure uses columns rather than a line, because these are counts of things that happened on discrete days, and a line would imply that a value could be read halfway between two dates. The dashed rule and the label do the work that a paragraph of text would otherwise have to do. The caption carries the source and the one warning the reader most needs.</p>
<p>The date breaks are weekly and the labels are <code>"%d %b"</code>, so the axis reads 06 Apr, 13 Apr, 20 Apr.&nbsp;Left to itself ggplot2 would have chosen something reasonable but not necessarily aligned with the weeks in your table, and a reader who is trying to match figure to table will notice.</p>
</section><section id="the-second-figure-mobility" class="level3" data-number="12.3.5"><h3 data-number="12.3.5" class="anchored" data-anchor-id="the-second-figure-mobility">
<span class="header-section-number">12.3.5</span> The second figure: mobility</h3>
<p>The case curve records what was reported. The mobility columns record where people went, which is a different question and the reason this file supports more than a case series on its own.</p>
<p>Two series on one set of axes means one row per series per date, so the two columns have to become one column of values plus one column of labels. <code>pivot_longer()</code> does that. It is from tidyr, which came in with the tidyverse, and it is the only function in this chapter you have not already met.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">april_mobility</span> <span class="op">&lt;-</span> <span class="va">april</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span></span>
<span>    <span class="va">date</span>,</span>
<span>    `Retail and recreation` <span class="op">=</span> <span class="va">retail_and_recreation_percent_change_from_baseline</span>,</span>
<span>    Workplaces              <span class="op">=</span> <span class="va">workplaces_percent_change_from_baseline</span></span>
<span>  <span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">pivot_longer</span><span class="op">(</span><span class="op">-</span><span class="va">date</span>, names_to <span class="op">=</span> <span class="st">"series"</span>, values_to <span class="op">=</span> <span class="st">"change"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">april_mobility</span></span>
<span><span class="co">#&gt; # A tibble: 60 × 3</span></span>
<span><span class="co">#&gt;    date       series                change</span></span>
<span><span class="co">#&gt;    &lt;date&gt;     &lt;chr&gt;                  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt;  1 2020-04-01 Retail and recreation    -23</span></span>
<span><span class="co">#&gt;  2 2020-04-01 Workplaces               -22</span></span>
<span><span class="co">#&gt;  3 2020-04-02 Retail and recreation    -25</span></span>
<span><span class="co">#&gt;  4 2020-04-02 Workplaces               -27</span></span>
<span><span class="co">#&gt;  5 2020-04-03 Retail and recreation    -21</span></span>
<span><span class="co">#&gt;  6 2020-04-03 Workplaces               -20</span></span>
<span><span class="co">#&gt;  7 2020-04-04 Retail and recreation    -24</span></span>
<span><span class="co">#&gt;  8 2020-04-04 Workplaces                -7</span></span>
<span><span class="co">#&gt;  9 2020-04-05 Retail and recreation    -23</span></span>
<span><span class="co">#&gt; 10 2020-04-05 Workplaces               -10</span></span>
<span><span class="co">#&gt; # ℹ 50 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Renaming inside <code>select()</code> is what gets you a readable legend without a second call. Backticks are needed around <code>Retail and recreation</code> because it contains spaces; R will accept a name like that as long as you quote it that way, and here it should be done, because that string goes straight onto the plot.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">april_mobility</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">date</span>, <span class="va">change</span>, colour <span class="op">=</span> <span class="va">series</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Reference line at zero, then one line per mobility series</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, colour <span class="op">=</span> <span class="va">nus_colours</span><span class="op">[[</span><span class="st">"muted"</span><span class="op">]</span><span class="op">]</span>, linewidth <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Circuit-breaker marker</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">cb_start</span>, colour <span class="op">=</span> <span class="va">nus_colours</span><span class="op">[[</span><span class="st">"crimson"</span><span class="op">]</span><span class="op">]</span>,</span>
<span>             linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Axis formatting: weekly date breaks</span></span>
<span>  <span class="fu">scale_x_date</span><span class="op">(</span>date_breaks <span class="op">=</span> <span class="st">"1 week"</span>, date_labels <span class="op">=</span> <span class="st">"%d %b"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Text: title states the finding; caption warns about the day-of-week baseline</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Movement fell the day the rules changed, and stayed down"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Percent change from Google's 3 January to 6 February 2020 baseline"</span>,</span>
<span>    x <span class="op">=</span> <span class="cn">NULL</span>, y <span class="op">=</span> <span class="st">"Change from baseline (%)"</span>, colour <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>    caption <span class="op">=</span> <span class="st">"Weekends are not comparable with weekdays: the baseline is a median by day of week."</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-april-mobility" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-april-mobility-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="capstone_files/figure-html/fig-april-mobility-1.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-april-mobility-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Retail and workplace mobility in April 2020, as percent change from Google’s pre-pandemic baseline.
</figcaption></figure>
</div>
</div>
</div>
<p>The step at 7 April is what the figure is for. Retail goes from 15% below baseline on 6 April to 51% below on 7 April; workplaces go from 24% below to 52% below on the same day. Behaviour changed within a day, while the case curve took a fortnight to turn.</p>
<p>Two features of that figure are not what they appear to be. The deep spike down to 83% below baseline is 10 April, which was Good Friday, a public holiday. The eight deepest workplace-mobility days in the entire year are all public holidays, so any dip you see in this series should be checked against a calendar before it is called a policy effect.</p>
<p>The regular bumps upwards are weekends, and they run the opposite way to intuition. Google’s baseline is a median computed separately for each day of the week, so a Sunday is compared with pre-pandemic Sundays. Workplace activity on a normal Sunday was already low, which leaves less room to fall.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">april</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">date</span> <span class="op">&gt;=</span> <span class="va">cb_start</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>weekday <span class="op">=</span> <span class="fu">wday</span><span class="op">(</span><span class="va">date</span>, label <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">weekday</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    days       <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>    workplaces <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">workplaces_percent_change_from_baseline</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 7 × 3</span></span>
<span><span class="co">#&gt;   weekday  days workplaces</span></span>
<span><span class="co">#&gt;   &lt;ord&gt;   &lt;int&gt;      &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Sun         3      -50  </span></span>
<span><span class="co">#&gt; 2 Mon         3      -66  </span></span>
<span><span class="co">#&gt; 3 Tue         4      -63  </span></span>
<span><span class="co">#&gt; 4 Wed         4      -66.5</span></span>
<span><span class="co">#&gt; 5 Thu         4      -67  </span></span>
<span><span class="co">#&gt; 6 Fri         3      -71.7</span></span>
<span><span class="co">#&gt; 7 Sat         3      -52.3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Weekdays sit between 63 and 72 points below baseline. Saturday and Sunday sit around 50. Workplace activity did not return at the weekend; the baseline it is compared against is lower.</p>
<p>If you want the two figures stacked as a single image for a one-page PDF, patchwork will do it with <code>p_cases / p_mobility</code> once you have assigned each plot to a name. They are kept separate here so that each keeps its full height on screen.</p>
</section><section id="the-three-sentences" class="level3" data-number="12.3.6"><h3 data-number="12.3.6" class="anchored" data-anchor-id="the-three-sentences">
<span class="header-section-number">12.3.6</span> The three sentences</h3>
<blockquote class="blockquote">
<p>April carried 15,243 reported cases, 26% of Singapore’s 2020 total, with 18 of its 30 days above 300 cases and 12 deaths; only May, at 18,715, was heavier.</p>
<p>Reported cases kept climbing for 13 days after the circuit breaker took effect on 7 April, peaking at 1,426 on 20 April, a pattern that reflects the pace of testing in the migrant-worker dormitories as much as the timing of infection.</p>
<p>Movement changed the day the rules did, with retail activity falling from 15% below baseline on 6 April to 51% below on 7 April and staying within a few points of its floor for the rest of the month, so the behavioural response was immediate even though the case curve was not.</p>
</blockquote>
<p>The three sentences do three different jobs. The first sizes the month against the year. The second addresses the point a reader would otherwise misread. The third brings in the second data source and sets the behavioural response against the case curve.</p>
<p>Two things are absent from these sentences. There is no recommendation, because nothing in this file supports one, and no claim that the circuit breaker did or did not work, because a single month of a single country with no counterfactual cannot establish either. The purpose of a situation report is description rather than causal inference.</p>
</section></section><section id="what-this-analysis-does-not-tell-you" class="level2" data-number="12.4"><h2 data-number="12.4" class="anchored" data-anchor-id="what-this-analysis-does-not-tell-you">
<span class="header-section-number">12.4</span> What this analysis does not tell you</h2>
<p>Write a version of this section for your own month, and make it specific to that month.</p>
<p><strong>Raw counts ignore population.</strong> Fifteen thousand cases is a number of people, not a rate. To turn it into a rate you need a denominator, and the appropriate denominator here is not obvious. Roughly 323,000 work-permit holders lived in dormitories of all types in 2020, of whom about 200,000 were in the 43 purpose-built dormitories. A case rate computed over the national population and a case rate computed over the dormitory-resident population are different quantities, and in April 2020 they were not close. This file gives you neither denominator.</p>
<p><strong>Raw counts ignore testing volume.</strong> A reported case requires a test, a positive result and a report. Change the number of tests and the case count changes without a single extra infection. There is no test-count column in this file, so you cannot compute test positivity, which is the standard way of asking whether a rise in cases reflects a rise in transmission or a rise in testing. A rising curve supports the statement that reported cases rose. It does not support the statement that infections rose.</p>
<p><strong>One national count is averaging two epidemics.</strong> From April to August 2020 the dormitory outbreak dominated Singapore’s case counts, and it had different dynamics from transmission in the wider community: different living density, different age structure, different testing regime, different intervention. MOH’s own daily updates reported those streams separately at the time. This file carries a single national total, so every mean you compute over those months is a weighted average of two processes, with weights you cannot see and that change from week to week. That is a limitation of the file, not of the epidemiology, and you should say which one you are reporting.</p>
<p>5 August 2020 is the clearest example. That day records 908 cases, against an August median of 91 and a next-highest August day of 313. Nine hundred and three of those 908 were dormitory residents, and 581 were linked to a single cluster at Acacia Lodge. MOH attributed the day’s numbers to clearance testing in dormitories picking up past infections. A mean that includes that day without comment describes a change in reporting as though it were a change in incidence.</p>
<p>One further point is flagged here as my own reading rather than something you can verify from the data. Google’s mobility series are built from location history on the phones of users who have that setting switched on, and Google does not publish these series broken down by nationality or work-permit status. Whether the movement of people confined to dormitories under quarantine appears in these curves at all is not a question this file can answer. I would not rely on the mobility series to describe what happened inside the dormitories in April. R will compute a mean of any column it is given; whether the column supports the question is a separate judgement.</p>
</section><section id="your-turn" class="level2" data-number="12.5"><h2 data-number="12.5" class="anchored" data-anchor-id="your-turn">
<span class="header-section-number">12.5</span> Your turn</h2>
<div id="exr-sitrep" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 12.1 (Write the August 2020 situation report)</strong></span> Produce the one-page report for August 2020: a table, two figures, three sentences of interpretation, and a short note on what your analysis does not tell you.</p>
<p>August is a harder month than April, even though the code is identical. What makes it harder is that the month contains a decision April does not, and the report has to address that decision explicitly.</p>
<p>You are done when someone who has never seen the data could read your page and come away with a correct impression of what August 2020 was like.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Stuck? Open for a hint (not the answer)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Compute the maximum, the median and the date of the maximum before you compute anything else, and put those three numbers next to each other. If a single day is several times the next highest day, the mean is describing that day rather than the month, and your report has to state explicitly what it does about that.</p>
</div>
</div>
</div>
<p><a href="../appendices/solutions.html#sec-sol-sitrep">Worked solution</a></p>
<p>If you want a second month after that, September 2020 is the quiet counterpart: 30 days, every one of them under 100 cases, a mean of 31.8. Reporting on a month in which little changed is a separate skill, and one that is required regularly.</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/cerm-nus\.github\.io\/r-intro\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
      for (let i=0; i<annoteTargets.length; i++) {
        const annoteTarget = annoteTargets[i];
        const targetCell = annoteTarget.getAttribute("data-target-cell");
        const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
        const contentFn = () => {
          const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          if (content) {
            const tipContent = content.cloneNode(true);
            tipContent.classList.add("code-annotation-tip-content");
            return tipContent.outerHTML;
          }
        }
        const config = {
          allowHTML: true,
          content: contentFn,
          onShow: (instance) => {
            selectCodeLines(instance.reference);
            instance.reference.classList.add('code-annotation-active');
            window.tippy.hideAll();
          },
          onHide: (instance) => {
            unselectCodeLines();
            instance.reference.classList.remove('code-annotation-active');
          },
          maxWidth: 300,
          delay: [50, 0],
          duration: [200, 0],
          offset: [5, 10],
          arrow: true,
          appendTo: function(el) {
            return el.parentElement.parentElement.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'quarto',
          placement: 'right',
          popperOptions: {
            modifiers: [
            {
              name: 'flip',
              options: {
                flipVariations: false, // true by default
                allowedAutoPlacements: ['right'],
                fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
              },
            },
            {
              name: 'preventOverflow',
              options: {
                mainAxis: false,
                altAxis: false
              }
            }
            ]        
          }      
        };
        window.tippy(annoteTarget, config); 
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../chapters/iteration.html" class="pagination-link" aria-label="Loops, and when you need them">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Loops, and when you need them</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/next-steps.html" class="pagination-link" aria-label="Where to go next">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Where to go next</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<div class="footer-logos">
<p><img class="logo-sshsph" src="../assets/logos/sshsph.png" alt="NUS Saw Swee Hock School of Public Health"><img class="logo-cerm" src="../assets/logos/cerm.png" alt="Centre for Epidemic Research and Modelling"><img class="logo-mlghn" src="../assets/logos/mlghn.png" alt="Machine Learning and Global Health Network"></p>
</div>
<p>Released under the <a href="https://github.com/CERM-NUS/r-intro/blob/main/LICENSE">MIT Licence</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/CERM-NUS/r-intro/edit/main/chapters/capstone.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/CERM-NUS/r-intro/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/CERM-NUS/r-intro/blob/main/chapters/capstone.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a>. <a href="https://github.com/CERM-NUS/r-intro/issues">Report a problem</a>.</p>
</div>
  </div>
</footer>


<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>