{
  "hash": "55145558e59304efe8ef9cfee3345489",
  "result": {
    "engine": "knitr",
    "markdown": "# Objects, vectors and functions {#sec-foundations}\n\n\n\n\n\n\n\n\n\nType `2 + 2` at the console and R prints `4`. Nothing of that calculation is kept, so nothing can be built on it. To work with 345 days of case counts, R has to store values under names, and you have to know what kind of value each name holds.\n\nThe second requirement is the one that causes trouble. R will let you put a word into a column of numbers without raising an error: it converts the numbers into text instead, and the mean of the column then comes back as `NA`. This chapter covers the vocabulary needed to diagnose that quickly.\n\nThe Singapore file is used throughout, so load it now. `read_covid()` is a small helper that ships with this book: it reads `data/sg_covid_data.csv` and hands back exactly what is in the file, with nothing cleaned and nothing repaired.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read_covid()\n```\n:::\n\n\n\n\n## Assignment {#sec-assignment}\n\nAssignment gives a value a name. R's assignment operator is a left-pointing arrow, made of a `<` and a `-`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_case <- as.Date(\"2020-01-23\")\nfirst_case\n#> [1] \"2020-01-23\"\n```\n:::\n\n\n\n\nTwo things happened. R evaluated the right-hand side, and it bound the result to the name `first_case`. Assignment produces no output; to see the value, type the name on its own line, as above.\n\nThat date is the first day this file records a confirmed case. Day one of the file, 22 January, has `confirmed` equal to zero.\n\nIn RStudio, `Alt` and minus (`Option` and minus on a Mac) types `<-` for you. The operator comes up constantly, so learn the shortcut early.\n\n### Why an arrow and not an equals sign\n\nR inherited `<-` from S, and S inherited it from APL, whose keyboards had a single key that produced a real `←` character. When S moved to keyboards without that key, the arrow was spelled out as two characters and stuck.\n\n`=` also works for assignment at the top level. This book does not use it, for one reason: inside a function call, `=` already means something else. In `round(x, digits = 2)` the `digits = 2` tells `round()` which of its arguments you are filling, and leaves no object called `digits` behind once the call has finished. Reserving `<-` for \"make an object\" and `=` for \"fill an argument\" keeps the two distinguishable when you read a line of code.\n\n### Naming things\n\nNames may contain letters, numbers, dots and underscores. They cannot start with a number, and they cannot contain spaces or hyphens. `daily_cases` is fine, `daily cases` is a syntax error, and `daily-cases` is read as `daily` minus `cases`.\n\nR is case sensitive. `Confirmed` and `confirmed` are different objects, and mixing them up produces one of the commonest error messages in R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovd\n#> Error:\n#> ! object 'covd' not found\n```\n:::\n\n\n\n\nWhen you see `object 'x' not found`, R has searched every environment on its search path and found no such name. The usual causes are a typo or a chunk that was never run.\n\nThis book uses `snake_case`: lower case, words joined by underscores. Tidyverse function and argument names follow the same convention, so a script written this way reads consistently from your objects through to the functions you call on them. Within that convention, a useful rule is nouns for data and verbs for functions: an object is named after what it is, so `covid` and `daily_cases` describe contents, while a function is named after what it does, so `read_covid()` and `mean()` describe actions. A reader who meets either kind of name in the middle of a script can then tell what to expect of it before finding where it was defined.\n\nSome names are best avoided entirely. `TRUE` and `FALSE` are reserved and cannot be reassigned, but their abbreviations `T` and `F` are ordinary variables. A line such as `T <- 0` early in a long script changes the meaning of every later `T`, so write `TRUE` and `FALSE` in full. A second group of names is best left alone because each is already a function: `c`, `data`, `mean` and `df` all have existing meanings. `df` in particular is the density function of the F distribution:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf(1, 2, 3)\n#> [1] 0.2788548\n```\n:::\n\n\n\n\nA data frame named `df` masks `stats::df()` on the search path. R can usually tell a function call from a variable and will resolve the reference correctly, but the name now has two meanings on the page, and code that looks `df` up as a value, such as passing it to another function, gets the data frame rather than the density. Choosing a noun that describes the contents avoids the collision entirely.\n\n## R has no scalars {#sec-vectors}\n\nR has no scalar type. What looks like a single number is a vector of length one, and much of R's behaviour follows from that.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_deaths <- 29\nlength(total_deaths)\n#> [1] 1\nlength(\"Singapore\")\n#> [1] 1\n```\n:::\n\n\n\n\nThe vector is the basic unit. `c()` (for *combine*) joins values into a longer one:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweek_one <- c(0, 1, 3, 3, 4, 5, 7)\nweek_one\n#> [1] 0 1 3 3 4 5 7\nlength(week_one)\n#> [1] 7\n```\n:::\n\n\n\n\nEvery column of the Singapore file is a vector of length 345. Pull one out with `$`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfirmed <- covid$confirmed\nlength(confirmed)\n#> [1] 345\nhead(confirmed, 10)\n#>  [1]  0  1  3  3  4  5  7  7 10 13\n```\n:::\n\n\n\n\nBecause the vector is the basic unit, arithmetic works on whole vectors at once. R does not need you to write a loop over 345 days.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(confirmed * 2, 10)\n#>  [1]  0  2  6  6  8 10 14 14 20 26\n```\n:::\n\n\n\n\nThis is called vectorisation, and it accounts for much of the brevity of R code for data analysis. A column of a table is a vector, so one line of arithmetic applies to all 345 days and the code never has to mention how many days there are. Without it, the same operation requires an explicit loop and an index to manage.\n\nThe same idea gives a useful quantity. The `confirmed` column is cumulative, a running total. The number of *new* cases on a given day is that day's total minus the previous day's. Shift the vector along by one, put a zero on the front so the lengths still match, and subtract:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# new cases are today's running total minus yesterday's, because confirmed is cumulative\nprevious_day <- c(0, confirmed[-length(confirmed)])\nnew_cases    <- confirmed - previous_day\nhead(new_cases, 10)\n#>  [1] 0 1 2 0 1 1 2 0 3 3\nmax(new_cases)\n#> [1] 1426\ncovid$date[which.max(new_cases)]\n#> [1] \"2020-04-20\"\n```\n:::\n\n\n\n\nThe peak is 1,426 new cases on 20 April 2020, during the dormitory outbreak. The comment above the chunk records why the subtraction is set up this way rather than what each line does; the code shows the what on its own, and a comment that merely repeats it is the first thing to go out of date as the code changes. The result can also be checked: the daily figures sum back to the final cumulative total.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(new_cases) == max(confirmed)\n#> [1] TRUE\n```\n:::\n\n\n\n\nThe zero on the front is not an arbitrary filler. The file starts on 22 January with `confirmed` equal to zero, so 22 January did have zero new cases. Writing that day as missing instead would drop a genuine day from every count made afterwards. `dplyr::lag()` does the same shift in one call, and `lag(confirmed, default = 0)` is where that zero goes; the version above is the same idea with the machinery visible.\n\n### Subsetting\n\nSquare brackets pick elements out by position, counting from 1 rather than 0.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfirmed[1]\n#> [1] 0\nconfirmed[1:5]\n#> [1] 0 1 3 3 4\nconfirmed[length(confirmed)]\n#> [1] 58599\n```\n:::\n\n\n\n\nA negative index means *everything except*, which is what `confirmed[-length(confirmed)]` did above: all of it bar the last day.\n\nYou can also subset with a logical vector, keeping the elements marked `TRUE`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid$date[new_cases > 1000]\n#> [1] \"2020-04-20\" \"2020-04-21\" \"2020-04-22\" \"2020-04-23\"\n```\n:::\n\n\n\n\nFour days in 2020 had more than a thousand new cases, and they run consecutively from 20 April. `dplyr::filter()` expresses the same operation more readably on a table, and underneath it does what this line does: build a logical vector, then retain the elements it marked `TRUE`.\n\n## Vector types and missing values {#sec-types}\n\nEvery vector has a type, and every element of a vector has the *same* type. Four types matter for data work:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(TRUE)\n#> [1] \"logical\"\ntypeof(2L)\n#> [1] \"integer\"\ntypeof(29)\n#> [1] \"double\"\ntypeof(\"Singapore\")\n#> [1] \"character\"\n```\n:::\n\n\n\n\nThe four types are logical, integer, double and character. (Two more exist, `complex` and `raw`, which are not needed for the material in this book.)\n\nInteger and double are both numbers, and R makes the distinction awkwardly. A number you type is a double unless you stick an `L` on the end. A colon range is an integer.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(1:5)\n#> [1] \"integer\"\ntypeof(5 / 2)\n#> [1] \"double\"\nidentical(1, 1L)\n#> [1] FALSE\n1 == 1L\n#> [1] TRUE\n```\n:::\n\n\n\n\n`identical()` reports that they are different objects; `==` reports that they hold the same value. Both are correct, and the distinction rarely matters in practice. What does matter is that doubles are stored in binary floating point, which cannot represent most decimal fractions exactly:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.1 + 0.2 == 0.3\n#> [1] FALSE\n0.1 + 0.2 - 0.3\n#> [1] 5.551115e-17\n```\n:::\n\n\n\n\nThis is not specific to R. Any language using IEEE 754 doubles behaves the same way, including spreadsheet software. Testing two calculated numbers with `==` is therefore unreliable; use `near()`, which allows a small tolerance:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear(0.1 + 0.2, 0.3)\n#> [1] TRUE\n```\n:::\n\n\n\n\nLogical values are `TRUE` and `FALSE`, and R treats them as 1 and 0 in arithmetic. A count of how many elements satisfy a condition is therefore `sum()` of the logical vector, and the proportion is `mean()` of it:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(covid$confirmed > 10000)\n#> [1] 254\nmean(covid$stringency_index > 50)\n#> [1] 0.5681159\n```\n:::\n\n\n\n\nThe count is 254 days of 2020 with more than ten thousand cumulative cases, and the stringency index was above 50 on 57% of days.\n\n### NA\n\n`NA` is R's marker for a value that should exist but is not recorded. It is not zero, not an empty string, and not a statement that the data are complete. Almost any operation involving an `NA` returns `NA`, because the result of that operation is unknown too.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA + 1\n#> [1] NA\nmean(c(1, 2, NA))\n#> [1] NA\n```\n:::\n\n\n\n\nThe propagation is deliberate: if one of three numbers is unknown, their mean is unknown as well, so R returns `NA` rather than averaging the two values it has.\n\nThe `deaths` column in this file makes it concrete. Singapore recorded no COVID-19 deaths for the first two months of the epidemic, and this file records those days as missing rather than as zero.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(covid$deaths, 12)\n#>  [1] NA NA NA NA NA NA NA NA NA NA NA NA\nsum(is.na(covid$deaths))\n#> [1] 59\nmean(covid$deaths)\n#> [1] NA\n```\n:::\n\n\n\n\nThere are 59 missing days, and so the mean of the column is `NA`. To get an answer you have to say explicitly that you are willing to ignore the gaps:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(covid$deaths, na.rm = TRUE)\n#> [1] 23.75874\n```\n:::\n\n\n\n\nWhether that is the right thing to do is a question about the deaths data, not about R. `na.rm = TRUE` drops the 59 unrecorded days and averages the 286 that remain, so the number returned is the mean of the days the source reported, which is not the mean of 2020. Which of the two you want depends on the question being asked, and the default behaviour at least requires the choice to be made explicitly.\n\nTwo more properties of `NA` come up in daily work. Testing it with `==` does not work, because \"an unknown value\" is not equal to anything, including another unknown value:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA == NA\n#> [1] NA\n```\n:::\n\n\n\n\nUse `is.na()` instead:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.na(c(1, NA, 3))\n#> [1] FALSE  TRUE FALSE\n```\n:::\n\n\n\n\n`NA` also comes in typed forms. Bare `NA` is logical; there are also `NA_integer_`, `NA_real_` and `NA_character_`, so that a missing value can sit inside a vector without changing its type. You rarely type these yourself, but you will see them in error messages.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(NA)\n#> [1] \"logical\"\ntypeof(NA_character_)\n#> [1] \"character\"\ntypeof(c(NA, 1))\n#> [1] \"double\"\n```\n:::\n\n\n\n\n## Coercion, or how a column of numbers becomes text {#sec-coercion}\n\nA vector holds one type, so combining two types forces R to choose one of them.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(1, \"a\")\n#> [1] \"1\" \"a\"\n```\n:::\n\n\n\n\nR issued no error or warning; it converted the number `1` into the string `\"1\"`, because that is the only way to hold both values in one vector. The rule runs one way only, from least to most flexible: logical values can be represented as integers, integers as doubles, and doubles as character strings, so a combination takes the type furthest along that sequence.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(c(TRUE, 1L))\n#> [1] \"integer\"\ntypeof(c(1L, 2.5))\n#> [1] \"double\"\ntypeof(c(2.5, \"Singapore\"))\n#> [1] \"character\"\n```\n:::\n\n\n\n\nNothing here is a bug, and no warning is issued at any step, which is why the conversion is easy to miss. Consider a spreadsheet of daily deaths in which one cell reads `\"not reported\"` instead of being left blank. That single cell turns the entire column to character on import, and then:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(c(\"1\", \"a\"))\n#> Warning in mean.default(c(\"1\", \"a\")): argument is not numeric or logical:\n#> returning NA\n#> [1] NA\n```\n:::\n\n\n\n\nThe warning is the useful part: `argument is not numeric or logical: returning NA`. When you see it, you have a character column that you thought was numeric. `typeof()` on the column confirms it in one line.\n\nGoing the other way is explicit, and R does warn:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.numeric(c(\"1\", \"a\"))\n#> Warning: NAs introduced by coercion\n#> [1]  1 NA\n```\n:::\n\n\n\n\n`NAs introduced by coercion` means R turned a value into `NA` because it could not parse it. Sometimes that is what you intended; sometimes it has removed a large part of the column. Count the missing values afterwards with `sum(is.na(x))` to find out which.\n\n## Recycling {#sec-recycling}\n\nWhen two vectors in an arithmetic expression have different lengths, R repeats the shorter one until it is long enough. You have already relied on this: in `confirmed * 2`, the `2` is a vector of length one and it got recycled 345 times.\n\nThat is the useful case. Recycling also applies when neither vector has length one, which is where it causes trouble.\n\n::: {.callout-important}\n## Predict before you run\n\n`c(1, 2, 3, 4) + c(10, 20)` produces a vector of length four. Write down the four numbers you expect, and whether you expect a warning. Then run it.\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(1, 2, 3, 4) + c(10, 20)\n#> [1] 11 22 13 24\n```\n:::\n\n\n\n\nNo warning was issued here: four is a multiple of two, so R recycled the shorter vector twice and reported nothing. Change the length to three and a warning appears:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(1, 2, 3) + c(10, 20)\n#> Warning in c(1, 2, 3) + c(10, 20): longer object length is not a multiple of\n#> shorter object length\n#> [1] 11 22 13\n```\n:::\n\n\n\n\n`longer object length is not a multiple of shorter object length` reports that the two vectors do not line up. The mechanism is the same in both cases; the warning appears only when the lengths are not multiples, not when the recycling is unintended. Checking `length()` on vectors before combining them is the reliable way to catch this.\n\n## Calling functions {#sec-calling-functions}\n\nA function has a name, takes arguments in brackets, and gives back a value. `mean(new_cases)` takes one argument and returns one number. Functions nest, and R works from the inside out:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(mean(new_cases), 2)\n#> [1] 169.85\nmedian(new_cases)\n#> [1] 40\n```\n:::\n\n\n\n\nA mean of 169.85 new cases a day against a median of 40 indicates a strongly right-skewed distribution, which matches the epidemic: most of 2020 had low daily counts, and a few weeks in April and May had very high ones.\n\nArguments can be given by position or by name. These three calls are identical:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(1, 10, 3)\n#> [1]  1  4  7 10\nseq(from = 1, to = 10, by = 3)\n#> [1]  1  4  7 10\nseq(by = 3, to = 10, from = 1)\n#> [1]  1  4  7 10\n```\n:::\n\n\n\n\nPosition only works if you remember the order. Names work regardless of order, and they record in the call itself which argument is being set. Pass the first argument or two positionally, since `mean(new_cases)` is unambiguous, and name everything after that.\n\nMost arguments have defaults, so you only supply the ones you want to change. `args()` shows you what they are:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nargs(round)\n#> function (x, digits = 0, ...) \n#> NULL\nargs(mean)\n#> function (x, ...) \n#> NULL\n```\n:::\n\n\n\n\n`round(x, digits = 0)` means that if you do not say otherwise, you get whole numbers. `mean(x, ...)` is less helpful, because `mean` is generic and the real arguments live in the method; this is one of the places where R's help page tells you more than the code does.\n\n`round()` has one behaviour to watch for:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(0.5)\n#> [1] 0\nround(1.5)\n#> [1] 2\nround(2.5)\n#> [1] 2\n```\n:::\n\n\n\n\n`round(0.5)` is 0 and `round(1.5)` is 2. R rounds halves to the nearest even number rather than upward, following the IEC 60559 standard, so that rounding a long column of values does not accumulate an upward bias. `?round` documents this. The behaviour is intended, and it can still surprise someone checking totals by hand.\n\n### Reading a help page\n\nEvery function in R ships with documentation. A question mark opens it:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n?mean\nhelp(\"mean\")\n```\n:::\n\n\n\n\nIf you do not know the name, two question marks searches the text of every installed help page:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n??\"standard deviation\"\n```\n:::\n\n\n\n\nHelp pages have a fixed structure, and reading them from top to bottom is rarely the quickest route. A more efficient order begins with the Usage section, which shows the function signature with every default filled in, so you can see what may be passed. From there, read only the two or three entries in Arguments that are relevant to the call you are writing. The Examples at the bottom of the page are runnable, and `example(mean)` runs them without opening the page; they are often the fastest way to see the function used correctly. The Details section matters most when something has already gone wrong, since that is where behaviour such as the rounding rule above is described, and the Value section settles what type the function returns, which is more often useful than it first appears.\n\nTidyverse functions carry the same documentation, typeset more legibly at <https://tidyverse.org>. Base R help pages are frequently terse, and much of that documentation was written for specialists rather than beginners. Searching for the function name plus \"r\" will usually find explanations in more ordinary language.\n\n## Packages and where functions live {#sec-packages}\n\nR ships with a few thousand functions. Everything else lives in packages: bundles of functions, documentation and sometimes data, written by other people and published on CRAN.\n\nInstalling is a one-off, per machine. It downloads and compiles code onto your hard disk.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")\n```\n:::\n\n\n\n\nLoading is per session. It takes an installed package and makes its functions available by name.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n\n\nThe distinction matters in practice. `install.packages()` belongs at the console, typed by hand, and not in a script; running it on every render costs minutes and requires an internet connection. `library()` belongs at the top of every script, because a script that does not load the packages it uses will fail on any machine where those packages are not already attached. The quotation marks are required by one and not the other, which is an inconsistency in R rather than a mistake on your part.\n\n### The masking message\n\n`library(tidyverse)` prints a block of text when it loads. Read it.\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\nLoading dplyr on its own reports the same thing in more detail:\n\n```\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union\n```\n\nNothing has broken, and the mechanism behind the message is the search path: R keeps an ordered list of the places it looks for a name.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(search(), 15)\n#>  [1] \".GlobalEnv\"        \"package:scales\"    \"package:patchwork\"\n#>  [4] \"package:here\"      \"package:lubridate\" \"package:forcats\"  \n#>  [7] \"package:stringr\"   \"package:dplyr\"     \"package:purrr\"    \n#> [10] \"package:readr\"     \"package:tidyr\"     \"package:tibble\"   \n#> [13] \"package:ggplot2\"   \"package:tidyverse\" \"package:stats\"\n```\n:::\n\n\n\n\nWhen you type `filter(...)`, R walks that list from left to right and uses the first `filter` it finds. Every package you attach is inserted near the front, so a newly loaded package wins against anything loaded before it. `package:dplyr` sits ahead of `package:stats`, so `filter` means dplyr's.\n\n`stats::filter` has not been deleted, and you can still reach it by giving its full address. The double colon means \"the function called `filter` from the package called `stats`, regardless of the search path\":\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(round(stats::filter(covid$confirmed, rep(1/7, 7)), 1), 10)\n#>  [1]   NA   NA   NA  3.3  4.3  5.6  7.0  8.9 10.9 12.7\n```\n:::\n\n\n\n\nThat is a seven-day moving average of the cumulative curve, which is the job `stats::filter()` does. It returns a time series object, hence the header lines about start, end and frequency, and the first three values are `NA` because a seven-day window cannot be centred on day one. None of this has anything to do with selecting rows from a table:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndplyr::filter(covid, stringency_index > 80)$date\n#> [1] \"2020-04-10\" \"2020-04-25\" \"2020-05-01\"\n```\n:::\n\n\n\n\nTwo functions share a name and do unrelated jobs. The conflicts message exists so that the collision is visible when the package is attached, rather than later when a result looks wrong.\n\nThe same applies to `lag()`. `dplyr::lag()` shifts a vector along by one position, which is exactly what you did by hand earlier. `stats::lag()` shifts a time series' *index* and leaves the values alone. If you ever compute daily cases and get a column of zeroes, this is why.\n\nThis is also why `library()` goes at the top of a script. If dplyr has not been loaded and you call `filter()` on a data frame, the call reaches `stats::filter`, and the resulting error does not point at the missing `library()` line.\n\n```\nError: object 'confirmed' not found\n```\n\n`stats::filter()` has no idea that `confirmed` is a column of the thing you handed it, so it tries to find an object by that name and fails. The fix is a `library(dplyr)` or `library(tidyverse)` line you left out, and the error message does not say so.\n\nWriting `dplyr::filter()` in full removes the ambiguity, at the cost of a package prefix on every call. It earns that cost in code you distribute, where the reader may have a different set of packages attached. For everyday analysis, load the package and read the conflicts message; if you would prefer collisions to raise an error instead of being resolved by precedence, the `conflicted` package does that.\n\n## Exercise\n\n::: {#exr-vectors}\n## Build a week by hand\n\nThe first seven cumulative confirmed counts in the file are 0, 1, 3, 3, 4, 5 and 7.\n\n1. Store them in a vector called `week_one` and confirm that R agrees it has seven elements and holds doubles.\n2. Work out how many new cases were recorded on each of days two to seven, using only subsetting and subtraction.\n3. Add the label `\"week one\"` to the front of `week_one`, look at the type again, and then try to multiply the result by two. Explain in one sentence what R did to your numbers and why the arithmetic now fails.\n4. Make a copy of `week_one` with the fourth element replaced by `NA`, then find its mean twice, once as R gives it to you and once telling `mean()` to drop the missing value.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\nFor part 2, two vectors of the same length subtract element by element, so you need one vector holding days two to seven and another holding days one to six. For part 3, look at `typeof()` before and after.\n:::\n\n[Worked solution](../appendices/solutions.qmd#sec-sol-vectors)\n",
    "supporting": [
      "foundations_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}