{
  "hash": "9783e9f622afbf74fb64e7b752fcf130",
  "result": {
    "engine": "knitr",
    "markdown": "# Objects, vectors and functions {#sec-foundations}\n\n\n\nType `2 + 2` at the console and R prints `4`. Type it again and R prints `4` again. Nothing has been kept, and nothing can be built on. Before you can do anything with 345 days of case counts, R has to hold on to things and give them names, and you have to know what kind of thing it is holding.\n\nThat last part is where beginners lose whole evenings. R will happily let you put a word into a column of numbers, and it will not shout. It will convert the numbers into words instead, and then your average comes back as `NA` and you have no idea why. This chapter is mostly about giving you the vocabulary to diagnose that in ten seconds rather than an hour.\n\nThe Singapore file is used throughout, so load it now. `read_covid()` is a small helper that ships with this book: it reads `data/sg_covid_data.csv` and hands back exactly what is in the file, with nothing cleaned and nothing repaired.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read_covid()\n```\n:::\n\n\n## Making R keep something {#sec-assignment}\n\nAssignment gives a value a name. R's assignment operator is a left-pointing arrow, made of a `<` and a `-`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_case <- as.Date(\"2020-01-23\")\nfirst_case\n#> [1] \"2020-01-23\"\n```\n:::\n\n\nTwo things happened. R evaluated the right-hand side, and it bound the result to the name `first_case`. Assignment produces no output, which surprises people; if you want to see the value, type the name on its own line, as above.\n\nThat date is the first day this file records a confirmed case. Day one of the file, 22 January, has `confirmed` equal to zero.\n\nIn RStudio, `Alt` and minus (`Option` and minus on a Mac) types `<-` for you. Learn it early; you will type this operator thousands of times.\n\n### Why an arrow and not an equals sign\n\nR inherited `<-` from S, and S inherited it from APL, whose keyboards had a single key that produced a real `←` character. When S moved to keyboards without that key, the arrow was spelled out as two characters and stuck.\n\n`=` also works for assignment at the top level. This book does not use it, for one reason: inside a function call, `=` already means something else. In `round(x, digits = 2)` the `digits = 2` is not creating an object called `digits`. It is telling `round()` which argument you are filling. Keeping `<-` for \"make an object\" and `=` for \"fill an argument\" means you can read a line of code and know which is happening without thinking about it.\n\n### Naming things\n\nNames may contain letters, numbers, dots and underscores. They cannot start with a number, and they cannot contain spaces or hyphens. `daily_cases` is fine, `daily cases` is a syntax error, and `daily-cases` is read as `daily` minus `cases`.\n\nR is case sensitive. `Confirmed` and `confirmed` are different objects, and mixing them up produces the single most common error message in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovd\n#> Error:\n#> ! object 'covd' not found\n```\n:::\n\n\nWhen you see `object 'x' not found`, R is telling you it looked everywhere it knows about and there is no such name. Nine times out of ten it is a typo or a chunk you never ran.\n\nThis book uses `snake_case`: lower case, words joined by underscores. The tidyverse does the same, so your code will look like the code around it.\n\nTwo names to avoid. `TRUE` and `FALSE` are reserved and cannot be reassigned, but their abbreviations `T` and `F` are ordinary variables. Someone who writes `T <- 0` early in a long script has quietly redefined truth for everything that follows. Write `TRUE` and `FALSE` in full. Similarly, avoid naming your own objects `c`, `data`, `mean` or `df`; R will usually cope, but you will confuse yourself.\n\n## R has no scalars {#sec-vectors}\n\nHere is the fact that makes the rest of R make sense. There is no such thing in R as a single number. What looks like one is a vector of length one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_deaths <- 29\nlength(total_deaths)\n#> [1] 1\nlength(\"Singapore\")\n#> [1] 1\n```\n:::\n\n\nThe vector is the atom. `c()` (for *combine*) glues values into a longer one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweek_one <- c(0, 1, 3, 3, 4, 5, 7)\nweek_one\n#> [1] 0 1 3 3 4 5 7\nlength(week_one)\n#> [1] 7\n```\n:::\n\n\nEvery column of the Singapore file is a vector of length 345. Pull one out with `$`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfirmed <- covid$confirmed\nlength(confirmed)\n#> [1] 345\nhead(confirmed, 10)\n#>  [1]  0  1  3  3  4  5  7  7 10 13\n```\n:::\n\n\nBecause vectors are the atom, arithmetic works on whole vectors at once. R does not need you to write a loop over 345 days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(confirmed * 2, 10)\n#>  [1]  0  2  6  6  8 10 14 14 20 26\n```\n:::\n\n\nThis is called vectorisation, and it is the reason R code for data analysis is short. A column of a table is a vector, so one line of arithmetic lands on all 345 days at once and the code never has to mention how many days there are. In a language without it you would be writing a loop, a counter, and eventually an off-by-one error.\n\nHere is the same idea doing something useful. The `confirmed` column is cumulative, a running total. The number of *new* cases on a given day is that day's total minus the previous day's. Shift the vector along by one, stick a zero on the front so the lengths still match, and subtract:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprevious_day <- c(0, confirmed[-length(confirmed)])\nnew_cases    <- confirmed - previous_day\nhead(new_cases, 10)\n#>  [1] 0 1 2 0 1 1 2 0 3 3\nmax(new_cases)\n#> [1] 1426\ncovid$date[which.max(new_cases)]\n#> [1] \"2020-04-20\"\n```\n:::\n\n\n1,426 new cases on 20 April 2020, the peak of the dormitory outbreak. Three lines, no loop, and the answer is right: the new cases add back up to the final total.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(new_cases) == max(confirmed)\n#> [1] TRUE\n```\n:::\n\n\nThe zero on the front is doing real work there, and it is not a fudge. The file starts on 22 January with `confirmed` equal to zero, so 22 January really did have zero new cases. Writing that day as missing instead would drop a genuine day from every count you make afterwards. `dplyr::lag()` does the same shift in one call, and `lag(confirmed, default = 0)` is where that zero goes; the version above is the same idea with the machinery visible.\n\n### Subsetting\n\nSquare brackets pick elements out by position, counting from 1 rather than 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfirmed[1]\n#> [1] 0\nconfirmed[1:5]\n#> [1] 0 1 3 3 4\nconfirmed[length(confirmed)]\n#> [1] 58599\n```\n:::\n\n\nA negative index means *everything except*, which is what `confirmed[-length(confirmed)]` did above: all of it bar the last day.\n\nYou can also subset with a logical vector, which is where this starts to pay off:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid$date[new_cases > 1000]\n#> [1] \"2020-04-20\" \"2020-04-21\" \"2020-04-22\" \"2020-04-23\"\n```\n:::\n\n\nFour days in 2020 with more than a thousand new cases, and they run consecutively from 20 April. `dplyr::filter()` says the same thing more readably, and underneath it is doing exactly this: building a logical vector, then keeping the elements it marked `TRUE`.\n\n## Four types, and one absence {#sec-types}\n\nEvery vector has a type, and every element of a vector has the *same* type. Four types matter for data work:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(TRUE)\n#> [1] \"logical\"\ntypeof(2L)\n#> [1] \"integer\"\ntypeof(29)\n#> [1] \"double\"\ntypeof(\"Singapore\")\n#> [1] \"character\"\n```\n:::\n\n\nLogical, integer, double, character. (There are two more, `complex` and `raw`. You can ignore them for the whole of your career unless you go looking.)\n\nInteger and double are both numbers, and R makes the distinction awkwardly. A number you type is a double unless you stick an `L` on the end. A colon range is an integer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(1:5)\n#> [1] \"integer\"\ntypeof(5 / 2)\n#> [1] \"double\"\nidentical(1, 1L)\n#> [1] FALSE\n1 == 1L\n#> [1] TRUE\n```\n:::\n\n\n`identical()` says they are different objects; `==` says they are the same value. Both are correct, and in practice you almost never need to care. Where it bites is that doubles are stored in binary floating point, which cannot represent most decimal fractions exactly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.1 + 0.2 == 0.3\n#> [1] FALSE\n0.1 + 0.2 - 0.3\n#> [1] 5.551115e-17\n```\n:::\n\n\nThat is not R being broken. Every language using IEEE 754 doubles does this, including the spreadsheet on your other screen. Never test two calculated numbers with `==`. Use `near()`, which allows a tiny tolerance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear(0.1 + 0.2, 0.3)\n#> [1] TRUE\n```\n:::\n\n\nLogical values are `TRUE` and `FALSE`, and R treats them as 1 and 0 when you do arithmetic on them. That small fact turns \"how many\" and \"what proportion\" into `sum()` and `mean()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(covid$confirmed > 10000)\n#> [1] 254\nmean(covid$stringency_index > 50)\n#> [1] 0.5681159\n```\n:::\n\n\n254 days of 2020 with more than ten thousand cumulative cases, and the stringency index was above 50 on 57% of days.\n\n### NA\n\n`NA` is R's marker for a value that should exist but is not recorded. It is not zero, not an empty string, and not \"the data is fine\". It is an admission of ignorance, and R takes it seriously: almost anything you do with an `NA` gives you `NA` back, because R refuses to guess.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA + 1\n#> [1] NA\nmean(c(1, 2, NA))\n#> [1] NA\n```\n:::\n\n\nThat propagation is the point. If you do not know one of three numbers, you do not know their mean, and R would rather tell you so than quietly average the two it has.\n\nThe `deaths` column in this file makes it concrete. Singapore recorded no COVID-19 deaths for the first two months of the epidemic, and this file records those days as missing rather than as zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(covid$deaths, 12)\n#>  [1] NA NA NA NA NA NA NA NA NA NA NA NA\nsum(is.na(covid$deaths))\n#> [1] 59\nmean(covid$deaths)\n#> [1] NA\n```\n:::\n\n\n59 missing days, and so the mean of the column is `NA`. To get an answer you have to say explicitly that you are willing to ignore the gaps:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(covid$deaths, na.rm = TRUE)\n#> [1] 23.75874\n```\n:::\n\n\nWhether that is the right thing to do is a question about deaths, not about R. `na.rm = TRUE` drops the 59 unrecorded days and averages the 286 that remain, so the number you get is the mean of the days the source reported, which is not the mean of 2020. Only you can say which of those you wanted. What matters here is that R made you ask.\n\nTwo more things about `NA`. Testing it with `==` does not work, because \"an unknown value\" is not equal to anything, including another unknown value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNA == NA\n#> [1] NA\n```\n:::\n\n\nUse `is.na()` instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.na(c(1, NA, 3))\n#> [1] FALSE  TRUE FALSE\n```\n:::\n\n\nAnd `NA` has flavours. Bare `NA` is logical; there are also `NA_integer_`, `NA_real_` and `NA_character_`, so that a missing value can sit inside a vector without changing its type. You rarely type these yourself, but you will see them in error messages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(NA)\n#> [1] \"logical\"\ntypeof(NA_character_)\n#> [1] \"character\"\ntypeof(c(NA, 1))\n#> [1] \"double\"\n```\n:::\n\n\n## Coercion, or how a column of numbers becomes text {#sec-coercion}\n\nA vector holds one type. So what happens when you combine two types?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(1, \"a\")\n#> [1] \"1\" \"a\"\n```\n:::\n\n\nR did not complain. It quietly converted the number `1` into the string `\"1\"`, because that is the only way to keep everything in one vector. The rule runs one way only, from least to most flexible: logical becomes integer becomes double becomes character.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypeof(c(TRUE, 1L))\n#> [1] \"integer\"\ntypeof(c(1L, 2.5))\n#> [1] \"double\"\ntypeof(c(2.5, \"Singapore\"))\n#> [1] \"character\"\n```\n:::\n\n\nNothing here is a bug, and no warning is issued at any step. That is exactly why it costs people an evening. Picture a spreadsheet of daily deaths where one cell says `\"not reported\"` instead of being left blank. That single cell turns the entire column to character on import, and then:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(c(\"1\", \"a\"))\n#> Warning in mean.default(c(\"1\", \"a\")): argument is not numeric or logical:\n#> returning NA\n#> [1] NA\n```\n:::\n\n\nThe warning is the useful part: `argument is not numeric or logical: returning NA`. When you see it, you have a character column that you thought was numeric. `typeof()` on the column confirms it in one line.\n\nGoing the other way is explicit, and R does warn:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.numeric(c(\"1\", \"a\"))\n#> Warning: NAs introduced by coercion\n#> [1]  1 NA\n```\n:::\n\n\n`NAs introduced by coercion` means R turned something into `NA` because it could not parse it. Sometimes that is what you wanted. Sometimes it has just deleted a fifth of your data. Always check how many `NA`s appeared.\n\n## Recycling {#sec-recycling}\n\nWhen two vectors in an arithmetic expression have different lengths, R repeats the shorter one until it is long enough. You have already relied on this: in `confirmed * 2`, the `2` is a vector of length one and it got recycled 345 times.\n\nThat is the useful case. Here is the other one.\n\n::: {.callout-important}\n## Predict before you run\n\n`c(1, 2, 3, 4) + c(10, 20)` produces a vector of length four. Write down the four numbers you expect, and whether you expect a warning. Then run it.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(1, 2, 3, 4) + c(10, 20)\n#> [1] 11 22 13 24\n```\n:::\n\n\nNo warning at all. Four divides by two, so R considered the recycling clean and said nothing. Change the length to three and it does speak up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(1, 2, 3) + c(10, 20)\n#> Warning in c(1, 2, 3) + c(10, 20): longer object length is not a multiple of\n#> shorter object length\n#> [1] 11 22 13\n```\n:::\n\n\n`longer object length is not a multiple of shorter object length` is R telling you your two vectors do not line up. It is the same silent mechanism either way, and the warning only appears when the arithmetic is untidy, not when it is wrong. This is why `length()` is worth running on anything you are about to combine.\n\n## Calling functions {#sec-functions}\n\nA function has a name, takes arguments in brackets, and gives back a value. `mean(new_cases)` takes one argument and returns one number. Functions nest, and R works from the inside out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(mean(new_cases), 2)\n#> [1] 169.85\nmedian(new_cases)\n#> [1] 40\n```\n:::\n\n\nA mean of 169.85 new cases a day against a median of 40 tells you the distribution is badly skewed, which for this epidemic it is: most of 2020 was quiet, and a few weeks in April and May were not.\n\nArguments can be given by position or by name. These three calls are identical:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq(1, 10, 3)\n#> [1]  1  4  7 10\nseq(from = 1, to = 10, by = 3)\n#> [1]  1  4  7 10\nseq(by = 3, to = 10, from = 1)\n#> [1]  1  4  7 10\n```\n:::\n\n\nPosition only works if you remember the order. Names work regardless, and they document the call for whoever reads it next, including you in three weeks. The convention most people settle on is to pass the first argument or two positionally, because `mean(new_cases)` is perfectly clear, and to name everything after that.\n\nMost arguments have defaults, so you only supply the ones you want to change. `args()` shows you what they are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nargs(round)\n#> function (x, digits = 0, ...) \n#> NULL\nargs(mean)\n#> function (x, ...) \n#> NULL\n```\n:::\n\n\n`round(x, digits = 0)` means that if you do not say otherwise, you get whole numbers. `mean(x, ...)` is less helpful, because `mean` is generic and the real arguments live in the method; this is one of the places where R's help page tells you more than the code does.\n\nWhile we are here, `round()` has an oddity that catches people out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(0.5)\n#> [1] 0\nround(1.5)\n#> [1] 2\nround(2.5)\n#> [1] 2\n```\n:::\n\n\n`round(0.5)` is 0 and `round(1.5)` is 2. R rounds halves to the nearest even number rather than always upward, following the IEC 60559 standard, so that rounding a long column of values does not drift upward. `?round` says so explicitly. It is documented behaviour, not a bug, and it will still confuse a colleague checking your totals by hand.\n\n### Reading a help page\n\nEvery function in R ships with documentation. A question mark opens it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n?mean\nhelp(\"mean\")\n```\n:::\n\n\nIf you do not know the name, two question marks searches the text of every installed help page:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n??\"standard deviation\"\n```\n:::\n\n\nHelp pages have a fixed shape, and reading them in order is a waste of time. Read them in this order instead.\n\n**Usage** first. It shows the function signature with every default filled in, so you can see at a glance what you are allowed to pass. **Arguments** second, but only the two or three you care about. **Examples**, at the very bottom, third and often most useful; they are runnable, and `example(mean)` runs them for you. **Details** only when something has already gone wrong, because that is where the awkward truths live, including the rounding rule above. **Value** when you are unsure what type comes back, which matters more than beginners expect.\n\nTidyverse functions carry the same documentation, typeset more kindly at <https://tidyverse.org>. If a help page is impenetrable, that is normal rather than a sign you are slow. Much of base R's documentation was written for statisticians in the 1990s and reads that way. Search for the function name plus \"r\" and you will find people explaining it to each other in ordinary language.\n\n## Packages and where functions live {#sec-packages}\n\nR ships with a few thousand functions. Everything else lives in packages: bundles of functions, documentation and sometimes data, written by other people and published on CRAN.\n\nInstalling is a one-off, per machine. It downloads and compiles code onto your hard disk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")\n```\n:::\n\n\nLoading is per session. It takes an installed package and makes its functions available by name.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nThe distinction trips up everyone once. `install.packages()` belongs at the console, typed by hand, and should never sit in a script; running it on every render wastes minutes and needs the internet. `library()` belongs at the top of every script, because a script that does not load what it uses will not run on anyone else's machine, including yours next month. The quotation marks go on one and not the other, which is an inconsistency in R and not something you did wrong.\n\n### The masking message\n\nThe first time you ran `library(tidyverse)` you got a wall of text. Read it rather than scrolling past it.\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\nLoad dplyr on its own and it says the same thing more bluntly:\n\n```\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union\n```\n\nNothing has broken. Here is the mechanism. R keeps an ordered list of places to look for a name, called the search path:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(search(), 15)\n#>  [1] \".GlobalEnv\"        \"package:scales\"    \"package:patchwork\"\n#>  [4] \"package:here\"      \"package:lubridate\" \"package:forcats\"  \n#>  [7] \"package:stringr\"   \"package:dplyr\"     \"package:purrr\"    \n#> [10] \"package:readr\"     \"package:tidyr\"     \"package:tibble\"   \n#> [13] \"package:ggplot2\"   \"package:tidyverse\" \"package:stats\"\n```\n:::\n\n\nWhen you type `filter(...)`, R walks that list from left to right and uses the first `filter` it finds. Every package you attach is inserted near the front, so a newly loaded package wins against anything loaded before it. `package:dplyr` sits ahead of `package:stats`, so `filter` means dplyr's.\n\n`stats::filter` has not been deleted, and you can still reach it by giving its full address. The double colon means \"the function called `filter` from the package called `stats`, regardless of the search path\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(round(stats::filter(covid$confirmed, rep(1/7, 7)), 1), 10)\n#> Time Series:\n#> Start = 1 \n#> End = 10 \n#> Frequency = 1 \n#>  [1]   NA   NA   NA  3.3  4.3  5.6  7.0  8.9 10.9 12.7\n```\n:::\n\n\nThat is a seven-day moving average of the cumulative curve, which is what `stats::filter()` is for. It returns a time series object, hence the header lines about start, end and frequency, and the first three values are `NA` because a seven-day window cannot be centred on day one. None of it has anything to do with picking rows out of a table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndplyr::filter(covid, stringency_index > 80)$date\n#> [1] \"2020-04-10\" \"2020-04-25\" \"2020-05-01\"\n```\n:::\n\n\nTwo functions, one name, completely different jobs. The message exists so that you find out about the collision when you load the package rather than three hours later when a result looks wrong.\n\nThe same applies to `lag()`. `dplyr::lag()` shifts a vector along by one position, which is exactly what you did by hand earlier. `stats::lag()` shifts a time series' *index* and leaves the values alone. If you ever compute daily cases and get a column of zeroes, this is why.\n\nThe practical consequence, and the reason `library()` goes at the top of a script: if you forget to load dplyr and call `filter()` on a data frame, you get `stats::filter`, and the error tells you nothing about the real problem.\n\n```\nError: object 'confirmed' not found\n```\n\n`stats::filter()` has no idea that `confirmed` is a column of the thing you handed it, so it tries to find an object by that name and fails. The fix is a `library(dplyr)` or `library(tidyverse)` line you left out, and the error message does not say so.\n\nYou can sidestep the whole business by writing `dplyr::filter()` in full. That is worth doing in a function you are shipping to other people, and it is too noisy for everyday analysis. Load the package, read the conflicts message, and if you want the collisions to become hard errors instead of quiet precedence, the `conflicted` package does that.\n\n## Exercise\n\n::: {#exr-vectors}\n## Build a week by hand\n\nThe first seven cumulative confirmed counts in the file are 0, 1, 3, 3, 4, 5 and 7.\n\n1. Store them in a vector called `week_one` and confirm that R agrees it has seven elements and holds doubles.\n2. Work out how many new cases were recorded on each of days two to seven, using only subsetting and subtraction.\n3. Add the label `\"week one\"` to the front of `week_one`, look at the type again, and then try to multiply the result by two. Explain in one sentence what R did to your numbers and why the arithmetic now fails.\n4. Make a copy of `week_one` with the fourth element replaced by `NA`, then find its mean twice, once as R gives it to you and once telling `mean()` to drop the missing value.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\nFor part 2, two vectors of the same length subtract element by element, so you need one vector holding days two to seven and another holding days one to six. For part 3, look at `typeof()` before and after.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-vectors)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}