{
  "hash": "77e4b06027183ac0ba8d92df9039e6e9",
  "result": {
    "engine": "knitr",
    "markdown": "# Loops, and when you need them {#sec-iteration}\n\n\n\n\n\nMost introductions to the tidyverse skip loops, or mention them once with an apology. This one does not, and the reason is on your timetable. Later in this course you will build compartmental models, and a compartmental model is a loop: the state of the epidemic tomorrow is computed from the state today, and there is no dplyr verb that expresses that. If your only tool is `mutate()`, you will be stuck.\n\nSo we do it in the awkward order. Write the loop first, watch it work, then see the one-liner that replaces it, and understand what you gained and what you gave up.\n\n## The loop the worksheet asked for\n\n`confirmed` in this dataset is cumulative. On 31 December it reads 58,599, which is every case Singapore recorded in 2020, not the number recorded that day. To get daily cases you take each value and subtract the one before it.\n\nWritten as a loop, that is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily <- numeric(nrow(covid))\n\nfor (i in seq_along(daily)) {\n  if (i == 1) {\n    daily[i] <- covid$confirmed[i]\n  } else {\n    daily[i] <- covid$confirmed[i] - covid$confirmed[i - 1]\n  }\n}\n\nhead(daily, 8)\n#> [1] 0 1 2 0 1 1 2 0\n```\n:::\n\n\nRead it slowly, because every piece is doing something.\n\n`daily <- numeric(nrow(covid))` creates the answer *before* filling it: a vector of 345 zeros, ready to be overwritten. `for (i in seq_along(daily))` runs the body once for each position, with `i` taking the values 1, 2, 3 and so on. The `if (i == 1)` branch exists because there is no day before the first one, so `covid$confirmed[0]` would give you nothing at all rather than a zero. And on day one the answer is `confirmed[1]`, which in this dataset is 0, because Singapore's first record on 22 January had a cumulative count of zero. That day really did have no new cases. It is not missing.\n\nThe result: 0, 1, 2, 0, 1, 1, 2, 0. Small numbers in a country that had not yet noticed what was coming.\n\n## The one-liner\n\nEverything above is one `mutate()` call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvectorised <- covid %>%\n  mutate(daily_cases_v = confirmed - lag(confirmed, default = 0)) %>%\n  pull(daily_cases_v)\n\nhead(vectorised, 8)\n#> [1] 0 1 2 0 1 1 2 0\n```\n:::\n\n\n`lag()` shifts a vector down by one position, so `lag(confirmed)` on day `i` is `confirmed` on day `i - 1`. The whole subtraction happens at once, across all 345 rows, with no index variable anywhere. `default = 0` is what replaces the `if (i == 1)` branch: it says what to use where there is no previous value, and 0 is right here for the reason given above. Leave the default out and day one becomes `NA`, which propagates into every count and every plot downstream.\n\nSame numbers? Do not take my word for it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentical(daily, vectorised)\n#> [1] TRUE\n```\n:::\n\n\n`identical()` is the strict comparison. It checks length, type and every element, and it returns a single `TRUE` or `FALSE` with no tolerance for rounding and no recycling. Use it when you want a yes-or-no answer about whether two objects are the same thing. (`all.equal()` is its forgiving cousin, which allows tiny floating-point differences and returns a *message* rather than `FALSE` when things differ, which trips people up inside `if`.)\n\nAnd both agree with the column `covid_daily()` built for you:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentical(daily, covid$daily_cases)\n#> [1] TRUE\n```\n:::\n\n\n## Being fair to the loop\n\nThe loop is eight lines and the `mutate()` is one. The loop has three places to get an index wrong: `seq_along(daily)`, `covid$confirmed[i]` and `covid$confirmed[i - 1]`. Get the last one wrong by writing `i + 1` and R will happily run it, hand you `NA` in the final position, and say nothing. The vectorised version has no indices at all, so it cannot have index bugs.\n\nThat is a real advantage and it is why the tidyverse exists. But the loop buys you two things the one-liner cannot.\n\nThe first is that you can see every step. `lag()` is a black box until you have written the shift yourself; once you have, it stops being magic.\n\nThe second is that you can stop it and look around. Put `browser()` inside the body and R drops you into an interactive prompt at that iteration, with `i` and every other local variable available to inspect:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in seq_along(daily)) {\n  if (i == 60) browser()          # stop on the 60th day and look\n  daily[i] <- covid$confirmed[i] - covid$confirmed[max(i - 1, 1)]\n}\n```\n:::\n\n\nType `n` to run the next line, `c` to continue, `Q` to quit. There is no equivalent for a `mutate()` that is wrong in the middle. When a vectorised calculation gives you a number you cannot explain, rewriting it as a loop and stepping through it is often the fastest way to find out why.\n\nThe rule most people settle on: reach for the vectorised version by default, and write the loop when the calculation is sequential or when you need to watch it happen.\n\n## Pre-allocate\n\n`daily <- numeric(nrow(covid))` was not decoration. Compare it with the way people write loops when nobody has told them otherwise:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrow <- function(n) {\n  x <- c()\n  for (i in 1:n) x <- c(x, i)\n  x\n}\n\nprealloc <- function(n) {\n  x <- numeric(n)\n  for (i in seq_len(n)) x[i] <- i\n  x\n}\n\nsizes <- c(10000, 20000, 40000)\n\ntibble(\n  n             = sizes,\n  grow_secs     = map_dbl(sizes, function(n) system.time(grow(n))[[\"elapsed\"]]),\n  prealloc_secs = map_dbl(sizes, function(n) system.time(prealloc(n))[[\"elapsed\"]])\n) %>%\n  mutate(grow_vs_previous_row = round(grow_secs / lag(grow_secs), 1))\n#> # A tibble: 3 × 4\n#>       n grow_secs prealloc_secs grow_vs_previous_row\n#>   <dbl>     <dbl>         <dbl>                <dbl>\n#> 1 10000    0.0810       0.00200                 NA  \n#> 2 20000    0.273        0                        3.4\n#> 3 40000    1.06         0.00100                  3.9\n```\n:::\n\n\nThe last column is `lag()` again, earning its keep outside a mutate on the COVID data. Each doubling of `n` multiplies the growing version's time by roughly four. That is the signature of a quadratic cost, and here is where it comes from: `x <- c(x, i)` does not append. R has no append. It allocates a brand new vector one element longer, copies the whole of `x` into it, adds the new value, and throws the old one away. Do that `n` times and you have copied roughly `n²/2` values.\n\n`prealloc_secs` barely moves, because `x[i] <- value` writes into memory that already exists. Those numbers are down at the resolution of the timer, which is why there is no ratio column for them.\n\nYour exact seconds will differ from mine. On a 345-day dataset none of this matters. On a stochastic simulation with 100,000 iterations it is the difference between a coffee break and lunch, and it is the single most common performance bug in student R code.\n\n## `seq_along()`, `seq_len()`, and the 1:0 trap\n\nYou will see `1:length(x)` and `1:nrow(df)` everywhere, including in code written by people who know better. They are wrong in exactly one case, and it is a case that happens.\n\n`:` counts downwards if it has to.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1:0\n#> [1] 1 0\n```\n:::\n\n\nNot empty. A vector of length two, counting down. So a loop written as `1:nrow(df)` over a data frame with no rows runs **twice**, with `i` equal to 1 and then 0.\n\nHere is a filter that finds nothing, because Singapore never recorded more than 1,426 cases in a day:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquiet <- covid %>% filter(daily_cases > 2000)\n\nnrow(quiet)\n#> [1] 0\n```\n:::\n\n\n::: {.callout-important}\n## Predict first\n\nThe next chunk loops over `quiet` using `1:nrow(quiet)` and prints one line per row. `quiet` has zero rows. Commit to a number of lines before you scroll.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in 1:nrow(quiet)) {\n  cat(\"Day\", format(quiet$date[i]), \"had\", quiet$daily_cases[i], \"new cases\\n\")\n}\n#> Day NA had NA new cases\n#> Day  had  new cases\n```\n:::\n\n\nTwo lines, and neither is true. The first is `i = 1`, and asking a zero-row tibble for its first row gives `NA`. The second is `i = 0`, and index zero in R returns a zero-length vector, which `cat()` prints as nothing at all. No error. If that loop had been accumulating a total instead of printing, you would now have `NA` where the right answer was \"there were no such days\".\n\n`seq_len()` and `seq_along()` never count backwards. They return an empty sequence when there is nothing to iterate over, and a loop over an empty sequence does not run:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseq_len(nrow(quiet))\n#> integer(0)\n\nfor (i in seq_len(nrow(quiet))) {\n  cat(\"Day\", format(quiet$date[i]), \"had\", quiet$daily_cases[i], \"new cases\\n\")\n}\n\ncat(\"finished, and printed nothing\\n\")\n#> finished, and printed nothing\n```\n:::\n\n\nUse `seq_along(x)` when you are walking a vector or list, and `seq_len(nrow(df))` when you are walking the rows of a data frame. It costs three extra characters and removes a whole category of bug.\n\n## `while`, when you do not know how many steps\n\n`for` needs to know the number of iterations before it starts. When the stopping condition depends on what you find, use `while`.\n\nHalf of Singapore's 2020 cases is 29,300 or thereabouts. Which day did the cumulative count cross that?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntarget <- max(covid$confirmed) / 2\ni <- 1\n\nwhile (covid$confirmed[i] < target) {\n  i <- i + 1\n}\n\ncovid$date[i]\n#> [1] \"2020-05-20\"\ncovid$confirmed[i]\n#> [1] 29364\ni\n#> [1] 120\nnrow(covid) - i\n#> [1] 225\n```\n:::\n\n\nHalf the year's cases had accumulated by 20 May, on day 120 of 345, with 225 days of the year still to run. That asymmetry is the dormitory outbreak, and it is worth sitting with for a moment.\n\nTwo things about `while`. Something inside the body must change the condition, or it runs forever; here it is `i <- i + 1`, and forgetting that line is the classic way to hang your R session. (Escape, or the stop button in RStudio, gets you out.) And the condition must eventually become false. If no day had crossed the target, `i` would keep climbing past 345 and `covid$confirmed[346]` would be `NA`, at which point R stops with a real error rather than looping forever:\n\n```\nError in while (covid$confirmed[i] < target) { :\n  missing value where TRUE/FALSE needed\n```\n\nThat message is worth memorising. It nearly always means a comparison produced `NA`, and `NA` is neither true nor false, so `while` and `if` refuse to guess.\n\n## `map()` and friends\n\nLoops that build a result one element at a time are common enough that purrr, part of the tidyverse, gives them a shorter form. `map(x, f)` calls `f` on each element of `x` and returns a **list** of the results, always the same length as `x`.\n\nLet me bring `month_summary()` across from @sec-functions. Chapters render in fresh sessions, so it has to be defined again here:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary <- function(df, which_month) {\n  start <- floor_date(as.Date(which_month), \"month\")\n\n  if (!start %in% df$month) {\n    stop(\"No data for \", format(start, \"%B %Y\"), \". The data covers \",\n         format(min(df$month), \"%B %Y\"), \" to \",\n         format(max(df$month), \"%B %Y\"), \".\", call. = FALSE)\n  }\n\n  df %>%\n    filter(month == start) %>%\n    summarise(\n      month      = start,\n      days       = n(),\n      total      = sum(daily_cases),\n      mean_daily = round(mean(daily_cases), 1),\n      peak       = max(daily_cases),\n      peak_date  = date[which.max(daily_cases)],\n      high_days  = sum(severity == \"High\")\n    )\n}\n\nall_months <- unique(covid$month)\nall_months\n#>  [1] \"2020-01-01\" \"2020-02-01\" \"2020-03-01\" \"2020-04-01\" \"2020-05-01\"\n#>  [6] \"2020-06-01\" \"2020-07-01\" \"2020-08-01\" \"2020-09-01\" \"2020-10-01\"\n#> [11] \"2020-11-01\" \"2020-12-01\"\n```\n:::\n\n\nNow the payoff for having made it return a one-row tibble:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- all_months %>%\n  map(function(m) month_summary(covid, m)) %>%\n  list_rbind()\n\nmonthly\n#> # A tibble: 12 × 7\n#>    month       days total mean_daily  peak peak_date  high_days\n#>    <date>     <int> <dbl>      <dbl> <dbl> <date>         <int>\n#>  1 2020-01-01    10    13        1.3     3 2020-01-30         0\n#>  2 2020-02-01    29    89        3.1     9 2020-02-14         0\n#>  3 2020-03-01    31   824       26.6    73 2020-03-25         0\n#>  4 2020-04-01    30 15243      508.   1426 2020-04-20        18\n#>  5 2020-05-01    31 18715      604.    932 2020-05-01        31\n#>  6 2020-06-01    30  9023      301.    569 2020-06-03        12\n#>  7 2020-07-01    31  8298      268.    513 2020-07-25        12\n#>  8 2020-08-01    31  4607      149.    908 2020-08-05         4\n#>  9 2020-09-01    30   953       31.8    86 2020-09-11         0\n#> 10 2020-10-01    31   250        8.1    19 2020-10-01         0\n#> 11 2020-11-01    30   203        6.8    18 2020-11-11         0\n#> 12 2020-12-01    31   381       12.3    30 2020-12-31         0\n```\n:::\n\n\nTwelve calls, twelve one-row tibbles, stacked into a table, in three lines. `map()` did the iterating and `list_rbind()` did the stacking. Had `month_summary()` returned a list, `list_rbind()` would have refused, which is the argument made at the end of @sec-functions.\n\nCheck the arithmetic against something you already know:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(monthly$total) == max(covid$confirmed)\n#> [1] TRUE\n```\n:::\n\n\nThe monthly totals add back to 58,599. May was the worst month by volume, with 18,715 cases and every single one of its 31 days classed High. April held the single worst day, 1,426 on the 20th.\n\n`map()` always returns a list. When you know each result is a single number, `map_dbl()` returns a plain numeric vector instead, which is usually what you want:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_dbl(all_months, function(m) month_summary(covid, m)$mean_daily)\n#>  [1]   1.3   3.1  26.6 508.1 603.7 300.8 267.7 148.6  31.8   8.1   6.8  12.3\n```\n:::\n\n\nThere is a whole family: `map_chr()` for strings, `map_int()` for integers, `map_lgl()` for `TRUE`/`FALSE`. They are stricter than `map()` on purpose. If one of your twelve results comes back as text when you asked for `map_dbl()`, you get an error instead of a silently mixed list.\n\n`walk()` is for when you want the side effect and not the value: printing, saving files, writing plots to disk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwalk(all_months, function(m) {\n  s <- month_summary(covid, m)\n  cat(format(s$month, \"%B\"), \"-\", s$total, \"cases,\", s$high_days, \"High days\\n\")\n})\n#> January - 13 cases, 0 High days\n#> February - 89 cases, 0 High days\n#> March - 824 cases, 0 High days\n#> April - 15243 cases, 18 High days\n#> May - 18715 cases, 31 High days\n#> June - 9023 cases, 12 High days\n#> July - 8298 cases, 12 High days\n#> August - 4607 cases, 4 High days\n#> September - 953 cases, 0 High days\n#> October - 250 cases, 0 High days\n#> November - 203 cases, 0 High days\n#> December - 381 cases, 0 High days\n```\n:::\n\n\n`walk()` returns its input invisibly, so nothing clutters the console except what you asked to print. Using `map()` here would work and would also dump twelve tibbles underneath your report.\n\n## The loop you cannot vectorise\n\nHere is the case that justifies the whole chapter.\n\nContact tracing has a capacity. Whatever the team's size, it can work through so many cases a day, and on a day when more arrive than that, the surplus waits until tomorrow. So the queue at the end of today is the queue at the end of yesterday, plus today's new cases, minus what the team got through. And it stops at zero, because a team that clears its desk by lunchtime cannot bank the spare afternoon against next month.\n\n$$\nQ_t = \\max\\left(0,\\ Q_{t-1} + C_t - k\\right)\n$$\n\n$C_t$ is the cases reported on day $t$, $k$ is the number the team can process in a day, and $Q_t$ is what is still waiting when they go home. Every $Q$ on the right sits one day behind the $Q$ on the left. You cannot compute 14 June without 13 June, which needs 12 June, and so on back to January. `lag()` is no help, because `lag()` shifts a column that already exists and here the column is the one you are creating.\n\nGive the team 300 cases a day. Singapore averaged 170 a day across 2020, so on paper that is a team with room to spare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncapacity <- 300\n\nbacklog <- numeric(nrow(covid))\nbacklog[1] <- max(0, covid$daily_cases[1] - capacity)\n\nfor (t in 2:nrow(covid)) {\n  backlog[t] <- max(0, backlog[t - 1] + covid$daily_cases[t] - capacity)\n}\n\nqueue <- covid %>%\n  select(date, daily_cases) %>%\n  mutate(backlog = backlog)\n\nqueue %>%\n  filter(date %in% as.Date(c(\"2020-04-12\", \"2020-04-13\", \"2020-05-01\",\n                             \"2020-06-14\", \"2020-08-01\", \"2020-10-14\")))\n#> # A tibble: 6 × 3\n#>   date       daily_cases backlog\n#>   <date>           <dbl>   <dbl>\n#> 1 2020-04-12         233       0\n#> 2 2020-04-13         386      86\n#> 3 2020-05-01         932    8869\n#> 4 2020-06-14         407   19172\n#> 5 2020-08-01         307   16680\n#> 6 2020-10-14           5       0\n```\n:::\n\n\nThe loop starts at `t = 2` because day one has nothing before it. That is the same edge case as the `if (i == 1)` branch in the very first loop of this chapter, handled by starting the counter one step in instead of branching inside the body.\n\nNow the version everybody writes first. The queue looks like a running total of the daily excess, and R has a function for running totals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnaive <- pmax(0, cumsum(covid$daily_cases - capacity))\n\nmax(naive)\n#> [1] 0\nmax(backlog)\n#> [1] 19172\n```\n:::\n\n\nZero. The cumulative sum says the tracing team never fell behind on a single day of 2020, while the loop has them 19,172 cases deep in the middle of June.\n\nThe damage is done in the first eighty-two days. Singapore did not record more than 300 cases in a day until 13 April, and every day before that hands `cumsum()` a negative number to bank. By 12 April the running total sits at -22,068, and the dormitory outbreak has to work all of that off before the sum turns positive. Across the whole year it never manages it: 58,599 cases against 345 days of 300 is 103,500. So `pmax()` on the outside flattens everything to zero.\n\nWrapping the clamp around the outside is the mistake. `max(0, ...)` has to happen at every step, because $Q_t$ depends on the *clamped* $Q_{t-1}$, and once the queue has hit zero it has forgotten everything before it. No cumulative function carries a value that gets reset partway along; `cumsum()` by construction never forgets a term it has already added. Take the clamp out and `cumsum()` is exactly right, which is the thing to notice. One specific piece of the model forces the loop, and being able to point at which piece is how you tell a calculation that needs a loop from one you have not thought about hard enough.\n\npurrr does have a function that holds running state for you. `accumulate()` gives the identical vector:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc <- accumulate(\n  covid$daily_cases[-1],\n  function(q, cases) max(0, q + cases - capacity),\n  .init = max(0, covid$daily_cases[1] - capacity)\n)\n\nidentical(backlog, acc)\n#> [1] TRUE\n```\n:::\n\n\nThat is a real convenience, and you should be clear about what it buys. `accumulate()` moves the bookkeeping into a function argument; the iteration underneath is unchanged. It still visits 13 June before 14 June, because it has to. Writing a recurrence more compactly does not make the sequential dependency go away.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqueue %>%\n  ggplot(aes(date, backlog)) +\n  geom_area(fill = nus_colours[[\"blue\"]], alpha = 0.15) +\n  geom_line(linewidth = 0.8) +\n  scale_x_date(date_labels = \"%b\") +\n  scale_y_continuous(labels = label_comma()) +\n  labs(\n    x = NULL, y = \"Cases waiting\",\n    title = \"A team clearing 300 a day ends up two months behind\",\n    caption = \"Illustrative capacity. Not Singapore's actual tracing capacity.\"\n  )\n```\n\n::: {.cell-output-display}\n![The tracing backlog implied by a team clearing 300 cases a day, applied to Singapore's 2020 reported cases. Illustrative capacity, not a figure published by anyone.](iteration_files/figure-html/queue-plot-1.svg)\n:::\n:::\n\n\nThe queue builds through the dormitory outbreak, peaks at 19,172 on 14 June and does not empty until 14 October, having been non-zero on 184 of 345 days. The date of that peak is the interesting part. Cases peaked on 20 April, and the workload peaked 55 days later, because a queue keeps growing for as long as arrivals exceed capacity rather than for as long as arrivals are rising. You cannot read that off the case curve. It only appears once you carry the state forward day by day.\n\nThe shape of this is the shape of every compartmental model you will write later in the course: a state, a rule for getting from today's state to tomorrow's, and a loop to run the rule. Swap the queue for susceptible, infectious and recovered and the code around it barely changes. That is the argument for spending an evening on `for` in a course that otherwise spends its time on `mutate()`.\n\n## Exercises\n\n::: {#exr-loop-vs-lag}\n## Cumulative deaths, both ways\n\nDo for `deaths` what this chapter did for `confirmed`: compute daily deaths with an explicit `for` loop, then again with `lag()`, then check the two against each other with `identical()`.\n\nThe deaths column will not behave like the cases column, and finding out how is the exercise. Compare the sum of your daily deaths against the final cumulative figure of 29 and account for any difference before you move on.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\n`deaths` starts with a long run of missing values, and the first number that appears is not 1. Look at `head(covid$deaths, 65)` and ask what differencing can possibly recover from a series that begins part-way up.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-loop-vs-lag)\n\n::: {#exr-tracing-backlog}\n## How big does the team need to be?\n\nLift the backlog loop into a function of `capacity` that takes a vector of daily cases and returns the backlog vector, then run it for teams clearing 200, 300, 400, 600 and 800 cases a day. Build one table with the peak backlog, the date of that peak, the number of days the team spent behind, and whether the queue ever cleared again after peaking.\n\nThen answer from your own output. Doubling the team from 300 a day to 600 a day does not halve the peak backlog. What does it do instead, and what is it about Singapore's case series that makes it come out that way?\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\nThis is `month_summary()` and `map()` again: a function of one argument that returns a one-row tibble, then `map()` and `list_rbind()` to stack five of them. `which.max()` gives you the position of the peak, and for \"did it clear\" you want whether any value *after* that position is zero. Keep `max(0, ...)` inside the loop, which is the whole point of the section above. If the last question will not come, compare `sum(covid$daily_cases > 300)` against `sum(covid$daily_cases > 600)`.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-tracing-backlog)\n",
    "supporting": [
      "iteration_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}