{
  "hash": "693798b813cd8557f250a29c59ba8a96",
  "result": {
    "engine": "knitr",
    "markdown": "# A monthly situation report {#sec-capstone}\n\n\n\n\n\nUp to now every chapter has handed you a question with the shape of the answer already showing.\nFilter this, group by that, plot the result. Real analysis doesn't arrive in that shape. It\narrives as a request from someone who wants to know what happened, by Friday, in a form they can\nput in front of a committee.\n\nSo here is the request. You pick a month of Singapore's 2020 and write the report. I'll do April\nfirst so you can see where the bar is, then August is yours.\n\n## The brief\n\nOne month. One page. On that page:\n\na table that gives the reader the month in numbers, two figures that show something the table\ncan't, and three sentences of interpretation. Three sentences, not three paragraphs. The\nsentence limit is the hard part and it's deliberate. Anyone can produce eight paragraphs of\nhedged description. Deciding which three things matter is the work.\n\nAssume the reader is a public health officer who knows Singapore and does not know R. They will\nnot read your code. They will look at the figures first, the table second, and your sentences\nonly if the figures made them curious.\n\n## What a good report contains\n\nThere are six things I look for, and they are all things you already know how to do.\n\n1. **The month is stated, and so is the denominator.** How many days does the month have, and\n   how many of them carry data? Every month in this file is complete, but saying so is what\n   separates a report from an assumption.\n2. **A count and a shape.** A total tells you the size of the month. A median, a maximum and\n   the date of the maximum tell you whether that total came from a steady grind or one bad day.\n   Report both.\n3. **A table with a unit the reader can hold.** Days are too fine for a monthly table and the\n   month itself is too coarse. Weeks work.\n4. **Two figures that answer different questions.** Two views of the case curve is one figure\n   drawn twice. Pair the epidemic curve with something else in the file: mobility, the\n   stringency index, the severity mix.\n5. **Every figure has a title that states a finding.** \"Daily cases, April 2020\" is a label.\n   \"Cases rose for 13 days after the circuit breaker began\" is a finding. Titles that make a\n   claim force you to check the claim.\n6. **At least one caveat that comes from looking at the data, not from a template.** \"Data may\n   be incomplete\" is a template. \"The 5 August count is four times the next highest August day\n   and needs an explanation before it goes in a mean\" is analysis.\n\n## April 2020, worked\n\n### A script that stands on its own\n\nYour report script must be readable from the top without any hidden state. That means it reads\nthe file and builds its own columns, in view, before it uses them. This is exactly the pipeline\nfrom the conditionals chapter, written out once so nothing in the report depends on something\nyou can't see.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid <- read_covid() %>%\n  arrange(date) %>%\n  mutate(\n    daily_cases  = confirmed - lag(confirmed, default = 0),\n    daily_deaths = deaths - lag(deaths, default = 0),\n    severity = case_when(\n      daily_cases <  100 ~ \"Low\",\n      daily_cases <= 300 ~ \"Medium\",\n      daily_cases >  300 ~ \"High\"\n    ),\n    severity = factor(severity, levels = c(\"Low\", \"Medium\", \"High\")),\n    month = floor_date(date, \"month\")\n  )\n```\n:::\n\n\nIf you're writing this in a script of your own rather than inside the book's project, swap\n`read_covid()` for `read_csv(here(\"data\", \"sg_covid_data.csv\"))`. That helper exists so the\nchapters don't repeat a file path forty times, and nothing else in the pipeline depends on it.\n\nThen pick the month once, at the top, in a named object. When August comes round you change one\nline rather than hunting for `\"2020-04\"` scattered through twenty chunks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport_month <- as.Date(\"2020-04-01\")\n\napril <- covid %>%\n  filter(month == report_month)\n\nnrow(april)\n#> [1] 30\n```\n:::\n\n\nThirty rows for a thirty-day month. That check takes two seconds and it is the cheapest error\nyou will ever catch.\n\n### How heavy was the month\n\n::: {.callout-important}\n## Predict before you run this\n\nApril 2020 has one day that dwarfs the rest. Write down the date you think it fell on before you\nread the next output. Most people put it in the first week, on the theory that the circuit\nbreaker started on 7 April and things improved from there.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril %>%\n  summarise(\n    days         = n(),\n    cases        = sum(daily_cases),\n    mean_daily   = mean(daily_cases),\n    median_daily = median(daily_cases),\n    peak         = max(daily_cases),\n    peak_date    = date[which.max(daily_cases)],\n    deaths       = sum(daily_deaths)\n  )\n#> # A tibble: 1 × 7\n#>    days cases mean_daily median_daily  peak peak_date  deaths\n#>   <int> <dbl>      <dbl>        <dbl> <dbl> <date>      <dbl>\n#> 1    30 15243       508.         488.  1426 2020-04-20     12\n```\n:::\n\n\nThe peak is 20 April, thirteen days after the circuit breaker began. Cases went up, and kept\ngoing up, for two weeks after Singapore closed workplaces and told everyone to stay home.\n\nThat is not a paradox and it is worth being precise about why. Reported cases are the output of\na testing programme, not a direct measurement of infection. Through April, testing in the\nmigrant-worker dormitories was expanding fast, and the dormitory outbreak dominated the national\ncount from April to August. A rising reported curve during that period is partly transmission\nand partly the swab rate catching up with infections that had already happened. You cannot\nseparate the two from this file, which is a thing to say in your report rather than a thing to\nhide.\n\nTwo small notes on that output. `median_daily` prints as `488.` with a trailing full stop, which\nis the tibble telling you the value isn't a whole number. It's 487.5, the average of the two\nmiddle days. And `deaths` is 12 here, which is trustworthy for April because the `deaths` column\nhas no missing values from 21 March onwards. Earlier in the year it does, 59 leading `NA`s, and\nlag-differencing across them recovers only 27 of the year's 29 deaths. If your chosen month is\nJanuary, February or March, say that out loud.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril %>%\n  count(severity)\n#> # A tibble: 3 × 2\n#>   severity     n\n#>   <fct>    <int>\n#> 1 Low          5\n#> 2 Medium       7\n#> 3 High        18\n```\n:::\n\n\nEighteen of April's thirty days were over 300 cases. Across the whole year only 77 days were,\nso April holds nearly a quarter of the year's worst days in a single month.\n\n### The table\n\nWeeks are the right grain for a monthly table. `floor_date(date, \"week\", week_start = 1)` puts\neach date on its Monday. I set `week_start` explicitly because lubridate's default is Sunday and\nhalf the people reading this expect Monday. Making the assumption visible costs one argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril_weeks <- april %>%\n  mutate(week = floor_date(date, \"week\", week_start = 1)) %>%\n  group_by(week) %>%\n  summarise(\n    days       = n(),\n    cases      = sum(daily_cases),\n    mean_daily = round(mean(daily_cases)),\n    peak       = max(daily_cases),\n    retail     = round(mean(retail_and_recreation_percent_change_from_baseline)),\n    stringency = round(mean(stringency_index), 1)\n  )\n\napril_weeks\n#> # A tibble: 5 × 7\n#>   week        days cases mean_daily  peak retail stringency\n#>   <date>     <int> <dbl>      <dbl> <dbl>  <dbl>      <dbl>\n#> 1 2020-03-30     5   383         77   120    -23       41.7\n#> 2 2020-04-06     7  1223        175   287    -53       71  \n#> 3 2020-04-13     7  4056        579   942    -61       76.8\n#> 4 2020-04-20     7  7036       1005  1426    -67       77.6\n#> 5 2020-04-27     4  2545        636   799    -67       76.8\n```\n:::\n\n\nLook at the `days` column before you look at anything else. The first row covers five days, not\nseven, because April 2020 started on a Wednesday and the week beginning 30 March mostly belongs\nto March. The last row covers four. Any comparison of `cases` across those rows is comparing\ndifferent amounts of time, which is why `mean_daily` is in the table and why `days` is in it too.\nLeave `days` out and a reader will read 383 against 1,223 as a threefold rise when part of it is\nnothing more than two extra days.\n\nThe rest of the table tells a fairly clean story. Weekly totals climb from 383 to 7,036 and then\nfall back. Mean retail mobility drops from 23% below baseline in the first partial week to 67%\nbelow in each of the last two. Mean stringency goes from 41.7 to 71 in one step and sits in the\nseventies for the rest of the month.\n\n### The first figure: the epidemic curve\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncb_start <- as.Date(\"2020-04-07\")\n\nggplot(april, aes(date, daily_cases)) +\n  geom_col(fill = nus_colours[[\"blue\"]]) +\n  geom_vline(xintercept = cb_start, colour = nus_colours[[\"crimson\"]],\n             linetype = \"dashed\") +\n  annotate(\"text\", x = cb_start + 1, y = 1350, hjust = 0, size = 3.2,\n           colour = nus_colours[[\"crimson\"]], label = \"Circuit breaker begins\") +\n  scale_x_date(date_breaks = \"1 week\", date_labels = \"%d %b\") +\n  scale_y_continuous(labels = label_comma()) +\n  labs(\n    title = \"Cases rose for 13 days after the circuit breaker began\",\n    subtitle = \"Singapore, new COVID-19 cases reported each day, April 2020\",\n    x = NULL, y = \"New cases reported\",\n    caption = \"Source: COVID-19 Data Hub. Reported cases, not infections.\"\n  )\n```\n\n::: {.cell-output-display}\n![Daily reported cases in Singapore, April 2020, with the start of the circuit breaker marked.](capstone_files/figure-html/fig-april-cases-1.svg){#fig-april-cases}\n:::\n:::\n\n\nColumns rather than a line, because these are counts of things that happened on discrete days\nand a line implies you could read a value off it halfway between two dates. The dashed rule and\nthe label do the work that a paragraph of text would otherwise have to do. The caption carries\nthe source and the one warning the reader most needs.\n\nThe date breaks are weekly and the labels are `\"%d %b\"`, so the axis reads 06 Apr, 13 Apr, 20\nApr. Left to itself ggplot2 would have chosen something reasonable but not necessarily aligned\nwith the weeks in your table, and a reader who is trying to match figure to table will notice.\n\n### The second figure: what people actually did\n\nThe case curve says what was reported. The mobility columns say what people did, which is a\ndifferent question and the reason this file is more interesting than a case line on its own.\n\nTwo series on one set of axes means one row per series per date, so the two columns have to\nbecome one column of values plus one column of labels. `pivot_longer()` does that. It's from\ntidyr, which came in with the tidyverse, and it's the only function in this chapter you haven't\nalready met.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril_mobility <- april %>%\n  select(\n    date,\n    `Retail and recreation` = retail_and_recreation_percent_change_from_baseline,\n    Workplaces              = workplaces_percent_change_from_baseline\n  ) %>%\n  pivot_longer(-date, names_to = \"series\", values_to = \"change\")\n\napril_mobility\n#> # A tibble: 60 × 3\n#>    date       series                change\n#>    <date>     <chr>                  <dbl>\n#>  1 2020-04-01 Retail and recreation    -23\n#>  2 2020-04-01 Workplaces               -22\n#>  3 2020-04-02 Retail and recreation    -25\n#>  4 2020-04-02 Workplaces               -27\n#>  5 2020-04-03 Retail and recreation    -21\n#>  6 2020-04-03 Workplaces               -20\n#>  7 2020-04-04 Retail and recreation    -24\n#>  8 2020-04-04 Workplaces                -7\n#>  9 2020-04-05 Retail and recreation    -23\n#> 10 2020-04-05 Workplaces               -10\n#> # ℹ 50 more rows\n```\n:::\n\n\nRenaming inside `select()` is what gets you a readable legend without a second call. Backticks\naround `Retail and recreation` because it has spaces in it; R will accept a name like that as\nlong as you quote it that way, and here it's worth it because that string goes straight onto the\nplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(april_mobility, aes(date, change, colour = series)) +\n  geom_hline(yintercept = 0, colour = nus_colours[[\"muted\"]], linewidth = 0.3) +\n  geom_line() +\n  geom_vline(xintercept = cb_start, colour = nus_colours[[\"crimson\"]],\n             linetype = \"dashed\") +\n  scale_x_date(date_breaks = \"1 week\", date_labels = \"%d %b\") +\n  labs(\n    title = \"Movement fell the day the rules changed, and stayed down\",\n    subtitle = \"Percent change from Google's 3 January to 6 February 2020 baseline\",\n    x = NULL, y = \"Change from baseline (%)\", colour = NULL,\n    caption = \"Weekends are not comparable with weekdays: the baseline is a median by day of week.\"\n  )\n```\n\n::: {.cell-output-display}\n![Retail and workplace mobility in April 2020, as percent change from Google's pre-pandemic baseline.](capstone_files/figure-html/fig-april-mobility-1.svg){#fig-april-mobility}\n:::\n:::\n\n\nThe step at 7 April is the whole point of the figure. Retail goes from 15% below baseline on 6\nApril to 51% below on 7 April; workplaces go from 24% below to 52% below on the same day.\nBehaviour changed overnight. The case curve took a fortnight to turn.\n\nNow the two things in that figure that are not what they look like. The deep spike down to 83%\nbelow baseline is 10 April, which was Good Friday, a public holiday. The eight deepest\nworkplace-mobility days in the entire year are all public holidays, so any dip you see in this\nseries should be checked against a calendar before it's called a policy effect.\n\nThe regular bumps upwards are weekends, and they run the opposite way to intuition. Google's\nbaseline is a median computed separately for each day of the week, so a Sunday is compared with\npre-pandemic Sundays. Workplace activity on a normal Sunday was already low, which leaves less\nroom to fall.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napril %>%\n  filter(date >= cb_start) %>%\n  mutate(weekday = wday(date, label = TRUE)) %>%\n  group_by(weekday) %>%\n  summarise(\n    days       = n(),\n    workplaces = mean(workplaces_percent_change_from_baseline)\n  )\n#> # A tibble: 7 × 3\n#>   weekday  days workplaces\n#>   <ord>   <int>      <dbl>\n#> 1 Sun         3      -50  \n#> 2 Mon         3      -66  \n#> 3 Tue         4      -63  \n#> 4 Wed         4      -66.5\n#> 5 Thu         4      -67  \n#> 6 Fri         3      -71.7\n#> 7 Sat         3      -52.3\n```\n:::\n\n\nWeekdays sit between 63 and 72 points below baseline. Saturday and Sunday sit around 50. Nobody\nwent back to the office at the weekend. The denominator changed.\n\nIf you want the two figures stacked as a single image for a one-page PDF, patchwork will do it\nwith `p_cases / p_mobility` once you've assigned each plot to a name. I've kept them separate\nhere so each keeps its full height on screen.\n\n### The three sentences\n\n> April carried 15,243 reported cases, 26% of Singapore's 2020 total, with 18 of its 30 days\n> above 300 cases and 12 deaths; only May, at 18,715, was heavier.\n>\n> Reported cases kept climbing for 13 days after the circuit breaker took effect on 7 April,\n> peaking at 1,426 on 20 April, a pattern that reflects the pace of testing in the\n> migrant-worker dormitories as much as the timing of infection.\n>\n> Movement changed the day the rules did, with retail activity falling from 15% below baseline\n> on 6 April to 51% below on 7 April and staying within a few points of its floor for the rest\n> of the month, so the behavioural response was immediate even though the case curve was not.\n\nThree sentences, three different jobs. The first sizes the month against the year. The second\naddresses the thing a reader will get wrong if you don't. The third brings in the second data\nsource and draws the contrast that makes the report worth reading.\n\nNotice what isn't in there. No recommendation, because nothing in this file supports one. No\nclaim that the circuit breaker worked or didn't, because a single month of a single country with\nno counterfactual cannot tell you. A situation report describes the situation. Resist the pull\nto conclude.\n\n## What this analysis does not tell you\n\nThis section is not decoration. Write a version of it for your own month, and make it specific.\n\n**Raw counts ignore population.** Fifteen thousand cases is a number of people, not a rate. To\nturn it into a rate you need a denominator, and the honest denominator here is not obvious.\nRoughly 323,000 work-permit holders lived in dormitories of all types in 2020, of whom about\n200,000 were in the 43 purpose-built dormitories. A case rate computed over the national\npopulation and a case rate computed over the dormitory-resident population are different\nquantities, and in April 2020 they were not remotely close. This file gives you neither\ndenominator.\n\n**Raw counts ignore testing volume.** A reported case requires a test, a positive result and a\nreport. Change the number of tests and the case count changes without a single extra infection.\nThere's no test-count column in this file, so you cannot compute test positivity, which is the\nstandard way of asking whether a rise in cases is a rise in transmission or a rise in looking.\nWhen your curve rises, you are entitled to say that reported cases rose. You are not entitled to\nsay that infections rose.\n\n**One national count is averaging two epidemics.** From April to August 2020 the dormitory\noutbreak dominated Singapore's case counts, and it had different dynamics from transmission in\nthe wider community: different living density, different age structure, different testing\nregime, different intervention. MOH's own daily updates reported those streams separately at the\ntime. This file carries a single national total, so every mean you compute over those months is\na weighted average of two processes, with weights you can't see and that change from week to\nweek. That is a limitation of the file, not of the epidemiology, and you should say which one\nyou're reporting.\n\n5 August 2020 is the sharpest example. That day records 908 cases, against an August median of\n91 and a next-highest August day of 313. Nine hundred and three of those 908 were dormitory\nresidents, and 581 were linked to a single cluster at Acacia Lodge. MOH attributed the day's\nnumbers to clearance testing in dormitories picking up past infections. Put that day in a mean\nwithout comment and you have published a wave that did not happen on that day.\n\nOne more, and I'm flagging it as my own reading rather than something you can verify from the\ndata. Google's mobility series are built from location history on the phones of users who have\nthat setting switched on, and Google does not publish these series broken down by nationality or\nwork-permit status. Whether the movement of people confined to dormitories under quarantine\nappears in these curves at all is not a question this file can answer. I would not lean on\nmobility to describe what happened inside the dormitories in April. That is the difference\nbetween running the code and doing the epidemiology: the code will compute a mean of anything\nyou hand it.\n\n## Your turn\n\n::: {#exr-sitrep}\n## Write the August 2020 situation report\n\nProduce the one-page report for August 2020: a table, two figures, three sentences of\ninterpretation, and a short note on what your analysis does not tell you.\n\nAugust is a harder month than April, and not because the code is harder. The code is the same\ncode. August is harder because the month contains a decision that April doesn't, and how you\nhandle it is most of what separates a good report from a competent one.\n\nYou are done when someone who has never seen the data could read your page and come away with a\ncorrect impression of what August 2020 was like.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\nCompute the maximum, the median and the date of the maximum before you compute anything else,\nand put those three numbers next to each other. If a single day is several times the next\nhighest day, the mean is describing that day rather than the month, and your report has to\ndecide out loud what to do about it.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-sitrep)\n\nIf you want a second month after that, September 2020 is the quiet counterpart: 30 days, every\none of them under 100 cases, a mean of 31.8. Writing an interesting report about a month where\nnothing happens is its own skill, and you will be asked for one eventually.\n",
    "supporting": [
      "capstone_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}