{
  "hash": "0bedea6436ac5d4e56c4eaa71fa64fd7",
  "result": {
    "engine": "knitr",
    "markdown": "# Writing functions {#sec-functions}\n\n\n\n\n\n\n\nCopy-paste is how most people's analysis scripts grow, and it works fine right up until the day it doesn't. The failure is never dramatic. You change one copy, forget the other two, and the script keeps running and keeps producing a number. That number is now wrong and nothing on your screen says so.\n\nThis chapter is about the alternative.\n\n## The rule of three\n\nHere is a question worth asking of the mobility data: on how many days did retail and recreation activity fall more than 30% below its January baseline?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(retail_and_recreation_percent_change_from_baseline < -30) %>%\n  nrow()\n#> [1] 88\n```\n:::\n\n\nEighty-eight days. Your supervisor asks what happens if you use a stricter cut-off. So you copy the block and change the number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(retail_and_recreation_percent_change_from_baseline < -60) %>%\n  nrow()\n#> [1] 48\n```\n:::\n\n\nThen a looser one, because it would be good to know whether the answer is sensitive to where you draw the line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(retail_and_recreation_percent_change_from_baseline < -20) %>%\n  nrow()\n#> [1] 164\n```\n:::\n\n\nThree blocks, 164 days at the loose end and 48 at the strict end, and the analysis is fine. The problem arrives a week later when you decide the dates matter more than the count, and you change `nrow()` to `pull(date)` in the first block. Now block one answers a different question from blocks two and three, and the only record of that decision is in your head.\n\nThe rule of thumb most R programmers converge on is: **once you have copied the same block of code a third time, write a function**. Two copies is a coincidence. Three is a pattern, and a pattern that lives in three places will eventually disagree with itself.\n\n## Anatomy\n\nA function has four parts, and R makes all four visible in the definition:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmobility_alert <- function(df, threshold = -30) {\n  df %>%\n    filter(retail_and_recreation_percent_change_from_baseline < threshold) %>%\n    pull(date)\n}\n```\n:::\n\n\nThe **name** is `mobility_alert`. It goes on the left of `<-`, exactly like any other assignment, because in R a function is a value you store in a variable. There is nothing special about the name; you could have called it `f`, and one day at 11pm you will, and three weeks later you will regret it. Name it after what it returns or what it does.\n\nThe **arguments** are `df` and `threshold`, in the parentheses after `function`. Inside the body they behave as ordinary variables. `threshold` has a **default value** of `-30`, so a caller who has no opinion can leave it out.\n\nThe **body** is everything between the braces. It is ordinary R code, and it can use the arguments freely.\n\nThe **return value** is the value of the last expression evaluated. There is no `return` keyword here and it is not needed. R functions return their last expression automatically, so `pull(date)` is the answer. You will see `return()` in other people's code and it is not wrong, but the idiom in R is to reserve it for early exits, which we will use in a moment.\n\nNow use it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalert_days <- mobility_alert(covid)\n\nlength(alert_days)\n#> [1] 88\nhead(alert_days)\n#> [1] \"2020-04-07\" \"2020-04-08\" \"2020-04-09\" \"2020-04-10\" \"2020-04-11\"\n#> [6] \"2020-04-12\"\ntail(alert_days, 1)\n#> [1] \"2020-07-13\"\n```\n:::\n\n\nEighty-eight days, running from 7 April to 13 July. The 7th of April is the first day of the circuit breaker, which is exactly what you would hope to see from a mobility series that is doing its job.\n\nNotice what the function inherited for free. Because the body uses `filter()`, the 24 missing values in the retail column drop out silently and correctly, and you get 88 days rather than the 112 that the base-R subscript would have handed you. That decision was made back in the chapter on missing data and it is now baked into every call.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(covid, aes(date, retail_and_recreation_percent_change_from_baseline)) +\n  geom_hline(yintercept = -30, linetype = \"dashed\", colour = nus_colours[[\"muted\"]]) +\n  geom_line() +\n  geom_point(\n    data = filter(covid, date %in% alert_days),\n    colour = nus_colours[[\"crimson\"]], size = 0.9\n  ) +\n  labs(\n    x = NULL,\n    y = \"Retail and recreation (% vs baseline)\",\n    title = \"Retail mobility against the alert threshold\"\n  )\n#> Warning: Removed 24 rows containing missing values or values outside the scale range\n#> (`geom_line()`).\n```\n\n::: {.cell-output-display}\n![The 88 days flagged by `mobility_alert()` at its default threshold. Marked days run from the first day of the circuit breaker to mid-July.](functions_files/figure-html/alert-plot-1.svg)\n:::\n:::\n\n\nThe warning about 24 rows removed is the January and early-February gap in the mobility series, and it should appear every time you plot this column. If it ever stops appearing, something upstream has filled those values in and you want to know about it.\n\n## Default arguments earn their keep\n\n`threshold = -30` looks like a convenience. It is doing more work than that, and the reason is the sign convention in this dataset.\n\nGoogle's mobility columns are *percentage change from baseline*. A fall in activity is a negative number. Retail bottoms out at -70 on 24 April. Residential goes the other way and peaks at +55 on 1 May, because when everything else empties out, people are at home. So \"a drop of more than 30%\" is `< -30`, and a reader who thinks in magnitudes rather than signs will reach for `30`.\n\n::: {.callout-important}\n## Predict first\n\nBefore you run the next chunk, write down a number. `mobility_alert(covid, threshold = 30)` asks for the days on which retail mobility was below 30. How many of the 345 days do you think come back?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrong_sign <- mobility_alert(covid, threshold = 30)\n\nlength(wrong_sign)\n#> [1] 321\nhead(wrong_sign, 3)\n#> [1] \"2020-02-15\" \"2020-02-16\" \"2020-02-17\"\n```\n:::\n\n\nThree hundred and twenty-one. Retail mobility spends almost the whole year below +30, so the filter keeps nearly everything, and the first \"alert day\" is 15 February, when nothing was happening. No error, no warning, no red text. Just a plausible-looking vector of dates that answers a question nobody asked.\n\nThis is the failure mode that functions are built to reduce. The default value is a decision made once, in the light, by someone who was thinking about signs at the time. Every call that accepts the default inherits that thinking. Only a caller who deliberately overrides it can get it wrong, and a deliberate override is at least visible in the code.\n\nIf you want to be stricter than a default, you can check the argument and refuse:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmobility_alert <- function(df, threshold = -30) {\n  if (threshold > 0) {\n    stop(\"`threshold` should be negative. Mobility is measured as percentage change \",\n         \"from baseline, so a drop of 30% is -30, not 30.\", call. = FALSE)\n  }\n  df %>%\n    filter(retail_and_recreation_percent_change_from_baseline < threshold) %>%\n    pull(date)\n}\n\nmobility_alert(covid, threshold = 30)\n#> Error:\n#> ! `threshold` should be negative. Mobility is measured as percentage change from baseline, so a drop of 30% is -30, not 30.\n```\n:::\n\n\n`call. = FALSE` suppresses the \"Error in mobility_alert(...)\" prefix, which is noise when the message already says everything. Whether to add a check like this is a judgement call. Checks cost lines and they can be wrong themselves. Add them where a wrong answer would be silent, as it is here, and skip them where the code would fall over anyway.\n\n## What happens inside stays inside\n\nA variable created inside a function does not exist after the function returns. R evaluates the body in a fresh environment that is thrown away on the way out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_day <- function(df) {\n  worst <- df$date[which.max(df$daily_cases)]\n  worst\n}\n\npeak_day(covid)\n#> [1] \"2020-04-20\"\n```\n:::\n\n\nThe function created `worst`, used it, and returned it. Now ask for it at the console:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworst\n#> Error:\n#> ! object 'worst' not found\n```\n:::\n\n\nThat error is a feature. If every function left its working variables lying around, a script with thirty functions in it would be a minefield of names that might or might not mean what you think. Scope is what lets you call a variable `i` or `tmp` or `worst` inside a function without wondering what else in your session is called that.\n\nThe traffic goes one way, though. A function can *read* variables from outside itself. If the body mentions a name it does not define, R looks in the environment where the function was written, which is usually your global environment. That is how `mobility_alert()` can call `filter()` at all. It is also how a function can quietly depend on something you forgot you had.\n\n## Stale globals, and why you restart R\n\nNow the more dangerous version of this, because it does not produce an error at all.\n\nThe worksheet this book replaces had an exercise that looped over months, and inside the loop it assigned to a variable at the top level of the script:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (m in c(\"2020-09-01\", \"2020-10-01\", \"2020-11-01\", \"2020-12-01\")) {\n  month_data <- covid %>% filter(month == as.Date(m))\n  cat(format(as.Date(m), \"%B\"), \"mean daily cases:\",\n      round(mean(month_data$daily_cases), 1), \"\\n\")\n}\n#> September mean daily cases: 31.8 \n#> October mean daily cases: 8.1 \n#> November mean daily cases: 6.8 \n#> December mean daily cases: 12.3\n```\n:::\n\n\nFour correct numbers. The loop is fine. But when it finishes, `month_data` is still sitting in the global environment, holding whatever the last iteration put there, which is December.\n\nSeveral exercises later came a bonus question about September. It used `month_data`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"September mean daily cases:\", round(mean(month_data$daily_cases), 1), \"\\n\")\n#> September mean daily cases: 12.3\n\nrange(month_data$date)\n#> [1] \"2020-12-01\" \"2020-12-31\"\n```\n:::\n\n\nThe heading says September. The number is December's. Nothing errors, nothing warns, and 12.3 is a perfectly believable figure for a quiet month. A student who ran that worksheet top to bottom would have written down the wrong answer with total confidence, and so would I.\n\nNow connect this to the rule from the good practice chapter about never saving your workspace and restarting R often. In a fresh session, `month_data` does not exist, and the bonus question fails like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_data\n```\n:::\n\n\n```\nError: object 'month_data' not found\n```\n\nA loud error that stops you, instead of a quiet number that fools you. That trade is the entire argument for restarting R. You are not trying to keep your session tidy for its own sake. You are trying to convert silent wrong answers into noisy ones, because you can fix a noisy one.\n\nThe structural fix is the subject of this chapter. If the calculation lives in a function, there is no top-level `month_data` to go stale, because the variable dies when the function returns.\n\n## Returning more than one thing\n\n`mobility_alert()` returns a vector, which is fine because it has one thing to say. Most summaries have several. Suppose you want, for a given month: how many days, how many cases, the daily mean, the peak and when it happened, and how many days were classed High.\n\nThe obvious move is a list, and it works:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary_list <- function(df, which_month) {\n  start <- floor_date(as.Date(which_month), \"month\")\n  d <- filter(df, month == start)\n  list(\n    month = start,\n    days  = nrow(d),\n    total = sum(d$daily_cases)\n  )\n}\n\nmonth_summary_list(covid, \"2020-04-01\")\n#> $month\n#> [1] \"2020-04-01\"\n#> \n#> $days\n#> [1] 30\n#> \n#> $total\n#> [1] 15243\n```\n:::\n\n\nDo not do this. Return a one-row tibble instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary <- function(df, which_month) {\n  start <- floor_date(as.Date(which_month), \"month\")\n\n  if (!start %in% df$month) {\n    stop(\"No data for \", format(start, \"%B %Y\"), \". The data covers \",\n         format(min(df$month), \"%B %Y\"), \" to \",\n         format(max(df$month), \"%B %Y\"), \".\", call. = FALSE)\n  }\n\n  df %>%\n    filter(month == start) %>%\n    summarise(\n      month      = start,\n      days       = n(),\n      total      = sum(daily_cases),\n      mean_daily = round(mean(daily_cases), 1),\n      peak       = max(daily_cases),\n      peak_date  = date[which.max(daily_cases)],\n      high_days  = sum(severity == \"High\")\n    )\n}\n\nmonth_summary(covid, \"2020-04-01\")\n#> # A tibble: 1 × 7\n#>   month       days total mean_daily  peak peak_date  high_days\n#>   <date>     <int> <dbl>      <dbl> <dbl> <date>         <int>\n#> 1 2020-04-01    30 15243       508.  1426 2020-04-20        18\n```\n:::\n\n\nApril: 30 days, 15,243 cases, a peak of 1,426 on the 20th, and 18 days classified High.\n\nThe reason for the tibble is composition. Sooner or later you will want all twelve months, not one, and a stack of one-row tibbles is a table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist_rbind(list(\n  month_summary(covid, \"2020-04-01\"),\n  month_summary(covid, \"2020-05-01\")\n))\n#> # A tibble: 2 × 7\n#>   month       days total mean_daily  peak peak_date  high_days\n#>   <date>     <int> <dbl>      <dbl> <dbl> <date>         <int>\n#> 1 2020-04-01    30 15243       508.  1426 2020-04-20        18\n#> 2 2020-05-01    31 18715       604.   932 2020-05-01        31\n```\n:::\n\n\nThe same move with lists does not work:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist_rbind(list(\n  month_summary_list(covid, \"2020-04-01\"),\n  month_summary_list(covid, \"2020-05-01\")\n))\n#> Error in `list_rbind()`:\n#> ! Each element of `x` must be either a data frame or `NULL`.\n#> ℹ Elements 1 and 2 are not.\n```\n:::\n\n\n`list_rbind()` is fussy on purpose, and the fussiness is telling you something true. A list has no column types and no guarantee that two of them have the same names in the same order, so stacking them is ambiguous. A one-row tibble carries all of that with it. In @sec-iteration you will generate all twelve summaries in one line and stack them; writing `month_summary()` to return a tibble today is what makes that line short tomorrow.\n\n## The guard clause\n\nThe `if (!start %in% df$month) stop(...)` at the top of `month_summary()` is a **guard clause**: a check that runs before the real work and exits early if the inputs make no sense.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary(covid, \"2021-03-01\")\n#> Error:\n#> ! No data for March 2021. The data covers January 2020 to December 2020.\n```\n:::\n\n\nAsk yourself what the alternative would have been. `filter()` would have returned zero rows and `summarise()` would have run on nothing. Here is that version, with the guard taken out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_summary_unguarded <- function(df, which_month) {\n  start <- floor_date(as.Date(which_month), \"month\")\n  df %>%\n    filter(month == start) %>%\n    summarise(\n      month     = start,\n      days      = n(),\n      total     = sum(daily_cases),\n      peak      = max(daily_cases),\n      peak_date = date[which.max(daily_cases)]\n    )\n}\n\nmonth_summary_unguarded(covid, \"2021-03-01\")\n#> Error in `summarise()` at magrittr/R/pipe.R:136:3:\n#> ℹ In argument: `peak_date = date[which.max(daily_cases)]`.\n#> Caused by error:\n#> ! `peak_date` must be size 1, not 0.\n#> ℹ To return more or less than 1 row per group, use `reframe()`.\n```\n:::\n\n\nR does stop, which is lucky, but look at what it stops on. The message is about `peak_date` being size 0, and `reframe()` is suggested as the fix. Neither has anything to do with what actually went wrong, which is that you asked for a month the data does not contain. A student chasing that message will spend twenty minutes reading about `reframe()`.\n\nDrop `peak_date` from that function and it gets worse, because then nothing is the wrong size and the whole thing succeeds:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncovid %>%\n  filter(month == as.Date(\"2021-03-01\")) %>%\n  summarise(\n    days       = n(),\n    total      = sum(daily_cases),\n    mean_daily = mean(daily_cases),\n    peak       = max(daily_cases)\n  )\n#> Warning: There was 1 warning in `summarise()`.\n#> ℹ In argument: `peak = max(daily_cases)`.\n#> Caused by warning in `max()`:\n#> ! no non-missing arguments to max; returning -Inf\n#> # A tibble: 1 × 4\n#>    days total mean_daily  peak\n#>   <int> <dbl>      <dbl> <dbl>\n#> 1     0     0        NaN  -Inf\n```\n:::\n\n\nZero days, zero cases, a mean of `NaN` and a peak of `-Inf`, delivered as a one-row tibble that will stack happily alongside eleven real months. The warning about `max()` is the only clue, and warnings scroll past.\n\nThat is what the guard buys: a message naming what you asked for, that it isn't there, and what is. When you write an error message, write the one you would want to read at 11pm.\n\nOne more thing about `month_summary()`: it demands a full date, `\"2020-09-01\"` rather than `\"2020-09\"`. That is `as.Date()`'s rule, not mine, and it fails loudly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.Date(\"2020-09\")\n#> Error in `charToDate()`:\n#> ! character string is not in a standard unambiguous format\n```\n:::\n\n\nLoudly is the right behaviour. A month string with no day is ambiguous, and R would rather stop than guess.\n\n## Exercises\n\n::: {#exr-mobility-alert}\n## Generalise the alert\n\n`mobility_alert()` only ever looks at the retail and recreation column. Rewrite it so the caller can choose which mobility series to check, keeping retail as the default so that existing calls still work.\n\nThen use your version to answer: how many days did workplace mobility fall below -60, and how many did parks? Look at the deepest workplace days in particular and see whether you can explain them.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\nPassing a column name into a dplyr verb from inside a function needs the curly-brace operator, `{{ }}`, around the argument. Search the tidyverse documentation for \"programming with dplyr\" if you want the full story, or wrap the argument and see what happens.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-mobility-alert)\n\n::: {#exr-month-summary}\n## Add a judgement to the summary\n\nExtend `month_summary()` with one more column, `verdict`, that reads `\"Escalate\"` when the month had more than five High days and `\"All clear\"` otherwise.\n\nRun it on September 2020 and on April 2020 and check that both verdicts are what you expect from the case counts. Then decide whether five is a defensible cut-off, and make it an argument if you think it isn't.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Stuck? Open for a hint (not the answer)\n\n`high_days` is already computed inside the `summarise()` call, but you cannot refer to a column you are creating in the same `summarise()` in all versions of dplyr. Adding a `mutate()` after the `summarise()` is the reliable way, and `if_else()` handles the two-way choice.\n:::\n\n[Worked solution](solutions.qmd#sec-sol-month-summary)\n",
    "supporting": [
      "functions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}